### ISSUE TITLE
defineFragment

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#106]
After a third and final attempt at `defineFragment`, I landed something that's robust enough to work, has 0 perf overhead for non-fragment nodes, and has no needed DOM placeholders. So far there's support for adjacent fragments, nested fragments, fragments returned from render(), views wthin fragments [1].

There are some caveats. Fragment nodes are not 100% like normal vnodes. They do exist in the vtree, but are flattened and transparent to the dom reconciliation algo. This means that they will not themselves support some lifecycle _hooks (at least initially) or any event handlers (cause they have no dom to bubble through), etc.. However they *can* hold `_key`, `_data`, `_ref` and other vtree-only stuff, if you need to reference some model/key from any hooks or handlers bound to any contained elements.

So far, the implementation adds about 0.6k (min) [2] to every build since support has to be integrated into various parts of the core. There's still some work left to get them fully useful, which will add perhaps another 0.1k-0.3k:

- ~~sig: `defineFragment([ type [, attrs], ] body)`, right now it's only `defineFragment(body)`~~ **DONE**
- ~~explicit vm.redraw() of sub-views with fragment roots~~ **DONE**
- ensure vnode.patch() works (may not be applicable)
- look into adding hooks based on vtree grafting pass rather than dom reconciliation pass
- refine dom reconciliation boundaries and fragment flattening (forward only) when doing fragment root redraw
- html() support
- tests
- ~~fragment root in top-level view (maybe)~~ **PROBABLY NOT**

cc @lawrence-dol

[1] https://github.com/leeoniya/domvm/blob/defineFragment/demos/fragments.html

[2] https://github.com/leeoniya/domvm/commit/93b0247c1c412776a05948acad90eb2444d7a2f9?short_path=90524ff#diff-90524ffa151b37c8b277925c017ad1ba

**Comment by grumpi** [comment]
I personally haven't felt a strong need for `defineFragment`, so far. Sure, there are a few `div`s that I could get rid of, but for the app I'm making it doesn't currently seem to be worth the hassle to deal with (potentially) different behavior between real nodes and fragments.

When I want to insert a list of nodes between other nodes without introducing another node to hold the list, what I've been doing is something like this:

```
                function frBody() {
			return [
				el("em", "big"),
				el("span", "cruel"),
			];
		}
		function View() {
			return function() {
                                var result = [el("strong", "hello")];
                                var adjectives = [];
                                if (reverse) {
                                    adjectives = frBody().reverse();
                                } else {
                                    adjectives = frBody();
                                }
                                result = result.concat(adjectives);
                                result.push(el("span", "world"));
                                return el("div", result);
                         }
                  }
```

I assume that what I'm doing here is very likely more inefficient than what the new `defineFragment` does. Also, multi-level nesting quickly gets unwieldy when doing this the 'manual' way, as opposed to using `defineFragment`.

I know I do sometimes use things in ways they are not intended to be used. Is there any serious problem with doing it this naive way?

**Comment by leeoniya** [comment]
returning fragments as view roots would probably be the main use case here.

the main benefit is wrapping state and redraw isolation around some adjacent subset of dom nodes. for instance, many DOM elements cannot have arbitrary nesting levels. eg. you can't wrap anything `<div>` around some adjacent set of `td`s.

another use is defining the body as a root-fragment sub-view and the wrapper in the parent. this is quite useful to prevent wrapper duplication (or having to externalize the wrapper in a function) across multiple similar views.

you can also use fragments to store some arbitrary data/state on the fragment vnode that pertains to its children rather than copying that data to every node child.

at the end of the day it's a nice-to-have feature that isnt exactly necessary, but can make some convenient constructions less grotesque. unfortunately, fragments cannot be implemented as an addon because the core reconciler must know how to handle them. so they add a certain bytesize weight to all builds, but hopefully no perf overhead when not used (if carefully implemented).

what's available now (array flattening) is a convenience feature for declarative templates, but if you use imperative template construction (as you're showing), they don't add much value anyways cause you can just use concat()/push() to build up the body.

**Comment by grumpi** [comment]
Ok, I think I understand what this is about a bit better now. :)

This feature:
* allows to make components that don't return a node but a fragment (i.e. "list of nodes, and, recursively, other fragments").
* allows for isolated redraw on nodes that can't be wrapped in `div`s (which makes a huge difference in the huge-table-situtation)

> unfortunately, fragments cannot be implemented as an addon because the core reconciler must know how to handle them

That makes sense.

I don't see anything wrong with having them as a core feature. It does sound convenient. The only reason I'm building a few of my templates imperatively is that this is the shortest and clearest way I found so far to add multiple nodes between other nodes without introducing another `div`.

It also sounds like it's quite difficult to figure out how to make it work in an intuitive way. What I mean with intuitive is

* I would expect _hooks to work if I make a view that returns a fragment.
* That events won't work on a virtual node seems obvious to me since there is no DOM element that the events can be attached to.
* I assume that events on child nodes of a fragment work as usual.

**Comment by leeoniya** [comment]
> I would expect _hooks to work if I make a view that returns a fragment.

Well, _hooks are defined at the vnode, so the assumption with how they work should be tied to the typw of vnode you're creating. View-level hooks will work as usual (redraw, update, mount, unmount). Node-level hooks (which reflect literal dom ops) are fired by the dom reconciler which runs at the very end of the cycle (template preproc -> match new vtree to old vtree -> patch node contents -> sync dom children (reorder, remove non-recycled, hydrate & insert new)).

There's no DOM methods for operating on sets of nodes in terms of group operations. So if a fragment needs to be moved up 5 nodes, you're really performing 5x descendent operations (which will all fire their respective _hooks). Providing a "batched" level of hooks that represent these groups of ops is not simple because it requires knowledge of the needed dom ops before you actually hit the base reconcile (which operates in a single pass for speed). I added a todo item above to evaluate some _hook congruence to vnodes (look into adding hooks based on vtree grafting pass rather than dom reconciliation pass). My initial suspicion is that recycle/insert/remove hooks are doable, but reinsert (move) would be problematic since there's no "reordering strategy" prepared ahead of the actually dom reconcile pass which works incrementally.

> I assume that events on child nodes of a fragment work as usual.

yes.

**Comment by grumpi** [comment]
> hooks are defined at the vnode, so the assumption of how they work should be tied to the type of vnode you're creating. 

I totally mixed up view hooks and _hooks, sorry about that. 

Are you saying view-level hooks already work as usual with views that return fragments? That's cool. Then all I'd personally expect to happen already works.

> My initial suspicion is that recycle/insert/remove hooks are doable, but reinsert (move) would be problematic

From what I understand, one major purpose of those node-level hooks is to have a place to add animations. If I understand you correctly, it's already possible to use hooks on the individual (element) nodes of the fragment, so we can animate the DOM nodes that "belong" to a fragment individually?

Is there a strong use case for fragment-level _hooks? 

I mean, I can imagine that someone might possibly need them, in particularly, in the huge-table-situation where the workaround of using a wrapper `div` on which to use hooks for animating doesn't work for some reason. I'm just having a hard time to think of such a reason right now.

@lawrence-dol would element-level hooks have worked in your recent table use-case?

**Comment by leeoniya** [comment]
> Are you saying view-level hooks already work as usual with views that return fragments?

i'm going to backtrack on this matter-of-factly made statement. even view-level mount/unmount hooks are currently triggered as a side-effect of dom removal of a view's root node at the last reconcile phase. if the root view node is a fragment, i would have to infer & trigger its unmounting by checking whether its children would/should be removed. this is basically the exact thing that'd need to be done to get non-root fragment hooks to work in general. so i'll have to see how the implementation pans out. it may turn out that hook triggers for fragments may need an extra pass to analyze how much of the body is unrecycled and thus would be removed by the reconcile pass. i'm confident there's a solution though even if it requires a seperate code path.

> If I understand you correctly, it's already possible to use hooks on the individual (element) nodes of the fragment,

yes, but hooks have other side-effect uses besides animation. and if you have a fragment that represents some model, you may only want to fire a hook once instead of for each fragment node. of course you can kinda cheat by attaching hooks only to the first child.


i think lawrence's use case was just to isolate redraw of a couple adjacent table rows that represented a single model. if you instead assemble the tbody as a whole tpl/view you're forced to redraw the entire thing. of course you can have multiple tbody elements/views but it adds dom weight.

**Comment by grumpi** [comment]
> i would have to infer & trigger its unmounting by checking whether its children would/should be removed. this is basically the exact thing that'd need to be done to get non-root fragment hooks to work in general

Let's hope things are as straightforward as you think they are. :)

> to isolate redraw of a couple adjacent table rows that represented a single model

Ok, I see. That's where the `vm.redraw()` for fragment-returning views is going to be useful.

> you can kinda cheat by attaching hooks only to the first child

I'll keep that in mind, that sounds like a good technique for many use cases. Would that have better performance than a fragment hook?

**Comment by leeoniya** [comment]
@grumpi 

> I'll keep that in mind, that sounds like a good technique for many use cases. Would that have better performance than a fragment hook?

Fragments will have worse performance characteristics than flattened templates. In benchmarks (and extreme stress cases) it would be significantly worse but in real life apps you'll likely never notice the difference.

The reason they perform worse is that they need to be flattened & tagged [with respect to their actual physical dom parentNode] before they hit the dom reconciler which runs a simple iterator over the array of vnodes. This flattening process must happen for all vnodes that contains a fragment as a child on every redraw. There's no way around this, but again, in typical apps you probably won't be able to measure a difference unless you do something like careless like call `vm.redraw()` on unthrottled `mousemove`, `resize`, or `scroll` events.

**Comment by leeoniya** [comment]
i've written some initial tests. more will come soon. gonna close this now that this has landed in the main branch.
