### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#11]
Router will wrap HTML5 history API (pushState, replaceState, maybe hashchange). Its responsibilites:

- Listen for url changes
- Translate url to route and invoke onenter/onexit handlers, passing through any parsed/validated params and/or popped HTML5 history state.
- The user-defined route handlers then process any needed state transitions such as
    - [onexit] Suspending/saving/clearing prior state (in cache, localStorage, DOM, server, etc..)
    - [onenter] Restoring/re-fetching state
    - Maybe validating input/preventing further (or reverting) navigation?
    - All this logic can be done in the handlers or deferred to the model and/or view's APIs
- Views then redraw either implicitly or explicitly to reflect new state/model
- Router must also must provide a reverse routing API to manually invoke/set routes by name w/params and generate urls so views and templates can be wired via dom handlers and href attrs

Keeping with domvm's view creation convention (which will be changing from `domvm()` to `domvm.view()` alongside `domvm.watch()` and `domvm.route()`), the proposed API is:

```js
function AppRouter(rt, app) {
	return {
		root: "/threaditjs/examples/domvm/",
		routes: {
			threadList: {
				url: "",
				onenter: function() {
					app.getThreads();
				}
				onexit: function(e) {
					app.threads = [];
				}
			},
			thread: {
				url: "thread/:id",
				params: {id: /[a-z0-9]{5}/i},			// TODO: fn validation
				onenter: function(id) {
					app.getComments(id);
				},
				onexit: function(e) {
					app.comments = [];
				}
			},
			_404: {

			}
		}
	}
}

function AppView(vm, app, key, impCtx) {
	return function() {
		var href = impCtx.appRt.href("thread", ["some_thread_id"]);
		return ["a", {href: href}, "View Comments"];
	};
}

// state/model
var app = new App();

var appRt = domvm.route(AppRouter, app);
var impCtx = {appRt: appRt};
var appVm = domvm.view(AppView, app, null, impCtx);

appRt.goto("threadList");
```

As with views, app is just a model to be manipulated/rendered by the router and the views. The router is passed into the view in an imported context alongside the main model (app).

Most of this is functionally near-ready for alpha.

@lawrence-dol thoughts?

**Comment by leeoniya** [comment]
A thing think about is, what comes first? the view or the router?

In the above example, the router is dependency-injected into the view so the view can generate hrefs via the reverse routing api, so the router is created first.

But you also need access in the opposite direction as well *during the init* of both, then it can't be done cleanly. If the `onenter` and `onexit` handlers need to invoke the view's API directly rather than through app, then you can simply inject a the view afterwards so everything is dep-injected post-init.

```js
var impCtx = {app: app, appRt: null, appVm: null};

var appRt = domvm.route(AppRouter, impCtx);
var appVm = domvm.view(AppView, app, null, impCtx);

impCtx.appRt = appRt;
impCtx.appVm = appVm;
```

The fundamental problem of both being available to each other during init is not technically possible. This is something that would be common to any implementation, coupled or decoupled. I cannot think of a situation when this would cause issues in real life. The more useful thing to do is init the router first to provide the link generator to any views and the when the route handlers fire, the view will already be available for direct use.

**Comment by lawrence-dol** [comment]
At a high level this looks good to me (but please, please, please, be aware that I am not actively using domvm yet, and it's in the use that the API snarls always come out). Certainly, it looks clear as to what the router is doing and what will be invoked when. 

I very much like the optional validation of the parameter; will that factor into the route selection, or cause an error? That is could I have two routes, one with `thread/123` and the other with `thread/abc`, or would that be dealt with in a single route that did different things? I expect the latter.

I dislike the `_404` name. I assume that's a special "not found" value. However, it assumes and infers a 404 response. I'd prefer something special that expresses the condition, not the response, like, say, @NoMatch or _NoMatch. I might not be understanding the purpose.

I don't see what `rt` is representing.

I find injecting the router into the view strange; I expect the router to define the views it will use for each route. Again, maybe because I am not seeing the bigger picture.

**Comment by leeoniya** [comment]
@lawrence-dol 

> I dislike the `_404` name. I assume that's a special "not found" value.

Point is well taken, since for client-side routing 404 is non-sensical without http response. `_noMatch` would be clearer.

> I don't see what `rt` is representing.

Similar to views: 

`AppView` is the view constructor/viewState closure
`appVm` === `vm` and is the materialized view w/API (view instance, ViewModel, whatever you wanna call it)

`AppRouter` is the router constructor/routeState closure
`appRt` === `rt` and is the materialized router w/API (router instance)

I just named them differently internally vs externally cause internally, `vm` is obviously your own vm whereas externally `vm` is too generic/ambiguous, so I call it `appVm` in the external context, but the two are exactly the same object.

> I find injecting the router into the view strange; I expect the router to define the views it will use for each route. Again, maybe because I am not seeing the bigger picture.

There are a bunch of ways to structure things. Consider that there can be multiple, disjoint views in the UI which can be affected by a route change. It is up to the handler to determine from the provided route, params and prior state how and what to update. You could update the app and by proxy (via observers), the views can redraw. Or you can update the views straight from the handler. I wanted to leave the option open and not fixate the handlers to be bound to one monolithic view.

You could of course make a handler creator that would allow you to bind one route to one view.

**Comment by leeoniya** [comment]
I expect varying "patterns" to be developed on top of domvm, because it *is* so decoupled. You could:

- Have your views be your entire models/components since they can enclose state and expose an api. This is kind of like React, but better because they can be composed declaratively or imperatively and have an API for external usage.
- Have your views just be dumb template renderers for passed-in data and have your models be completely disjoint.
- Have your models wrap your views and expose a single API that controls both.
- Stuff I haven't thought of yet.

It easy to create a "framework" around domvm by simply creating thin wrappers that adhere to your own conventions. But when your wrappers turn out to be too simplistic, then you have the full power of the core and can adapt your framework to expose more of that power.

**Comment by leeoniya** [comment]
> I find injecting the router into the view strange

sorry, i dont think i answered this directly. the only reason the view needs the router in this example is because the view template uses the router's api to generate href links and implicit onclick handlers for the template.

else you have to write a bunch of boilerplate to handle `e.preventDefault()` from link clicks and handling url changes and your views would need to become url-structure-aware - which should be the router's domain. so the router serves to separate and dep-inject those concerns into the views.

the router is purely an SPA concept, it is not at all needed to create widgets for normal websites where all url nav is handled normally by server and client.

hope that helps

**Comment by yosbelms** [comment]
The router API is clear but could be simplified regarding consistency. domvm special properties are prefixed with `_`, hence the `root` could be prefixed too.

Currently:
```js
function AppRouter(rt, app) {
    return {
        root: "/threaditjs/examples/domvm/",
        routes: {
            _noMatch: { },            
            threadList: {
                url: ""
            },

            ...
        }
    }
}
```

With my proposal:
```js
function AppRouter(rt, app) {
    return {
        _root: "/threaditjs/examples/domvm/",
        _noMatch: { }
        threadList: {
            url: "",
            onenter: function() {
                app.getThreads();
            }
        },
        
        ...        
    }
}
```

It is consistent with the rest of the API and the routers tree is flattened.

**Comment by leeoniya** [comment]
@yosbelms not sure that i agree.

i would rather not intermix settings and routes for the sake of flatness.

> domvm special properties are prefixed with `_`

yes, but only when it's necessary/useful to intermix them for terseness, such as the props object in template nodes. accounting for them in all loops and doing prefix checks adds perf overhead and code complexity.

`_noMatch` is an actual [special-case] route, whereas `root` is a prefix to all defined routes. there will undoubtedly be additional config params in the future, and i don't believe flattening one layer and intermixing everything is beneficial.

thanks for your input, though!

i have node-level lifecycle hooks coming up in the next couple days and a demo for using them for animating ioninsert/onremove/onreuse/etc..

**Comment by yosbelms** [comment]
@leeoniya 
> accounting for them in all loops and doing prefix checks adds perf overhead and code complexity.

I don't think so because prefixed properties are predictables, see the following snipet:
```js
function processRoutes(routes) {
    var
    route,
    root    = routes._root,
    noMatch = routes._noMatch;

    routes._root = routes._noMatch = void 0;

    // alternative:
    // delete routes._root; delete routes._noMatch;

    for (route in routes) {
        ...
    }
}
```

>  there will undoubtedly be additional config params in the future

I hope no many more. Please don't bloat it.

BTW, I'm really interested in this project, so I have taken the GitHub organization (https://github.com/domvm), npm package (https://www.npmjs.com/package/domvm) and the Bower package, all three ready to transfer the ownership to you, whenever you want.

**Comment by leeoniya** [comment]
@yosbelms

> I don't think so because prefixed properties are predictable, see the following snippet:

Sorry, I prefer:

```js
for (var name in cfg.routes) {
	...
}
// and
cfg.root
```

Also, pretty sure `delete` is a de-opt in v8 and can make things slow besides being wordy. For custom node props, I set them to `null` [1]. Again, I don't want to flatten routes with other config params. `root` is not a route, it's a prefix and only improves a tiny a bit over just concatenating a prefix stored in some var to all urls yourself. In addition to `root`, you need an actual `""` or `"/"` route. `_` was a compromise for template nodes to improve readability since you will have many of them but you'll only ever have one or very few routers.

> I hope no many more. Please don't bloat it.

Bloat is not explicitly **un**planned.

> BTW, I'm really interested in this project, so I have taken the GitHub organization (https://github.com/domvm), npm package (https://www.npmjs.com/package/domvm) and the Bower package, all three ready to transfer the ownership to you, whenever you want.

Thanks. If you'd like to help out with UMD packaging, that'd be even more helpful: #5

[1] https://github.com/leeoniya/domvm/blob/master/src/view.js#L823

**Comment by leeoniya** [comment]
it's possible the flattening may actually happen differently and similar to what i did with views.

the router constructor will just return the essential flat object of routes like the view constructor returns the essential render func.

the rest of the config will be done via a secondary call to rt.config() or rt.setPrefix(), etc. either externally or internally.

the router is new, so the api is not yet stable.

**Comment by leeoniya** [comment]
as of https://github.com/leeoniya/domvm/commit/1bc1e32b1850a2f9431b6f85a315cfe669c657ff the router fn must simply return a flat route list. `root` is gone as it's trivial to concat it yourself in the closure. `_noMatch` should be returned in the list as a normal route.

**Comment by lawrence-dol** [comment]
For my two cents, I think I'd prefer `_noMatch` to be at the same level as routes and without the leading `_`.

    function AppRouter(rt, app) {
        return {
            root: "/threaditjs/examples/domvm/",
            routes: {
                threadList: {
                    url: ""
                ...
                },
            routeNotFound: { 
                },            
            }
        }
    }

**Comment by leeoniya** [comment]
probably not. it gets special treatment by the router in a hash that's otherwise fully free-worm. like specially-treated `props` in tpl nodes which are otherwise fully user-defined. i'll probably keep the `_` for uniformity here.

**Comment by yosbelms** [comment]
+1

**Comment by leeoniya** [comment]
FYI, `url` has been changed to `path`

**Comment by leeoniya** [comment]
So it turns out my original instinct to entirely abandon hash routes for the history API (polyfilled as needed) was a bit off. I came to this realization during the threaditjs implementation https://github.com/leeoniya/domvm/issues/24.

There are two related points that the history API cannot really address.


The first is that the server's request router needs to be involved in accommodating a history-based design. Let's take the threaditjs example.

1. Accessing `/` on initial request loads `index.html` from the server which then attaches to `window.onpopstate` and uses `pushState` and `replaceState` to manage the rest of the nav.
2. User navs to `/threads/xyz` and is shown that thread.
3. User decides to use `F5` to refresh the page.
4. Browser will now ask the server for `/threads/xyz`. Oops!

So the server needs to know to always load `index.html` whenever a request comes into any route prefixed by wherever your SPA lives. If it's a domain, then you could configure this in nginx/apache/node or in some front-controller script where everything lands. This is okay for SPAs most of the time, but for a threaditjs demo which runs on gh-pages, i have no control over the routing, so I cannot run the SPA and have the history-pushed routes be accessible if the user refreshes the browser.

The second issue is also related to this. What if I just have a widget like a gallery/slider and want to be able to navigate between slides using browser's back/forward? We no longer need the router for an SPA but for on-page widget navigation without having to hook up complex server-side routing support for it.

Hashes actually solve both of these issues very nicely. They allow your app to be runnable from any directory or domain without having to touch the server's router since you will always load the same file from the server with different hashes for the SPA router: `index.html#/some/long/route`. This accommodates in-page widget navigation the same way, the page is accessible normally from the server and the hash loads up the widget state.

I don't currently see a good way to accomplish these two very standard tasks in a good way with the history API.

That being said, the current API and approach will not be changing - it works well if you're willing to config your server's routing to support these cases. However, I'm evaluating using hashes not just as a fallback/polyfill mechanism but as an actual explicit routing mode. The api will remain the same and I already have some additions needed to support this that currently break because I now have to maintain my own state stack to replace history's state, I dunno yet if localstorage will be needed for this but I suspect "yes" because a page refresh will blow away anything stored in the DOM/window.

**Comment by leeoniya** [comment]
maybe combing them would work best [1] and we can get the best of both worlds without rolling our own state stack in localstorage or having to touch the backend router.

https://lea.verou.me/2011/05/change-url-hash-without-page-jump/

**Comment by graydixon** [comment]
I've recently been working on a routing system that I've used to replace backbones' router in one of my works projects. Its not exactly succinct, but I like how the browser behaves at reload and unload... I'll try explain it as best I can - and if you want to see an example, I can email you a link to it - but I'm not too keen on sharing it publicly (because its not really relevant)...

The crux of my thinking is that whenever a route is fired which matches one of your applications routes;
- you capture WHERE it should be loaded (which element)
- add the instruction to an object
- encode that object
- replace the hash with this encoded string making sure you don't fire a hash change twice

This essentially destroys the use of the address bar for manual navigation/recognising what page your on because your filling it with nonsense, and I know that there will be limitations because of how long the string can be in certain browsers, however - you do end up with a page where every element can be affected by entering a new # state. Allowing for complex pages to built that can react to the users every whim, completely changing every element on the page - if thats whats required. As well as allowing for normal history navigation.

My implementation is for a widget/grid environment where the user can control the number and layout of cells, they can load any route into any cell of the grid and then share or load any encoded string back into the page... which will rebuild the grid and call every route for the appropriate element/cell. 

So, for your domvm router, I think it would be really helpful [for me at least] if you could define a route at component level, and have domvm handle all the monotony of managing/rebuilding the hash state for you.

I'd love to do a PR for this, if your welcoming of the suggestion, but if it doesn't fit with your goals then I'd totally understand.

**Comment by lawrence-dol** [comment]
The purpose of the `#` is to separate the "in app" path from the page containing the app. Plain an simple. What follows the `#` should designate a specific location in your app, be able to be bookmarked to return then and in all other ways function logically like an internet URL. 

Please implement as such. And other conditions of state, like sort column, ascending/descending and other things that are not relevant to the user getting to that part of the app should be in local-storage. If they belong with the URL because somehow sending them to another user matters, they belong as part of the query data, which the app should be able to see and use. The operation of the hash-location should be very RESTful.

**Comment by graydixon** [comment]
Agreed, what I'm essentially describing is a dynamic situation where the application only knows what to display because of the instructions inside the #.

Take the threaditjs example, the page is really simple, and only shows the one thread (eg /thread/5jb4Lk). If the page was more complex - and had the ability to show n number of thread components rather than one (say for example - a list of user selected threads), then the URL # of thread/5jb4Lk wouldn't be instructive enough to load the hash into the correct element on page. What I'm basically wanting is the ability to have an undefined number of components and have each one be controllable by its own route map. The applications route map would be intuitive enough to be able to address multiple components in a single #.

**Comment by leeoniya** [comment]
@graydixon thanks for the suggestion,

> Allowing for complex pages to built that can react to the users every whim, completely changing every element on the page - if thats whats required. As well as allowing for normal history navigation.

What you're talking about is what i've always referred to as "route multiplexing". i could have sworn i mentioned this idea in this issue, but i guess not. the idea is to somehow encode the state of all components into the url so that literally any combination of states can have a url. This can be accomplished a bunch of ways such as json/base64 encode a flat/keyed component:state map etc. Rather than having completely unreadable URLs, you'd be better off storing the state in json/localstorage, generating a key and loading up `#?state=sha2Key` or something...

There are a couple reasons I don't want to do this. First is that it's an opinionated can of worms and is already very easy to implement over the current router anyways. Being decoupled, domvm doesnt have a concept of route <-> component <-> element binding. The only thing the router does is parse or push the url, extract any parameters and pass it to `onEnter/onExit` callbacks of matching routes you have predefined. Any state saving/restoring in your app is entirely up to you and there are a million ways you may want to do it. Doing any more than the "essence of routing" either couples the router the rest of domvm or creates opinions that then need to handle all the cases which had not been accounted for.

The goal of the core router is to provide a declarative route map with callbacks that handles the address bar (hash and history) and firing route callbacks with parsed (or invoked) route params.

@lawrence-dol

> And other conditions of state, like sort column, ascending/descending and other things that are not relevant to the user getting to that part of the app should be in local-storage.

This is one view of it. But really, REST is whatever the user decides it needs to be. If some elements of state don't matter and can be reset when a user navigates to the URL, then t doesn't fall under REST, otherwise it does. Whether you pass it as query params or in the path or in cookies, it's all the same and arguing over how each part needs to be passed is pointless - do whatever you feel is correct. That being said, i personally agree with your categorization.

**Comment by leeoniya** [comment]
@lawrence-dol 

Current route definition:

```js
thread: {
	path: "/thread/:id/:foo",
	params: {id: /[a-zA-Z0-9]{5,7}/},
	onenter: function(e, id, foo) {
		...
	},
	onexit: function(e, id, foo) {
	},
},
```

Right now, the router only handles paths and not querystrings or hashes. It extracts segments from the path, validates via regex and passes them through to the callbacks as arguments following the `e` routing event.

In reality, it should handle all parts of a URI. The question is, what should the definition look like and should all parts be explicitly split or can we merge segment names and querystring keys into a single `params` validator? And how should these parsed values be passed through to the callbacks? How should the href generator change to accommodate building urls that include all these parts? How should hash routing mode work?

Here's an initial idea.

Keep a single `params` and require that keys be unique between segs and query but pass each set separately to the callback. This will play nice with `href` generation by explicitly specifying different semantic parts.

"/thread/abc123/blah?sortBy=date&sortOrd=asc"

```js
thread: {
	path: "/thread/:id/:foo",
	params: {id: /[a-zA-Z0-9]{5,7}/, sortOrd: /asc|desc/},
	onenter: function(e, segs, query, hash) {
		...
	},
},
```

I don't think inter-op between `hash` and `history` routing will be an easy thing to engineer without ambiguity. So the plan is to have two distinct modes. And their operation will only differ in where the parser grabs the full URI from. In `hash` mode it will grab it from `window.location.hash` and in `history` mode it will grab `window.location.href`, strip the scheme & domain and parse out the rest of the parts.

It should be easy to toggle between one and the other, since even hashes can have their own hashes parsed out: `/foo/#/bar?baz=123#blah`.

**Comment by leeoniya** [comment]
to polyfill `e.state` in browsers that are missing `history` or using hash, this looks like it would do the trick, just uses `window`:

https://gist.github.com/juliocesar/926500#gistcomment-1620487

```js
// fix issue where localStorage or sessionStorage are not available , example  : incognito Mode
try
{
	 window.sessionStorage.setItem('testKey', '1');
	 window.sessionStorage.removeItem('testKey');
}
catch (error)
{
	 window.sessionStorage = {
		_data       : {},
		setItem     : function(id, val) { return this._data[id] = String(val); },
		getItem     : function(id) { return this._data.hasOwnProperty(id) ? this._data[id] : undefined; },
		removeItem  : function(id) { return delete this._data[id]; },
		clear       : function() { return this._data = {}; }
	  };
}
```

**Comment by leeoniya** [comment]
the primary router changes are now done. everything else will be considered enhancements, improvements or bugs.
