### ISSUE TITLE
[perf] on-demand vnode reuse

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#111]
domvm v2 is already fast [1], but i think it can get even faster if people are willing to write their templates a bit differently. this can be done in a backwards-compatible manner by adding an extra signature to the vnode factory functions.

Current signature:

```js
var el = domvm.defineElement,
    vw = domvm.defineView;

function View(vm, data) {
  return () =>
    el("div", [
      el("em", "foo"),
      vw(ItemsView, data.items),
    ])
}
```

Body-generator signature:

```js
var el = domvm.defineElement,
    vw = domvm.defineView;

function View(vm, data) {
  return () =>
    el("div", d => [
      d.el("em", "foo"),
      d.vw(ItemsView, data.items),
    ])
}
```

Here's the idea:

Currently, the new vtree must be generated in full before being returned from `render`. This means all vnodes must be pre-allocated and after the oldVtree/newVtree diff pass, the old vtree is fully discarded by the GC - which takes time. By returning a body-generating function, we allow things to be lazy and pass in a "donator" `d`. What `d`'s methods do is a combination of `findDonor` and `patch`, where each vnode is located and re-used on demand from the oldVtree parent. As a result, we shorten the lifetime of any temporary vnodes and let the GC work more efficiently and allocate less stuff.

The syntax difference is small and clean when using ES6, so the templates stay concise (though the compiled ES5 versions would replace `d =>` with `function(d) {...}` and be beefier).

this is speculation at this point, but i think it may work.

[1] https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html

**Comment by thysultan** [comment]
This could work well with something like `shouldComponentUpdate` on components that have more than a few children.

**Comment by leeoniya** [comment]
i think immutability is the way to go for any kind of complex sCU.

domvm's current sCU implementation is called `diff`, which can return an array or hashmap of values to diff between redraws. if the values all match then redraw is short-circuited.

I have a demo coming using https://github.com/arqex/freezer and `diff` to do this redraw optimization, similar to https://github.com/kolodny/immutability-helper. Essentially it just emits views with a pre-defined `diff = function(vm, state) { return [state] }`. I'll prolly push it today or tomorrow.

this was the purpose of the latest commit ;)

**Comment by leeoniya** [comment]
this turned out to be impractical and not worth it.

the way in which internal passes are optimized makes implementing this quite ugly and using it quite ugly as well.

**Comment by leeoniya** [comment]
welp, i decided to circle back to this. as newer fast libs are able to run <= 8.5MB mem, there's no reason why domvm must use 10.2MB [1]. the recent spike in mem usage was a result of switching the impl to sub-views since they are currently the only method for diffing & short-circuiting for 0 changes (sCU).

rather than trying to make an overly-generic `vnode.diff` construct, i'll try to focus on the most common case that can benefit from such optimizations: lists. hopefully this isn't seen as just an attempt to cater to benchmarks that artificially manufacture giant lists. @lawrence-dol can likely utilize this already for large grids.

the idea, as before, is to create a deferred iterator that can diff and reuse old body vnodes. for the public API, this is the best that i've come up with so far:

```js
var li = domvm.list;

function View() {
    return (vm, data) => {
        var items = li(data, {
            key:  item => item.id,
            diff: item => [store.selected === item.id, item.text],
        });

        return el("#app", {_flags: domvm.KEYED_LIST}, items.map(item =>
            el("p", {class: store.selected === item.id ? 'selected' : null}, [
                el("em", item.text),
            ])
        ));
    }
}
```

[1] https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html

**Comment by leeoniya** [comment]
this will be in v3
