### ISSUE TITLE
reconciler bug with diff() & keyed sub-views

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#113]
https://gist.github.com/leeoniya/82558c8a3861d715bf451017f0ab746f

**Comment by iamjohnlong** [comment]
this doesn't freeze the browser but the last two changes to the state doesn't update the dom.

https://jsfiddle.net/iamjohnlong/3kcgns6g/

If you comment out the diff it works as expected

**Comment by leeoniya** [comment]
the problem was a dumb oversight early in the diff short-circuit [1] that confused the reconciler later. should work as expected now. thanks for reporting.

[1] https://github.com/leeoniya/domvm/commit/861073375c88db90e34d9271323789e19133c724#diff-623c25c223969bc3a1e61ad61cb93341R243

**Comment by iamjohnlong** [comment]
sweet thx!
