### ISSUE TITLE
parameterized hooks?

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#115]
#114 got me thinking a bit.

how useful would it be to introduce parameterized hooks, similar to parameterized event handlers?

current events:
```js
el("button", {onclick: [someFn, "a", "b"]}, "Press me!");
```

possible hooks:
```js
el("select", {_hooks: {willInsert: [setInitialVal, "two"]}}, [...]);
```

it has the benefit of defining the hooks inline with the template without function re-creation on each redraw as would happen with inline `setInitialVal.bind(null, "two")`. it's important for event handlers since they need to be actually bound/unbound in the DOM, but may not be worth the internal weight/complexity for hooks.

**Comment by iamjohnlong** [comment]
I might use this feature..

> but may not be worth the internal weight/complexity for hooks.

I agree with that statement.

Is there anyway of getting JSX to work with the templates?

**Comment by leeoniya** [comment]
> Is there anyway of getting JSX to work with the templates?

i'm not familiar with what would be involved in writing the necessary adapter & introducing additional tooling/dependencies & tests to ensure all of domvm's template features can be represented properly in JSX.

speaking as someone who dislikes JSX and the baggage it must bring with it, i dont have an interest in working on this. however, if someone wanted to create and maintain a thoroughly-tested, high quality `domvm-jsx` repo, i would be more than happy to explain any domvm nuances to the implementer and link to it from the README for those interested.

**Comment by iamjohnlong** [comment]
I'm not a fan either, but it my company people are wanting to move to React. Seemingly because of JSX and the thinking that it will be easier for devs to grok. I disagree and I want to make a case for using domvm but I'm at a disadvantage with no JSX support.  I'll look into adapter, thanks Leon

**Comment by lawrence-dol** [comment]
> Is there anyway of getting JSX to work with the templates?

I absolutely detest JSX, so if anything is done, please let it be (a) entirely optional, and (b) as a preprocessing step so that no-one else has to carry the weight.

IOW, I agree whole-heartedly with @leeoniya.

People who want JSX have, in my (limited) experience failed to comprehend and experience the power of Turing-complete templating done well. Which both Mithril and DOMVM have done.

**Comment by leeoniya** [comment]
> Seemingly because of JSX and the thinking that it will be easier for devs to grok.

this simplicity is skin-deep. imo devs for whom JSX is significantly easier than hyperscript will end up struggling with the more difficult concepts in JS which immediately follow anything beyond a static Hello World.

at the end of the day, domvm is a view layer for JS devs; neither domvm nor React is a good place to start learning it by adding a ton of tooling and blurring the line between where actual JS starts and HTML-ism ends.

**Comment by iamjohnlong** [comment]
I agree with you both :)

I'll point them here so they can be enlightened.

**Comment by leeoniya** [comment]
there was a recent discussion about people's preferences with Mithril, too: https://github.com/lhorie/mithril.js/issues/1619

**Comment by leeoniya** [comment]
nah, no need for more codebase growth
