### ISSUE TITLE
Porting V1 to V2

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#116]
This issue is intended to record my experience of porting a complex DOMVM app (with no routing) from V1 to V2. Comments will have two types, requests for help, and notes for what I've needed to do.

When I am done porting, I'll close the issue, but it should then serve as a reference for others.

**Comment by lawrence-dol** [comment]
My app already uses hyperscript-like function wrappers for components and elements, so for those I just need to point them at the DOMVM `defineView` and `defineElement`, resp.

As well I have a separate `prop` function and had already externalized DOMVM V1's AJAX support into a separate module, so I have no changes relating to props or AJAX, provided the view processing executes functions when they are encountered for attribute values.

**Comment by lawrence-dol** [comment]
Dropped explicit config, which was only forcing debouncing off, since my app already debounces to the UI thread (making RAF superfluous):

    domvm.view.config({
        debounce        : false,
        });

**Comment by leeoniya** [comment]
mini+ builds do expose a simplistic `domvm.prop()` that can fire a callback on mutation and can prevent the callback from firing during prop setting by passing `false` as the second arg. [1]

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/utils.js#L129

**Comment by lawrence-dol** [comment]
Port my view extensions for debounced redraws to use the view prototype, changing the enclosing extension function to be a self-executing function to contain the state:

    domvm.view.extend(function(vm) {
        let domWrap     =(typeof(DomOpWrapper)===typeof(Function) ? new DomOpWrapper() : null);     // Include DomOpWrapper in script to instrument DOM operations
        let redrawEvt   =false;                                                                     // coalescing redraws
    
        // Used directly as a property mutation processor; must have no args and return undefined.
        // Use `redrawEft` to signal that the model has changed and the view needs to be accordingly
        // updated to match. This debounces multiple redraws due to a single event and should be the
        // "normal" redraw employed.
        vm.redrawEvt=function() {
            if(!redrawRaf && !redrawEvt) {
                redrawEvt=true;
                setTimeout(function() {
                    redrawEvt=false;
                    if(domWrap) { domWrap.start(); vm.redraw(); console.log(domWrap.end()); }
                    else        {                  vm.redraw();                             }
                    },0);
                }
            };
        ...
        });

becomes:

    (function redrawStateClosure() {
        let domWrap     =(typeof(DomOpWrapper)===typeof(Function) ? new DomOpWrapper() : null);     // Include DomOpWrapper in script to instrument DOM operations
        let redrawEvt   =false;                                                                     // coalescing redraws
        let redrawRaf   =false;                                                                     // coalescing RAF redraws

        // Used directly as a property mutation processor; must have no args and return undefined.
        // Use this to signal that the model has changed and the view needs to be accordingly
        // updated to match. This debounces multiple redraws due to a single event and should be the
        // "normal" redraw employed.
        domvm.ViewModel.prototype.redrawEvt=function() {
            let vm=this;
            if(!redrawRaf && !redrawEvt) {
                redrawEvt=true;
                setTimeout(function() {
                    redrawEvt=false;
                    if(domWrap) { domWrap.start(); }
                    vm.redraw();
                    if(domWrap) { console.log(domWrap.end()); }
                    },0);
                }
            };
        ...    
        })();

**Comment by lawrence-dol** [comment]
Change `domvm.view` to `domvm.createView`.

**Comment by lawrence-dol** [comment]
@leeoniya 

Apologies if this has already been covered in another issue.

Having ported my two redraw extensions to V2, as above, I was expecting that `this` would naturally then be the vm. Am I mistaken; I am getting errors that it's undefined. But it's certainly not the first argument, as with V1. I'm not seeing how to use extensions. It seems like it may be the second argument, but it's very sparse until a number of redraws have happened.


I see `this` changing as follows:

    16:01:49.016 [**] redraw this: undefined  AppScript:414:366
    16:01:49.019 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined }  AppScript:414:366
    16:01:49.025 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined }  AppScript:414:366
    16:01:49.027 [**] redraw this: undefined AppScript:414:366
    16:01:49.037 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined }  AppScript:414:366
    16:01:49.384 TypeError: a is undefined[Learn More]  AppScript:151:164
    16:01:49.403 [**] redraw this: undefined AppScript:414:366
    16:01:49.405 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined, events: Object, render: AppView/<(), _redrawAsync: V/<(), _updateAsync: V/<(), node: Object, 1 more… }  AppScript:414:366
    16:01:49.413 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined, events: Object, render: AppView/<(), _redrawAsync: V/<(), _updateAsync: V/<(), node: Object, 1 more… }  AppScript:414:366
    16:01:49.417 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined, events: Object, render: AppView/<(), _redrawAsync: V/<(), _updateAsync: V/<(), node: Object, 1 more… }  AppScript:414:366
    16:01:49.419 [**] redraw this: undefined AppScript:414:366
    16:01:49.421 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined, events: Object, render: AppView/<(), _redrawAsync: V/<(), _updateAsync: V/<(), node: Object, 1 more… }  AppScript:414:366
    16:01:49.422 [**] redraw this: Object { api: Object, id: 0, view: AppView(), model: undefined, key: undefined, events: Object, render: AppView/<(), _redrawAsync: V/<(), _updateAsync: V/<(), node: Object, 1 more… }  AppScript:414:366

**Comment by leeoniya** [comment]
unable to reproduce: https://jsfiddle.net/nfLm4m2f/

**Comment by lawrence-dol** [comment]
@leeoniya : N/mind. Was brain-farting on the invocation context; went for a walk and realized the problem within minutes.

**Comment by lawrence-dol** [comment]
@leeoniya : What's the relationship between `createView`, `defineView` and `injectView`? Which one corresponds to V1's `domvm.view`? I assume `createView` does.

**Comment by leeoniya** [comment]
right.

you'd use `injectView(vm)` where you would provide an existing vm directly as a child, `defineView` is the declarative in-template view definition, `createView` is the vm factory that corresponds to the old `domvm.view`

**Comment by lawrence-dol** [comment]
@leeoniya : Then, I suppose, I would use `injectView` for a view previously created by `createView` and use `defineView` for a view where I wanted DOMVM to invoke the object's view function to create an instance as needed it as needed?

**Comment by leeoniya** [comment]
correct

**Comment by lawrence-dol** [comment]
### Be sure to look for single-element bodies.

I was bitten a number of times by failing to notice some elements which had a single element for their body, and not wrapping the body element in an array.

For example:

    vElm("div.grid.layout-grid", vElm("div.row", [
        ...
        ])

which needs to become:

    vElm("div.grid.layout-grid", [ vElm("div.row", [
        ...
        ]])

Otherwise it emits `[object Object]`.

**Comment by lawrence-dol** [comment]
### Attributes with "prop" Values

Had to locate any attributes which were using property getter/setter functions and change them to invoke the function. E.g:

    el("input", { value: someProp });

becomes:

    el("input", { value: someProp() });

**Comment by lawrence-dol** [comment]
### Attributes with "prop" Values

Had to locate any attributes which were using property getter/setter functions and change them to invoke the function. E.g:

    el("input", { value: someProp });

becomes:

    el("input", { value: someProp() });

**Comment by lawrence-dol** [comment]
### Don't Overwrite the Bootstrapping Script

The only problem that took significant time was a curiosity that resulted from the way I'd constructed my HTML bootstrapping code, which worked without error in V1, but resulted in weird errors within DOMVM relating to v-node properties not being defined.

The problem turned out to be that I was overwriting the element that contained the bootstrapping code like this:

    <body>
        <div id="jse">
            <p id="placeholder" style="margin:1em; text-align:center;">This application requires JavaScript.<br><br>If you have JavaScript enabled, please contact Technical Support.</p>

            <script>
            let update=function(htm,tmo) {
                setTimeout(function() { let elm=document.getElementById("placeholder"); if(elm) { elm.innerHTML=tmo; } },tmo);
                }
            update("",0);
            update("Task is still loading...<br><br>Please wait."                                                         , 5000);
            update("Task is still loading...<br><br>Sense of impending doom."                                             ,10000);
            update("Hmmm, this is inauspicious...<br><br>Something must have gone awry, please contact Technical Support.",15000);
            </script>

            <script src="AppScript"></script>

            <script>
            new JSE({
                // config here
                });
            </script>
        </div>
    </body>

I had to move the scripts out of the `<div>`, like this:

    <body>
        <div id="jse">
            <p id="placeholder" style="margin:1em; text-align:center;">This application requires JavaScript.<br><br>If you have JavaScript enabled, please contact Technical Support.</p>
        </div>

        <script>
        let update=function(htm,tmo) {
            setTimeout(function() { let elm=document.getElementById("placeholder"); if(elm) { elm.innerHTML=tmo; } },tmo);
            }
        update("",0);
        update("Task is still loading...<br><br>Please wait."                                                         , 5000);
        update("Task is still loading...<br><br>Sense of impending doom."                                             ,10000);
        update("Hmmm, this is inauspicious...<br><br>Something must have gone awry, please contact Technical Support.",15000);
        </script>

        <script src="AppScript"></script>

        <script>
        new JSE({
            // config here
            });
        </script>
    </body>

**Comment by lawrence-dol** [comment]
And with that, my porting adventure to DOMVM V2 is complete.

My assessment of the task, apart from the gnarly HTML script issue, is that it was routine, even for a fairly complex special-case app with a number of out-of-the-ordinary requirements.

**Comment by leeoniya** [comment]
good to hear 👍
and now we await the before/after benchmarks 😉

**Comment by leeoniya** [comment]
@lawrence-dol have you felt any perf improvement since switching to v2?

**Comment by lawrence-dol** [comment]
@leeoniya : Unfortunately I could see no visible difference, which has led me to instrument the various code sections and see where the time is going. 

The total time required to build my approx 2000 element view is 90 +/- 15 ms, of which only 20 seconds is DOMVM; the rest is building the vDOM structure in my code.

I have a 100 ms block of time unaccounted for.

I have found out that I can skip building an intermediate structure, which only takes 4 ms anyway, so caching that is saving virtually nothing and makes the code more complex.

**Comment by leeoniya** [comment]
hmm, v2 is very significantly faster than v1, so perhaps the bottleneck is elsewhere. from the timings, the app overall looks to be running fadt enough.

**Comment by lawrence-dol** [comment]
> app overall looks to be running fast enough

Each set like the one above represents an interaction with the host. The first block is irrelevant, waiting for the user to submit data to the host. The subsequent ones are the time required for the submission, response and creation of a new page. The first redraw will happen concurrently with comms (my testing is using recorded data to bypass coms) so it doesn't matter. But the next two totaling 141 ms are crucial.

Unfortunately I am replacing a Java applet, which does the equivalent work in a staggering 2 ms (though that is using my custom GUI toolkit which is designed to be remarkably efficient). Even so, I need to get this number down to 50 ms if that's achievable.

**Comment by leeoniya** [comment]
if domvm time is really only 20ms / 141ms, i'm not sure what i can do do help much.

rather than instrumenting different functions, it would be much better to use chrome's profiler and see which functions are actually consuming the bulk of the resources. you should record the time between interactions and inspect the timeline. i think a lot more can be learned from this and whether domvm plays a significant role in the slowness. if you saw no difference between v1 and v2, i have a strong feeling the issue lies elsewhere, simply because the speed difference between v1 and v2 is huge.

**Comment by lawrence-dol** [comment]
> i'm not sure what i can do do help much

I agree. Just filling you in on some of the details. Though it's 40 ms since the final total of the last block is when DOMVM invokes `didRedraw`. Still, that's not huge.

> it would be much better to use chrome's profiler

Yep. Though it seems like my next priority might be comms.

**Comment by leeoniya** [comment]
another statistic is that a naive/unoptimized dbmonster 0% mutation redraw, which regenerates 2900 vnodes and re-syncs/diffs the full dom takes 1.30ms on my avg spec laptop. so the framework overhead is practically non-existent. anything more than that is simply the nature of the browser's DOM ops & repaint/reflow, which you would incure anyhow with optimal vanillajs.

[1] https://cdn.rawgit.com/leeoniya/domvm/2.x-dev/demos/bench/dbmonster/index.html

**Comment by lawrence-dol** [comment]
You comment made me think, my testing is in Firefox. Chrome's JS engine is significantly faster than FF. So I tested it in there, and the difference is now dramatic. Noticeably a marked improvement over V1.

`````
Performance Results:
  - Start Waiting .................................... :         967.000 ms 
  - Total ............................................ :         967.000 ms 
Performance Results:
  - Start Submit ..................................... :           0.000 ms 
  - Submit - Done .................................... :           1.000 ms 
  - Total ............................................ :           1.000 ms 
Performance Results:
  - Start Redraw ..................................... :           1.995 ms 
  - App View ......................................... :           0.000 ms 
  - App View - Done .................................. :           0.000 ms 
  - DisplayPanel Redraw .............................. :           0.000 ms 
  - DisplayPanel View ................................ :           5.000 ms 
  - DisplayPanel View - Done ......................... :           3.000 ms 
  - StatusPanel Redraw ............................... :           0.000 ms 
  - StatusPanel View ................................. :           0.000 ms 
  - StatusPanel View - Done .......................... :           2.000 ms 
  - DisplayPanel Redraw - Done ....................... :           0.000 ms 
  - StatusPanel Redraw - Done ........................ :           0.000 ms 
  - Redraw Completed Total ........................... :          11.995 ms 
Performance Results:
  - Start Waiting .................................... :           0.000 ms 
  - Update Model ..................................... :           1.005 ms 
  - Update Model - Done .............................. :          28.995 ms 
  - Total ............................................ :          30.000 ms 
Performance Results:
  - Start Redraw ..................................... :           0.000 ms 
  - App View ......................................... :           0.000 ms 
  - App View - Done .................................. :           0.000 ms 
  - DisplayPanel Redraw .............................. :           0.000 ms 
  - Build Grid ....................................... :           1.000 ms 
  - Build Grid - Done ................................ :           0.000 ms 
  - DisplayPanel View ................................ :           4.005 ms 
  - DisplayPanel View - Done ......................... :           3.995 ms 
  - StatusPanel Redraw ............................... :           0.000 ms 
  - StatusPanel View ................................. :           1.000 ms 
  - StatusPanel View - Done .......................... :           1.000 ms 
  - DisplayPanel Redraw - Done ....................... :           0.000 ms 
  - StatusPanel Redraw - Done ........................ :           0.000 ms 
  - Redraw Completed Total ........................... :          11.000 ms 
`````

**Comment by leeoniya** [comment]
also make sure you're using the `min` versions, they are faster as they're optimized by Google Closure Compiler, you'll see about 15% perf boost.

**Comment by leeoniya** [comment]
FWIW, i get 2.00ms dbmonster 0% redraw in firefox vs chrome's 1.30ms

**Comment by lawrence-dol** [comment]
#### Don't bother trying to cache views.

Confirmed that eliminating the interim cached structure (which was now essentially the same as DOMVM's structure) resulted in a net gain for both Chrome and Firefox, cutting redraw times by about 50% and 72%, resp.

If there is relatively expensive work that can be avoided on every view, it might be worthwhile, but that probably means that your model has polluted your view.

Now the bottleneck is squarely in the realm of processing the host data, which is where it should be. 

There is unlikely to be anything more I do to improve things with respect to DOMVM, which has done it's job admirably.

**Comment by leeoniya** [comment]
> cutting redraw times by about 50% and 72%, resp.

woah 😮
