### ISSUE TITLE
intent to remove exposed refs

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#117]
exposed refs `^foo` is a feature that allows an inner vnode to be added to the refs of ancestor views. this opens the door for memory leaks and very expensive & fragile tracking since the removal og sub-views requires that all ancestor view's refs are cleaned up, preventing redraw optimizations and forcing expensive internal tracking.

purpose of this feature was to allow some level of cross-subview communication at some common ancestor view. however, this type of comm breaks view isolation and is not a design that's robust. if a parent view needs to access a subview's ref it can always traverse the vtree and access the vm.refs object directly.

this feature has never been documented for v2, so it will be removed on either a patch or minor semver bump

**Comment by lawrence-dol** [comment]
No problem with me. And I agree with your reasoning.

**Comment by lawrence-dol** [comment]
Related... Can you now only set refs on a vm's node? I have a reference on a normal HTML node, which causes "TypeError: vnew.vm is not a function" in DOMVM code.

![image](https://cloud.githubusercontent.com/assets/8662551/23344077/ea215d96-fc2a-11e6-8742-21894672580e.png)

Which results in:

![image](https://cloud.githubusercontent.com/assets/8662551/23344083/046829fa-fc2b-11e6-9852-95f90cd85eae.png)

in the following code:

    function preProc(vnew, parent, idx, ownVmid, extKey) {
        if (vnew.type == VMODEL || vnew.type == VVIEW)
            { return; }

        vnew.parent = parent;
        vnew.idx = idx;
        vnew.vmid = ownVmid;

        // set external ref eg vw(MyView, data, "^moo")
        if (extKey != null && typeof extKey == "string" && extKey[0] == "^")
            { vnew.ref = extKey; }

        if (vnew.ref != null)
    ===>    { setRef(vnew.vm(), vnew.ref, vnew); }

        if (isArr(vnew.body)) {
    ...

**Comment by leeoniya** [comment]
that would be a silly restriction. you can set refs on any vnode that will be set within its `vm.refs.*`.

if you cannot create a jsfiddle, please at least post the app-space code that you're invoking. posting just the error is usually not very helpful for me. it sounds like `vnew` is not a `VNode` you're returning from a template.

**Comment by lawrence-dol** [comment]
> that would be a silly restriction

I agree.

> if you cannot create a jsfiddle...

Ouch. I was just asking a question, and providing some context for you. 

The node *is* a vnode, but it's missing it's prototype, which after a little bit of digging, turns out to be a result of my cloning the view tree before returning it to DOMVM. I do this because it's a lot of work to generate on every redraw, and in V1 it was a simple tree of simple objects.

Now the question becomes, does DOMVM still mutate the tree it's given in situ, or can I now safely cache and reuse it? Otherwise, I probably just need to transfer the prototype as well when I'm cloning.

**Comment by leeoniya** [comment]
> Now the question becomes, does DOMVM still mutate the tree it's given in situ

yes. one of the reasons for the huge perf boost is now the vnodes are generated directly rather than allocating and processing an intermediate jsonml structure into the final vtree. once the template is returned, those vnodes are used and mutated directly, refs hooked up and parents linked (all of this happens in `preProc()` [1]). on redraw they are unlinked from the vtree and de-referenced which allows the GC to purge them from mem. you can manip the vtree until it is returned from render but not afterwards since it becomes stale after every redraw. this is the same as it worked in v1, minus the jsonml abstraction.

if you cannot work around this, a v1-compat jsonml pre-processor is available as an addon, but not included in any builds [2]. there is a perf hit to using it, though it will still be quite a bit faster than v1 [3]

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/preProc.js
[2] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/addons/jsonml.js
[3] https://github.com/leeoniya/domvm/issues/101#issuecomment-260141793
