### ISSUE TITLE
Attributes with function value not resolved

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#118]
Creating an input field with a value which is a getter function used to resolve the value in V1. In V2 I now get the `Function.toString()` value.

It was simple enough to solve; after generating my view I just needed to walk the tree and detect such attributes and invoke the function, but...

Is this expected?

**Comment by leeoniya** [comment]
v2 expects everything returned in templates to be vnodes, plain values (that are converted to defineText vnodes or removed).

this is again to reduce the type-testing within the lib. simply invoke the getters/generator functions within the templates, the extra `()` is both clearer and worth the perf boost.

**Comment by lawrence-dol** [comment]
Agreed. Just making sure it was an intentional change.

**Comment by leeoniya** [comment]
the exception to this is `isStream` testing of vnode bodies, prop values and css object values as described in https://github.com/leeoniya/domvm/issues/112#issuecomment-277326369
