### ISSUE TITLE
TypeError: vm.refs is null

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#119]
I have refs in my app which, in some circumstances, are not created (because the node they reference is not required). But other code tests for these refs, doing the obvious:

    if(vm.refs.xyz) {
        ...
    }

This, of course, breaks when there are no refs at all and the `refs` object is null.

Would it be undesirable to always have a `refs` object? Otherwise, I am just ensuring it exists in my render function.

**Comment by leeoniya** [comment]
i'm not sure about this one. i think there's more value in cheaply testing if there are any `refs` at all by testing against null rather than having to do a slow array-allocating `Object.keys(vm.refs).length == 0` in addition to creating an empty refs object for each view.

your case is a bit puzzling to me, too. if you have a single view which may or may not contain refs depending on render() logic, you should probably be setting some kind of viewState flags/vars in your own app that tell unambiguously what's available. relying on the presence of some ref being populated by the view layer seems like a rather indirect method of figuring out what app state you're dealing with.

**Comment by lawrence-dol** [comment]
> you should probably be setting some kind of viewState flags/vars

That's a fair comment. On the one hand, I agree with you, from a big-picture perspective. On the other, I have some code about to use an object which could be null; on principle it's more direct to test that object than some other tangentially related flag. 

It's a bit of a PITA when container objects may be null and you have to constantly test `if(con && con.key) ...` every time you touch it. On the other hand, I guess I signed up for that when I said "use strict".

Furthermore, refs is an object that might be created indirectly in a number of places; it's easy then to create code that tests for a specific reference which works all through testing and then breaks under the specific case where no reference at all was generated.

I raised it as a "hmmm?" Let me ponder it further; I'm torn on the pragmatic desire that refs should be part of the vm even when it's empty.

I didn't especially like my work-around (which was just to ensure the object exists in the vm render).

**Comment by lawrence-dol** [comment]
> i think there's more value in cheaply testing if there are any `refs` at all...

That's a very good point. I forget that JavaScript objects don't have a length property.

**Comment by leeoniya** [comment]
to play devil's advocate, empty checking can be cheap:

```js
isEmpty(obj) {
  for (var k in obj)
    return false;
  return true;
}
```

**Comment by lawrence-dol** [comment]
Yes, though it needs to check for null and `hasOwnProperty`.

    function isEmpty(obj) {
        if(obj == null) { return true; }
        for(var prp in obj) {
            if(obj.hasOwnProperty(prp)) { return false; }
            }
        return true;
        }

**Comment by leeoniya** [comment]
i mean to test a plain refs obj that would be guaranteed not to be null

**Comment by lawrence-dol** [comment]
Current browsers it's can be slightly cheaper with `for of` to not iterate prototype properties:

    isEmpty(obj) {
        for (var k of obj) return false;
        return true;
    }

**Comment by leeoniya** [comment]
i'm gonna close this. if you really want this behavior, you can simply extend the ViewModel prototype with your own ES5 getter (via `Object.defineProperty` [1]) to get the desired effect: https://jsfiddle.net/v1ubxq7o/

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
