### ISSUE TITLE
add support for namespaced svg attrs

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#123]
might have perf implications

**Comment by leeoniya** [comment]
relevant: https://github.com/hyperapp/hyperapp/issues/209

**Comment by sabine** [comment]
> rather than supporting any namespace, just explicitly test for xlink:href, which is cheap

AFAIK, this will do just fine for SVG sprites in an external spritesheet. If there's really some use case where defining other namespaces is useful, it will come up eventually.

**Comment by leeoniya** [comment]
forgot this issue was still open. `xlink:href` support got added in 3.x-dev.
