### ISSUE TITLE
add will/didInit vm hooks

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#126]
doing stuff during view initialization is already handled by the closure invocation.

maybe add will/didInit vm hooks that fire before and after the view closure/constructor, with same args. so this init point can be exposed externally as well. see #125.

**Comment by iamjohnlong** [comment]
My use case for this is I have a component factory that I want to pass in a single object to. Having the init hook would be preferable but I could pass in my own init function and call it myself. If adding will/didInit has a perf penalty I would say don't add it.

**Comment by leeoniya** [comment]
can you post some before/after code here?

**Comment by leeoniya** [comment]
i added a `didInit` vm hook. as expected, there was no measurable perf impact:

```js
var el = domvm.defineElement;

function View() {
    return {
        hooks: {
            willInit: () => console.log("willInit"),
            didInit: () => console.log("didInit"),
        },
        render: () => el("p", "Hello"),
    };
}

var vm = domvm.createView(View).mount(document.body);
```

**Comment by iamjohnlong** [comment]
I'm having a brain fart on what I'm trying to accomplish with this. I'm trying to couple Freezejs and components together, which might not be the best idea. The thought is I would have state-full components the have the freezer object built in. Something like `vm.state`.  

```js

const el = domvm.defineElement;
const vw = domvm.defineView;

const State = new Freezer({
  user: {
    name: 'john'
  }
});

function Component(component) {
  return (...args) => {
    const render = component.render;
    args[0].state = State.get();
    component.render = (...args) => {
      args[0].state = State.get();
      return render.call(null, ...args);
    };
    // if there is an init call it
    if(component.init) component.init(...args);
    return component;
  };
}

const UserComponent = Component({
  init() {
    console.log('init something here..')
  },
  hooks: {
    didMount(vm) {
      console.log('did', vm.state);
    }
  },
  render(vm, model) {
    return el('h1', vm.state.user.name);
  }
});

const View1 = () => {
  return {
    render(vm, model) {
      return el('div', [
        vw(UserComponent)
      ]);
    }
  };
};

const vm = domvm.createView(View1);

vm.mount(document.body);


```

**Comment by leeoniya** [comment]
i continue to be confused by what value Freezer brings to your past examples, as well as this one.

here, every component's "state" is the full app state, so the isolation isnt there. why not just use the global State instead of doing extra work to set a *global* state on every view?

freezer's core deliverable is that it brings immutability and update notifications. this allows for optimized redraws (assuming you hook up `vm.diff`), and view reactivity (changing the global store auto-redraws the views). here, you're using freezer, but you're not really *using* it. the use of freezer in this example is just noise, i think.

it may seem strange coming from an author of a view lib, but to me, views are secondary to a Component; they are not *the* component itself. i think the README in this repo illustrates the difference very clearly in the `Hello World++` example. this is contrary to how many devs use React, where using their view-centric components is promoted, though there's no reason that React can't be used in a secondary capacity, like domvm.

i kinda see what you're trying to do here but i dont understand *why* and what the motivation is.

**Comment by iamjohnlong** [comment]
> here, every component's "state" is the full app state, so the isolation isnt there. 

Yeah I think I'll let a param be passed in as a string `'some.deep.state'` get it and set  it to vm.state, or `'*'` to get the full state. 

> why not just use the global State instead of doing extra work to set a global state on every view?

I'm toying with this idea to see if it is worth it. In my mind it simplifies things, if I've chosen to depend on Freezer or whatever state container then why not couple it with a state-full component? Whats the drawback? The example doesn't have the component modify the state so it's not very clear of the benefits of having the state there. Crapy example.

> freezer's core deliverable is that it brings immutability and update notifications. this allows for optimized redraws (assuming you hook up vm.diff)

I could wire it up to diff and auto redraw. But I don't mind explicitly calling redraw when I set the state. If performance is an issue I can always add the vm.diff per component.

> views are secondary to a Component; they are not the component itself.

I think that's what I'm doing here. The state-full component cares about having state and the view just expects state to be the current state. All this is doing is calling State.get in the render for you.

**Comment by leeoniya** [comment]
alright, i'm done being a hypocrite and prescribing how domvm should be used, considering that flexibility is a core selling point :)

your example looks and works fine. with the added `didInit`, you can now hook into a more complete post-initialization callback. what your example does gets executed here [1], while `didInit` will fire later [2], giving you access to more vm stuff.

as a side-note, you should use `return render.call(args[0], ...args);` to match the calling semantics of a normal render, where `this === vm`. if you don't do this, ES6 class views would break. otherwise it doesnt matter, it's not needed for anything internally.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/ViewModel.js#L17
[2] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/ViewModel.js#L57

**Comment by leeoniya** [comment]
this is now released as part of 2.1.3.

**Comment by iamjohnlong** [comment]
Thanks for the feedback and the hooks 👍

**Comment by leeoniya** [comment]
@iamjohnlong i'll be removing the `didInit` hook in v3 in favor of `{init:}` return. this will better align with planned plain-object views as well as replacing es6 class views' wordy `constructor` with a shorter `init`.

**Comment by iamjohnlong** [comment]
sounds good, looking forward to v3
