### ISSUE TITLE
removal of h, defineElementSpread from builds

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#127]
`domvm.defineElementSpread` and `domvm.h` have been removed from the dist builds. they were mostly dead weight and i personally don't use them. like `jsonml`, they're still available in /src/view/addons and it's easy to make a custom build that includes them by uncommenting in the build script [1].

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/builds/nano.js

**Comment by lawrence-dol** [comment]
Sounds good to me. Only use for `h` I would have is porting from Mithril... and I'm not certain how useful that would be.

**Comment by iamjohnlong** [comment]
@leeoniya can you distribute 2.1.3 to npm?

**Comment by leeoniya** [comment]
it's up

**Comment by iamjohnlong** [comment]
thank you sir
