### ISSUE TITLE
setting "for" attribute in label tag

### ISSUE THREAD

**Issue by xz64** [leeoniya/domvm#129]
Hi,

Is there any way to set the "for" attribute on a `<label>` using `defineElement`? I tried this and it didn't work: 

`el('label', { 'for': 'username' })`

Thanks in advance

**Comment by leeoniya** [comment]
make sure u're setting an "id" and not just "name" on the input itself.

https://jsfiddle.net/u0tuag0e/

**Comment by xz64** [comment]
I see. I was setting the "for" on the wrong element which is why it wasn't working for me.
