### ISSUE TITLE
Uncaught TypeError: Cannot read property '_node' of null

### ISSUE THREAD

**Issue by xz64** [leeoniya/domvm#131]
Hi,

I am seeing an issue where the existence of a willUnmount hook will trigger this error to occur during a redraw:
 
```
Uncaught TypeError: Cannot read property '_node' of null(…)
headTailTry @ domvm.nano.js?f7fe:839
syncChildren @ domvm.nano.js?f7fe:969
patchChildren @ domvm.nano.js?f7fe:1153
patch @ domvm.nano.js?f7fe:1054
redrawSync @ domvm.nano.js?f7fe:1473
(anonymous function) @ domvm.nano.js?f7fe:1268
call @ domvm.nano.js?f7fe:135
```

The`headTailTry` function is called with `lftSib` and `rgtSib` being `null`

I tried to find a minimal test case to reproduce it, but I couldn't reproduce it. (I can reproduce it in a larger project though) Here is the code I tried to reproduce the issue:

https://jsfiddle.net/2qrgsk8b/3/

One thing that is interesting is that if I remove the willUnmount hook from one of my views (which gets removed during a redraw) then the error doesn't occur. Even a no-op willUnmount hook will cause the error. The view with the willUnmount hook does not have any other hooks either nor is it doing any manual dom manipulation. I am using domvm 2.1.4 nano build.

**Comment by leeoniya** [comment]
your fiddle doesn't error for me in any browser, should it?

unfortunately without a repro, i cannot really begin to dig into this :(

BTW, `vw(ViewWithUnmountHook, {}, false)` can just be `vw(ViewWithUnmountHook)`. Also, rather than wrapping and passing down `{ switchView: switchView }`, you may consider using the `micro` build that has internal event bubbling addons: `vm.emit("switchView", "view2")` in a descendant & `vm.on({switchView: function(viewName) {...}})` in some ancestor.

**Comment by leeoniya** [comment]
i'm not sure if this will help me much, but can you check if the same issue also occurs for you when using a view's root node's hook instead via `el("div", {_hooks: {willRemove: Function.prototype}})`. those hooks have a lot of similarities.

**Comment by xz64** [comment]
The fiddle isn't supposed to have the error. I just put it there to give an idea of what kind of code was causing the error to happen. I think it has something to do with `redraw` being called twice in the same event loop. (first in the parent view (causing child vnodes to be gone), then in the child view (when child vnodes no longer exist due to the first `redraw` call)

The same issue does occur even if I use the `willRemove` hook the way you described.

**Comment by leeoniya** [comment]
here's some info which may help.

there's a fast path for removal of entire dom branches via `.textContent = null` in the absence of `willUnmount` or `willRemove` hooks in the decedents. This assertion and bubbled flag setting is done in the template preprocesor [1] shortly after you return a template from a view's `render()`. when either of these flags is detected, the removal of the whole branch is done using the slower depth-first bottom-up manner [2].

what may be happening is that the flag is not being set when it should be, but i'm not sure this would cause the exact behavior you're seeing. perhaps understanding/stepping through this can help you narrow down a reduced case.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/preProc.js#L30
[2] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/dom.js#L38

**Comment by leeoniya** [comment]
i tried getting it to fail by doing multiple mounts/unmounts, but still nothing :/

https://jsfiddle.net/2qrgsk8b/4/

**Comment by xz64** [comment]
The DEEP_REMOVE flag appears to be getting set properly. Can you explain the purpose of `syncChildren` on a high level? I'm trying to see how` lftSib` and `rgtSib` end up being `null` by the time `headTailTTry` is called. My guess is that it's trying to recycle some DOM element whose `previousSibiling` became null after being removed from the DOM.

**Comment by leeoniya** [comment]
redraw works like this:

1. render returns new vtree template
2. preProc flattens arrays, etc. sets up refs, idx, parent links.
3. a diff happens between old vtree and the processed new vtree: the new vtree is recursively crawled and donor vnodes are looked up in the old vtree. once a matching vnode is found its .el dom reference is moved over and direct props/attrs/events are patched in the dom.
4. syncChildren then runs to reorder the dom, initialize new views, insert new nodes and remove any order any dom elements whose vnodes are did not get recycled in 3. most of the hooks run in this final dom reconciliation pass.

**Comment by xz64** [comment]
I have reproduced the error via this fiddle:

https://jsfiddle.net/2qrgsk8b/7/

The behavior changes depending on how many `span`s are inside `View1`.

- 0-2 `span`s - no error
- 3 `spans`  - `domvm.nano.js:516 Uncaught TypeError: Cannot read property 'previousSibling' of null`
- 4+ `span`s - `Uncaught TypeError: Cannot read property '_node' of null`

**Comment by leeoniya** [comment]
ah, i see what's going on. you're trying to redraw an unmounted subview, which doesnt makes sense.

The `vm` arg provided to the any view closure is that view's instance. When you call `vm.redraw()`, you're redrawing *this* view and all its descendants. In your example you're first, redrawing the top-level view by calling the passed-down `model.switchView()` effectively unmounting View1 and then call `vm.redraw()` within `onSwitch` which tries to redraw the already-unmounted View1.

From a subview, you can always redraw an ancestor view by doing `vm.parent().redraw()` or `vm.root().redraw()`. Alternatively you can use the emit system as suggested above to request a redraw from an emit `on` handler somewhere above.

It's possible to add a more helpful message that can warn you if you're trying to redraw an unmounted view, but this will add some bytes to the build. I haven't investigated exactly why the error messages differ depending on the number of siblings, but i'm not sure this matters.

Let me know if that makes sense and thanks for taking the time to narrow it down.

**Comment by xz64** [comment]
Yes, that makes sense. Thanks for the help!

**Comment by tropperstyle** [comment]
> It's possible to add a more helpful message that can warn you if you're trying to redraw an unmounted view, but this will add some bytes to the build

@leeoniya I've also run into scenarios where it would have been nice for the framework to throw an explicit error when something is definitely wrong. What about something like [rollup-plugin-strip](https://github.com/rollup/rollup-plugin-strip)? Additional asserts would definitely help while developing, but they don't necessarily need to be in the production builds.

**Comment by leeoniya** [comment]
i've considered something like this, but the asserts/logs/debugs need to be conditional and often must create temp variables and call helper functions.

the issue is that the conditions end up not being stripped and often leave the whole block behind because what was required was more than just a single statement/expression but some additional logic to test for errors.

ideally a rollup plugin would strip everything within `if (DEVMODE) { }` blocks and `DEVMODE && (...)` statements only when some global `DEVMODE === true` (i can work this logic into my build script). Then we could add a bunch of complex assertions and error messages to the source.
