### ISSUE TITLE
Injection of arbitrary HTML

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#138]
I am in the process of designing a system whereby our customer's can supply the body of sections of the UI via their own JavaScript, which might use any mechanism they want to generate the HTML.

What's the recommended way with DOMVM of creating a container where the contents should be left alone, to be manipulated apart from DOMVM? Does the `_raw` flag still exist?

**Comment by leeoniya** [comment]
yes, `_raw` still exists, though i would advise against using it use `domvm.injectElement()` after running the provided html through DOMParser[1] to get back a safe dom node. it depends on your use case tho.

[1] https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

**Comment by lawrence-dol** [comment]
The customer will be required to provide an element or array thereof. I will simply add whatever they supply to the specific container. The interaction is trusted, so I don't expect to require a string form or parser.

So, I just create a view container to hold it and have the renderer use `injectElement()` like so:

~~~~
function view() {
    return function(vm) {
        return domvm.injectElement(customerHtml);
        }
    }
~~~~

(Can't find any documentation for `injectElement` or a demo using it.)

**Comment by leeoniya** [comment]
it doesn't need to be a view root either, but can be if you want: https://jsfiddle.net/51zkydms/

> (Can't find any documentation for `injectElement` or a demo using it.)

it's there ;) https://github.com/leeoniya/domvm#templates

and there's a "demo" in the tests: https://github.com/leeoniya/domvm/blob/2.x-dev/test/src/others.js#L169

**Comment by lawrence-dol** [comment]
Looks pretty straight-forward. Thanks.
