### ISSUE TITLE
Microsoft Edge rendering bugs with DEVMODE warnings turned on

### ISSUE THREAD

**Issue by e1ectronic** [leeoniya/domvm#139]
I got some strange errors in Microsoft Edge with DEVMODE warnings turned on. 

Problems gone when I replaced this line in domvm.dev.js
`console.warn.apply(null, msgArgs);`
with this
`console.warn.apply(console, msgArgs);`

Software versions:
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by leeoniya** [comment]
nice catch! will fix today.
