### ISSUE TITLE
Comment the purpose of each function

### ISSUE THREAD

**Issue by FaizShah** [leeoniya/domvm#14]
It would be helpful if there was a comment before each function that gave a short description of what it does and what it's used for. I know a few are commented but it would make it much easier to read the source if you could add comments for every function.

**Comment by leeoniya** [comment]
Wasn't expecting people to start hacking the source so soon, heh :)

Not opposed to adding some more descriptions, but priorities right now are on finishing the routing plugin and making much more public API docs. The internals explanation would be secondary and could only be terse to those who are already familiar with the lib's ergonomics.

If you have questions about specific internal functions, go ahead and ask here. If you want a high-level overview, I can also give you that.

**Comment by leeoniya** [comment]
speaking of routing, if you'd like to provide some feedback on the current implementation that would be very helpful. see #11

**Comment by lawrence-dol** [comment]
@leeoniya 

> Wasn't expecting people to start hacking the source so soon, heh :)

Ha ha. I pulled the project and began looking over the source from the first day you tagged me. The best indicator of the quality of the thinking of a person is the quality of the code they write.

**Comment by leeoniya** [comment]
lol, there was some hairy code in there before. hope i didn't tag you too early :)

**Comment by FaizShah** [comment]
@leeoniya

Well, specifically I had a hard time quickly finding where the implementation of the templating language is, since the words 'template' and 'jsonml' aren't used in the source. Other than that it's relatively easy to read the code right now so it shouldn't be a main concern.

> Wasn't expecting people to start hacking the source so soon, heh :)

I have wanted to write something like this for a while out of frustration for the way other javascript frameworks and libraries are written. When you linked me to it on HN I was really happy and started looking through the source immediately. :)

I noticed in your forked libraries you have a lot of the same libraries I was researching, I have a few more to suggest you look at if you're interested.

Gonna work on my first app with domvm either today or tomorrow, will report back with the results. :)

**Comment by leeoniya** [comment]
@FaizShah 

Thanks! I look forward to some feedback. While I think broadly ingesting even more libs would reduce my focus, please link them anyways. If there is a lib or concept that can logically fit into domvm, I will definitely look at it, but from what I have seen, many pretty/terse features presume a coupled structure, so may not work at the lower levels.

**Comment by leeoniya** [comment]
btw, if your project is plopen source, it would be very helpful to see it in full rather than isolated pieces. It would be easier for me to see when you're scope-hacking around poorly documented or undocumented features.

**Comment by leeoniya** [comment]
I've published the router and split the lib into a few modules. The API has changed slightly.

`domvm()` is now `domvm.view()`

`vm.html()` is now `domvm.html(vm.node)`

**Comment by leeoniya** [comment]
gonna close this. not because i don't think it should be done but there's just way too much other stuff to get done by 1.0 and until the lib is stable there's enough changing internally that it doesn't make sense to spend additional time on this.
