### ISSUE TITLE
Declarative view events

### ISSUE THREAD

**Issue by tropperstyle** [leeoniya/domvm#142]
What is the recommended way to pass events through a declarative view?

```javascript
vw(CustomerSelector, {
  _events: {
    select: customer => console.log('I am never called from vm.emit')
  }
}),
```

```javascript
vw(CustomerSelector, {
  onselect: customer => console.log('Do I put this in the model?')
}, 'key-needed-else-always-remounts'),
```

Sometimes I use a global state object or sometimes I will pass a model for the view to manipulate `vw(CustomerSelector, OrderForm)` but there are times when I'd prefer a component that only knows about it's internal state and abstracts underlying input events and exposes it's own set of event handlers.

**Comment by leeoniya** [comment]
you can pass extra data through the last `opts` argument. the full signature is:

```js
domvm.defineView(viewFn, model, key , opts)
```

currently domvm does reserve `diff` and `hooks` [1] in opts that it will auto-process if you wanted to define either of those externally. otherwise you can set custom keys on it and do whatever you need.

another option is to just wrap your model in an ad-hoc object and just provide an explicit key:

if keying by model identity, as would be default without key and wrapper:

```js
vw(CustomerSelector, {model: model, events: ...}, model);
```

or by some explicit key:

```js
vw(CustomerSelector, {model: model, events: ...}, model.id);
```

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/ViewModel.js#L47-L54

**Comment by iamjohnlong** [comment]
@leeoniya how do you feel about changing the model key word to state? I find myself doing `model.model` a lot.

**Comment by leeoniya** [comment]
there's no requirement for the wrapper to have a `model` key, it's just an example. domvm doesnt care about anything except the identity of the object you pass in and the key. you can have a wrapper `{someState: foo, myEvents25: ...}` and it'll work fine.

the only place where the literal `model` exists is `vm.model`, which you dont ever need to reference because it's passed into the view and render() as an arg, and you can rename that to "state" in your app code if you prefer.

if you're talking more from a documentation / philosophical perspective, i think that "model" is a better fit for domvm since it doesnt advertise itself as a pure/functional solution, although it's easily used this way by simply ignoring the closure state and only ever using the args passed to render().

**Comment by tropperstyle** [comment]
So, the other option in practice looks like:
```javascript
vw(CustomerSelector, null, 'still-needed?', {
  onselect: customer => console.log('Called from vnode.opts.onselect?')
}),
```

I'm referring to a view without any model other than it's own UI state. The example of `CustomerSelector` might include a list with search functionality. Another example is a `PhoneInput` that includes a country code selector and number formatter. These views don't manipulate models, they provide abstractions over dumb inputs and events.

**Comment by iamjohnlong** [comment]
@tropperstyle why not just use a template if holding state is not needed?

**Comment by tropperstyle** [comment]
I think you mean something like:

```javascript
function customerselect({onselect}) {
  return el('div.customer-selector', [
    // Some form that eventually calls onselect
  ]);
}
```

Consumed like:
```javascript
el('div.page', [
   customerselect({
     onselect: customer => console.log('alrighty')
   })
])
```

So now where do I place my UI state? I can use a closure, but then all instances share the same state, and I need it isolated per instance.

From Sub-views vs Sub-templates:
> [vnodes] Can hold data, which can then be accessed from event handlers

So I can initialize private data on the first mount that is accessible during the life-cycle of the vnode? How would I do that with the code above?

**Comment by leeoniya** [comment]
> I'm referring to a view without any model other than it's own UI state. 

if `CustomerSelector` has no other `CustomerSelector` siblings, then it will always recycle properly, so you don't need to provide a key in this case. For views that just need some external data i typically do:

```js
vw(CustomerSelector, {
  onselect: customer => console.log('Called from vnode.opts.onselect?')
}, false),
```

this basically prevents the view from being keyed by the wrapper identity. you can use any static value, it doesn't need to be `false` (`""`,`0`,`"blah"` will all work fine).

> So I can initialize private data on the first mount that is accessible during the life-cycle of the vnode? How would I do that with the code above?

vnodes themselves are destroyed and recreated during each redraw, but they can hold temp data *until* you redraw:

```js
el("div", { _data: "mooo", onclick: (e, vnode) => console.log(vnode.data) }, "sup");
```

**Comment by leeoniya** [comment]
i think there's enough info here, but feel free to ask for further clarification if needed.

**Comment by tropperstyle** [comment]
Thanks for the clarification. I haven't found a use case for parameterized handlers nor vnode data, but semi related: how can I clean up an event handler?

```javascript
_hooks: {
  didInsert({el, data}) {
    data.onclick = function() { };
    el.addEventListener('click', data.onclick);
  },
  didRemove({el, data}) {
    el.removeEventListener('click', data.onclick);
  }
}
```

This won't work as you stated above, vnodes are recreated each redraw. The only options I can think of is pulling the function up into a closure variable or beefing it up to a subview.

**Comment by leeoniya** [comment]
out of curiosity, why aren't you using `{onclick: ...}`. using hooks this way will be significantly slower.

**Comment by tropperstyle** [comment]
I updated my previous comment to show more of the desired intent.

**Comment by leeoniya** [comment]
you *could* use a `willRecycle` hook to do `vnew.data = vold.data` to transfer it over, but it's unnecessary jumping through hoops that's easily avoided with a subview. i'm also partial to the micro [balalaika](https://github.com/finom/balalaika) for jquery-esque dom manip sugar.

here's a quickly-rolled custom dropdown: https://jsfiddle.net/L2sgvvod/

if you're using a much heavier lib like Select2, then YMMV, but since domvm can now ignore foreign elements in its dom ;), you can still append the created wrapper into your own subview rather than `<body>` globally.

**Comment by tropperstyle** [comment]
I actually had an example like that originally, but I removed it because I didn't want you to make that leap to hide the event handlers in the sub-view.

Rolling with your example..

```javascript
el('input', {
  onfocus: => (e, {data}) => { data.dropdown.open() },
  _hooks: {
    didInsert({el, data}) {
      data.dropdown = domvm.createView(Dropdown);
    },
  }
}
```

There is still a need to access the non-child element from the host event handlers. I think the `willRecyle` line is what I'm looking for.

Thanks!

**Comment by leeoniya** [comment]
it's a rather odd pattern, considering the `vm` returned by createView holds a partial vtree, which you're storing tangentially on a parent vnode's `data`. perhaps i'm not understanding the larger context that warrants such an unusual design. i've written pretty complex apps with domvm and never had to do something like this, including transfering over vnode data. any "awkward" code in my domvm apps is almost universally around animations/transitions. i may suggest something else if you can show the fuller use-case.

**Comment by tropperstyle** [comment]
I build custom UIs with HTML/CSS. Think native feeling, not web standards. I used to use mithril, but 1.0 release was way off the mark for me.

Due to layout limitations, you sometimes cannot have a conceptually related element as a child, or even a sibling.

I added a few lines of CSS to your fiddle to illustrate this:
https://jsfiddle.net/yoqrp6ux/1

So now you must have the dropdown live outside, but it is still managed from a source vnode. Why is storing this on `data` an odd pattern? Rather than domvm providing some persistent `state` object, that seems to be opt-in with `willRecycle`.

**Comment by leeoniya** [comment]
> Due to layout limitations, you sometimes cannot have a conceptually related element as a child, or even a sibling.

this was actually a core consideration during domvm's design. the conclusion i came to after multiple prototypes is that the least-surprises route is simply not to use declarative views in cases like this. and so, this need is addressed in domvm by either imperative composition, which, i think, is domvm's distinguishing feature; you can inject pre-initialized, partial views into disjoint parts of your templates (or dom mount points) while maintaining isolated redraw control without relying on a global shared state and global redraw.

```js
var el = domvm.defineElement,
    iv = domvm.injectView;

function Dropdown(opts) {
    function InputView() {
        return () =>
            el("input");
    }

    function OptsView() {
        return () =>
            el("ul", opts.map(o =>
                el("li", o)
            ));
    }
    
    // public api and exposed views for embedding
    const self = {
        open: () => {...},
        close: () => {...},
        redraw: () => {
            for (var name in self.views)
                self.views[name].redraw();
        },
        views: {
            input: domvm.createView(InputView, self),
            opts: domvm.createView(OptsView, self),
        },
    };
    
    return self;
}

function AppView(vm, state) {
    const myDrop = Dropdown(["A","B","C"]);
    
    return () =>
        el("body", [
            el("header", [
                "Hello...",
                iv(myDrop.views.input),
            ]),
            el("main", [
                "Options: ",
                iv(myDrop.views.opts),
            ])
        ]);
}

var appView = domvm.createView(AppView).mount(document.body, true);
```

as a trade-off for giving up declarative view composition, you get shared state without hacks, disjoint and granular redraw control, a user-defined exposed widget API/state. the second example of https://github.com/leeoniya/domvm#hello-world is somewhat like this but exposes a single view from the "component". there's also wiki page (that needs updating to domvm v2) on the flexibility of different patterns. (v1 had JSONML-esque templates, but the semantics remained the same).

anyways, hope that helps or gives you some ideas. regardless, if you found something that works/makes sense for you then go with it :)

[1] https://github.com/leeoniya/domvm/wiki/View-Model-Patterns
