### ISSUE TITLE
The `window` namespace.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#144]
I am preparing an external API with which our customers will interact with my app in a very controlled manner. To that effect I want DOMVM and all other external library code entirely hidden from them so they cannot screw anything up. I noticed the following lines in the DOMVM, the only place where it breaks it's encapsulation of `this` at line 1605 in the micro build:

    // prevent GCC from inlining some large funcs (which negatively affects Chrome's JIT)
    window.syncChildren = syncChildren;

I wonder, can that be changed to `this.syncChildren` and still have the desired effect in Chrome?

**Comment by leeoniya** [comment]
this code is stripped out by the build script after the minification pass [1]. the only exposed symbol in the min builds is `domvm`.

it seems silly to be concerned with customers digging into undocumented apis anyhow considering there's no real way to protect against this.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/build.js#L149

**Comment by lawrence-dol** [comment]
> this code is stripped out by the build script after the minification pass

Then, it won't perform the stated purpose, no? So why have it in there?

> it seems silly to be concerned with customers digging into undocumented apis anyhow considering there's no real way to protect against this.

You may think so, but I do not. And there are very easy and highly effective ways to prevent customer's from shooting themselves in the foot (and wasting hours and days of Technical Support and Developer time), provided they don't edit the source, which is something we can see and document and consequently charge them for.

**Comment by leeoniya** [comment]
> Then, it won't perform the stated purpose, no? So why have it in there?

it's there to prevent the *minifier* from inlining syncChildten. after the min is done it can be stripped out.

**Comment by lawrence-dol** [comment]
> it's there to prevent the *minifier* from inlining syncChildten

Ohhh. I see.
