### ISSUE TITLE
[docs] diff() & identity return

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#148]
when `diff()` returns an array or object that does not match by identity to the prior diff return, it will shallow-compare these types. if the intent is to return the whole model (as with immutable structures) and the model changes, it will trigger an unnecessary shallow compare which is not needed and could result in a wrong answer if the diff lives deeper than 1 level.

since we can't tell what the author's intent is, it can be documented that the workaround is to return a wrapped model in an ad-hoc object or array. this would prevent the cheapest `===` diff without an extra wrapper allocation, but could prevent potential bugs.

**Comment by leeoniya** [comment]
rolling into #156

**Comment by niahoo** [comment]
Hi, the doc is unclear to me regarding diffing with immutable state.

Does the following code mean that the view will never redraw because `0` is always equal to `0` ?

```javascript
var StaticView = {
    diff: function(vm, data) {
        return 0;
    },
    render: function(vm, data) {},
};
```

Does the following mean that the view will not redraw if `data` is the same object instance as `data` from the previous call (comparing with `===`) ? 

```javascript
    diff: function(vm, data) {
        return [data];
    },
```

What happens when I just return the `data`, when it is the same object as before ? When it is a new object ?

Thanks !

**Comment by leeoniya** [comment]
you're right. i think the docs need to be updated. there's no need to array-wrap immutables.

> Does the following code mean that the view will never redraw because 0 is always equal to 0 ?

yes. the actual logic is pretty simple:

https://github.com/leeoniya/domvm/blob/e7299cc42077ae1750ae8de1f753042570ce63f9/src/view/ViewModel.js#L214-L220

it first does a strict equivalence check on the return value of `diff()`, and if that fails it will then either do a shallow array or object comparison.

**Comment by niahoo** [comment]
Alright, thank you very much :)

**Comment by leeoniya** [comment]
sorry, i take that back. (still need that coffee.)

if there's no difference, then the equivalence prevents a further diff. BUT if the immutable is different, it will fall back to shallow-diffing the immutable (which is redundant). it wont cause any different behavior, but is extra work that doesnt really need to happen. if you array-wrap, then at most you'll get a single test in all cases.

does that make sense?

**Comment by niahoo** [comment]
Yeah, looking at the code extract above, it does :)

**Comment by tropperstyle** [comment]
I'm still a bit confused by this. If I used freezer.js[1], the recommendation is to array wrap `freezer.get()`? Why would this do less work than without it wrapped in the array?


[1] https://github.com/arqex/freezer

**Comment by tropperstyle** [comment]
Nevermind, I get it after looking at the utils functions. Essentially, you want === on a frozen object. But for regular objects, you want to compare properties instead of the pointer.

**Comment by leeoniya** [comment]
> If I used freezer.js[1], the recommendation is to array wrap freezer.get()?

the recommendation is to array-wrap any immutables returned from `diff()`. at the top level it could be the full state (`freezer.get()`) but in sub-views it may be a portion of that state which was extracted and passed down.
