### ISSUE TITLE
[mem] render() cannot easily be shared across view instances

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#149]
each view instance wraps render() in a rAF-debouncing function to prevent > 60fps redraw floods. this technically prevents us from sharing a single function across multiple views of the same class.

we can either make render() debouncing opt-in globally or per-view. or find another way to avoid having to wrap it so it can be shared.

**Comment by lawrence-dol** [comment]
> opt-in globally or per-view

I think any differing functionality must be opt-in-per-view, or else using components built in isolation becomes impossible.

> to avoid having to wrap it so it can be shared

It's most likely I am missing some subtlety, but it seems to me that the lion's share of the expense is the render function itself, not it's wrapper, so it's worthwhile to share the render function even if it's wrapped, no?

**Comment by leeoniya** [comment]
yes, for sure. but the typical pattern is to return render from the closure, so it's not shared as a standard pattern and in addition it is wrapped by the debounce. so, double-whammy. it really only matters for view init and only when you have a list of 1k+ views.

the closure return will not be a requirement in v3 with plain object components, so i think this is mostly a non-issue.
