### ISSUE TITLE
compare domvm with mithril, performance etc.

### ISSUE THREAD

**Issue by futurist** [leeoniya/domvm#150]
I'm just found domvm, and used [mithril](https://github.com/MithrilJS/mithril.js) for a long time before, now I'm doing a performance test as below, using

https://github.com/MithrilJS/mithril.js/tree/next/performance

And your [mithril-adaptor](http://leeoniya.github.io/domvm/demos/mithril-adapter/)

**DOMVM2.1.4**

```
rerender without changes x 358 ops/sec ±10.57% (29 runs sampled)
construct large VDOM tree x 11,796 ops/sec ±5.39% (32 runs sampled)
mutate styles/properties x 287 ops/sec ±20.81% (21 runs sampled)
```

**Mithril 1.1.1**

```
rerender without changes x 3,414,552 ops/sec ±6.55% (47 runs sampled)
construct large VDOM tree x 3,610 ops/sec ±4.56% (49 runs sampled)
mutate styles/properties x 10,763 ops/sec ±3.24% (51 runs sampled)
```

Seems the construct time is fast, but later **mutate styles/properties** is slow for DOMVM

But I'm wondering some lost in my test, can you have a look at the test file for DOMVM?

[test-perfdomvm.zip](https://github.com/leeoniya/domvm/files/1063344/test-perfdomvm.zip)

**Comment by leeoniya** [comment]
those numbers are impossible :)

there is a high probability that the Mithril implementation recycles the DOM while the domvm impl is recreating the full dom on each cycle.

that mithril-adapter is pretty old and i would advise against using it. i'll see if i can reproduce that bench in domvm later today for you.

**Comment by leeoniya** [comment]
@futurist what's the easiest way to run these in a browser? there seems to be a lot of mocks etc to run this under node?

**Comment by futurist** [comment]
Yeah, it's not easy to run, I'm using below steps:

```
git clone https://github.com/MithrilJS/mithril.js
cd mithril.js-next
npm install
copy indexdomvm.html test-perfdomvm.js performance/
```

Then goto `performance` folder and open `indexdomvm.html` for DOMVM, and `index.html` for mithril.

But the DOMVM version can only run first 3 tests...

**Comment by leeoniya** [comment]
you can tell from just opening it that the implementations are not the same. domvm renders hundreds of copies, while mithril renders just 1.

there is already a fairly extensive [benchmark](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html) that compares domvm performance against dozens of other frameworks, including Mithril 1.1.1. that benchmark actually analyzes Chrome's timeline view, so the results are quite accurate and impossible to cheat on.

i'm not certain that i want to implement every other framework's benchmarks to prove the performance. do you have any specific concerns?

**Comment by futurist** [comment]
For me I'm compare the deep details for mithril and domvm, not just performance. Like sync render, partial render, etc. And want to convert my existing mithril component with minimal cost. So consider the possibility, values and time.

The beauty of domvm is the total control of the virtual dom, I think, but the mithril way of virtual dom have simple concept and less code to do the virtual dom job, but less controllable than domvm.

But If you can provide some guide for mithril user(or some other vm-lib user), that's a good thing for the community.

The performance in the benchmark is good, thank you!

This issue just a question, and now can be closed...

**Comment by leeoniya** [comment]
>  And want to convert my existing mithril component with minimal cost.

i'm happy to provide guidence for how to migrate specific mithril code to domvm views. possibly this can be turned into a wiki for other users. if you provide mithril jsfiddles you want to convert, i will give you domvm jsfiddles that are equivalent.

domvm's hyperscript does not support a spread body signature out of the box and requires the body to be a single argument (array, string, number):

```js
// mithril
m(".foo", {},
  m(".bar",
     m(".baz", "hello")
  )
)

// domvm
var el = domvm.defineElement;

el(".foo", {}, [
  el(".bar", [
     el(".baz", "hello")
  ])
])

// domvm w/defineElementSpread

var el = domvm.defineElementSpread;

el(".foo", {},
  el(".bar",
     el(".baz", "hello")
  )
)
```

[defineElementSprea](https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/addons/defineElementSpread.js) is available as an addon and can be marked for inclusion in any custom build.

**Comment by futurist** [comment]
Any perf comparing with [mithril 1.x](https://github.com/MithrilJS/mithril.js)? Really want to know that 😄

**Comment by iamjohnlong** [comment]
@futurist https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html

**Comment by futurist** [comment]
Compare with mithril, the only concern is the `m.route` counterpart. I've checked [domvm-router](https://github.com/leeoniya/domvm-router), but it's not updated since 2016. Any update for the router? Or any suggestions? Thank you!

**Comment by leeoniya** [comment]
hey @futurist domvm focuses on doing one thing: rendering and composing views.

domvm-router **does not** enable defining routes in your views, it's simply a router i wrote, similar to existing third party routers as mentioned in the docs [1]. domvm-router does have a nice feature of generating routes from parameters, which many other routers lack. it does need some documentation, but you can see how it's used here [2] and feel free to use any other router lib.

the logic of which views must to be rendered based on route can be defined in your templates, it can be as simple as:

```js
function activeTabView() {
  if (window.location.href.indexOf("users") != -1)
    return vw(UsersView, store.users);
}

el(".tab-content", [
  activeTabView()
])
```

[1] https://github.com/leeoniya/domvm#what-domvm-is-not
[2] https://github.com/leeoniya/domvm-router/issues/1
