### ISSUE TITLE
removal of only child w/willRemove hook & Promise results in loop

### ISSUE THREAD

**Issue by sabine** [leeoniya/domvm#153]
Hi Leon,

I accidentally managed to write some code that triggers `willRemove` lots of times, then went on to find out what causes it.

It looks to me like there's something strange going on when you 1) remove the last child of a node, and 2) the node returns a Promise from its `willRemove` hook.

Look at this pen for a fairly minimal example (I made it stop after producing a bunch of duplicate `willRemove` calls so that you have a chance to inspect things. When I let it run freely, it keeps the browser tab so busy that it's hard to see anything):
https://codepen.io/anon/pen/xrYbRM

Maybe I'm trying to use things the wrong way - I do have a talent for that. :)

**Comment by leeoniya** [comment]
hey, thanks for the repro. this looks like a legit bug. i've reduced the testcase further: https://codepen.io/anon/pen/owEjXE?editors=1010

```js
var el = domvm.defineElement;

function View1(vm, data) {
    var x = 0;
  
    var hooks = {
        willRemove: node => {
            console.log("willRemove", node);

            if (++x < 10)
                return new Promise((resolve, reject) => setTimeout(resolve, 100));
        }
    };

    return () =>
        el("ul", data.map(word =>
            el("li", {_hooks: hooks}, word)
        ))
}

var data = ["foo"];

var vm = domvm.createView(View1, data).mount(document.body);

setTimeout(function() {
    data.pop();
    vm.redraw();
}, 1000);
```

**Comment by leeoniya** [comment]
this should be resolved. thanks for the report.

**Comment by sabine** [comment]
cool! :)
