### ISSUE TITLE
View initialization uses stale data.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#154]
I have a view whose state data has nothing at all to do with the parent which creates the view. So I tried to initialize `vm.data` in my view constructor:

````
function View(vm) {
    vm.data={};
    ...
    return {  init: viewInit, render: viewRender };
    }
````

But when I tried to access the state in `init`, I found it was passed as `undefined`:

````
function viewInit(vm,sta) {
    /**/console.log("[**] init vm",vm); // vm.data is there
    /**/console.log("[**] init sta",sta); // sta is null!
    ...
    }
````

This happens because DOMVM uses the original `data` argument to invoke `init`, not the current `vm.data` value:

````
function ViewModel(view, data, key, opts) {
    ...

    var out = isPlainObj(view) ? view : view.call(vm, vm, data, key, opts);
    // vm.data is now {}

    ...

    // but this uses data arg, not vm.data
    vm.init && vm.init.call(vm, vm, data, key, opts);
}
````

The same argument could be used for key, which appears to be populated into `vm` before the view factory is called, and which might be overridden by it, particularly if the view's identity is self-realized.

I believe the `init` call should be:

    vm.init && vm.init.call(vm, vm, vm.data, vm.key, opts);

**Comment by leeoniya** [comment]
> I believe the init call should be: `vm.init && vm.init.call(vm, vm, vm.data, vm.key, opts);`

i made this change, though i must say that your use pattern is rather strange. `vm.data` is mostly an implementation detail. `data`'s purpose is specifically to inject external dependencies (eg from parent). as states in https://github.com/leeoniya/domvm/issues/151, i've reserved `vm.state` and `vm.api` for the purpose of maintaining externally-accessible view state and methods.

while you *could* use `data` to hold view state, you now have to know whether or not `data` and `vm.data` was internally-set state or externally set state on a per-component basis, which is a definite footgun IMO. i would stick to setting and using `vm.state` in your case.

**Comment by lawrence-dol** [comment]
How is it that all this time I've been mentally oblivious to `vm.state`. What you say makes perfect sense and I'll alter my code forthwith. I've been up for about 60 hours. Sorry!

**Comment by leeoniya** [comment]
no worries. get some sleep!
