### ISSUE TITLE
View Closure

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#16]
@yosbelms

I made a branch [1] to evaluate the benefit of eliminating the private view closure. It was surprisingly easy to convert thanks to the fact that templates nodes can be getter funcs. The tests only required a couple tweaks and for the benchmark tests it was just a matter of unwrapping the templates. You can see the diff yourself [2].

Ignore the infinite-scroll demo diff, it's all whitespace EOL. But actually this is the one I'd like to discuss. I did not convert this one because I think it exactly illustrates the benefits of having an architecture-provided predictable and logical init place & private closure.

The way it is set up now, you have the init closure, which has access to everything and it returns a renderer which will get called on every redraw to re-generate the template. It is extremely clear and uniform. While you save one layer in simple cases where there's not much init in the new branch, you now have to create your own init "factories" for other cases. I prefer to have a predictable place for init with everything clearly dependency-injected rather than returning a render function closed over who-knows-what. It seems like a bad pattern if there's any hope of having multiple people writing plugins whose structure is entirely free-form. React's and Mithril's ecosystems are healthy for a reason, and it's not because they offer absolute flexibility - quite the opposite, in fact.

If you re-structure the current infinite-scroll demo [3] for the closure-free view, don't you just end up re-creating what domvm already provides but less powerful ~~because you dont have access to the vm until things are rendered?~~. Technically you could init the vm imperatively with your render func and use it externally for `.hook()`, `.on()`, `.redraw()`, etc..

Try reworking it yourself, I'd like to see where you end up!

[1] https://github.com/leeoniya/domvm/tree/view-as-renderer
[2] https://github.com/leeoniya/domvm/commit/a6e7992e56033b5cd3ae138381d50e3d7f4667ed
[3] http://leeoniya.github.io/domvm/demos/infinite-scroll.html

**Comment by yosbelms** [comment]
> React's and Mithril's ecosystems are healthy for a reason, and it's not because they offer absolute flexibility - quite the opposite, in fact.

Totally agree, since domvm is still in early stages I think is good to play whith several architectures.

I always design libs/frameworks in two layers, *core api* and *facade api*. The *facade api* exposes an architecture which should be used in most of the cases. In the other hand, *core api* exposes raw functions and classes to be used in those cases were enterprise devs and/or hackers needs fine-grained api for specific requirements. Take this example requirement: "Run all the rendering process inside a WebWorker, then send the diff to the main thread to patch the dom", It could make a difference in the performance of any heavy rendering big app.

My point is that architecture should be separated from low level api, and both should be exposed. Hence, I may use just a plain template by low level api, or the closure using the documented architecture. In both cases it shoul be possible.

**Comment by leeoniya** [comment]
This sounds great in theory but has been demonstrated to incur a significant perf overhead to create a serializable "patch" in one step and perform the patching itself in another. I invite you to show me a vdom lib which accomodates a separate diff & patch which even approaches domvm or faster libs on dbmonster.

> It could make a difference in the performance of any heavy rendering big app.

You really need to qualify this statement with real world examples. are we talking 100k dom nodes mutating at 60fps? No lib on earth can do this, with or without Web Workers.

domvm already provides plenty of mechanisms to optimize perf. Isolated subview redraw, granular node patching, event delegation. People drool over React when it's slow as molasses - every dom diffing lib made in the last year blows it away.

domvm is not a low level vdom diff/patch lib. not sure how often i can say this :) it's meant to be practical and fast for 98% of cases, optimizable for 1.9% and simply the wrong solution for the remaining 0.1%. i do not plan to strip all opinions/structure enforcement out of domvm. in some cases it makes sense, like you suggested for the router, but in other cases you'll need to prove your point better.

until you show me the zen of removing the view scope/init and doing the same thing yourself anyways, i see no reason to flatten it just because the same thing could kinda be done in your own closure. you can start by reworking the infinite scroll demo.

i'm finishing up a domvm implementation of threaditjs which is helping me a great deal in balancing api tersness and module interop/boundaries. for the record, it is currently the fastest implementation among the other libs tested so far [1].

[1] http://threaditjs.com/

**Comment by leeoniya** [comment]
fittingly just popped up on HN: see 3 and 4:

http://programmingisterrible.com/post/139222674273/write-code-that-is-easy-to-delete-not-easy-to

discussion:

https://news.ycombinator.com/item?id=11093733

**Comment by yosbelms** [comment]
I am aware that to make a serializable patch is an overhead. I just mentioned a "scientific case" to back my point of separation. I know that diff/patch proccess is critical but the external layer of architecture is not so. Anyway I'm finishing the TodoMVC App I'm preparing to submit a PR to the examples. Once finished, I will rerwrite it using the new branch, then I will share my experience.

**Comment by leeoniya** [comment]
i think we're done here :D
