### ISSUE TITLE
DOMVM Doesn't Play Nice with Concatenation

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#163]
Just noticed this while investigating a (severe) memory leak in my app. DOMVM includes a "use strict"; outside of it's enclosure, and so makes all following scripts strict, even though they may not be written for it.

````
/* domvm.micro.min.js */
/*
 https://github.com/leeoniya/domvm (3.x-dev, micro)
*/
'use strict';(function(C,x){...
````

It should be:

````
/* domvm.micro.min.js */
/*
 https://github.com/leeoniya/domvm (3.x-dev, micro)
*/
(function(C,x){'use strict';...})(this,function(){'use strict';...});
````

**Comment by leeoniya** [comment]
huh, gotta see if rollup's umd wrapper or closure compiler puts it there. my guess is the latter.

**Comment by leeoniya** [comment]
okay, so this is a known closure compiler issue [1]. Rollup does in fact put "use strict" at the top of its umd wrapper and Closure removes it. Closure will then add it to the entire file if language_out=ECMASCRIPT5_STRICT (which it has been).

i guess we'll need to set the language_out to ECMASCRIPT5 and add a hack into the build script to shove it back in after minification. pretty sad to need a workaround for this, but not difficult to do.

[1] https://github.com/google/closure-compiler/issues/997

**Comment by lawrence-dol** [comment]
Looks like this will do it:

    --output_wrapper="(function(){'use strict';%OUTPUT%}).call(this)"

**Comment by leeoniya** [comment]
no, that'll re-wrap rollup's umd wrapper. which is not what we want. i already have a hack in the build script to undo Closure's aggressive inlining [1], so it's just a matter of adding an extra replace call there.

245f048fd25c739675768e0fc76a36159ef77492 should fix this,

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/build.js#L150
