### ISSUE TITLE
Syncing model property with DOM value.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#166]
@leeoniya

I've developed this function to keep a model property in sync with the DOM value; it takes a model object, property name and attribute name and sets up the value assignment and an `oninput` handler. It also allows the backing model property to be either a simple value or get/set wrapper. 

The thing I haven't catered for is having multiple handlers, which would allow application code can add `oninput` handling on top of this.

What do you think of it in the context of DOMVM?

```js
function modelSync(obj,prp,atr) {
    return { [atr]: modelValue(obj,prp), oninput: [modelUpdateHandler,obj,prp,atr] };
    }

function modelUpdateHandler(obj, prp, atr, evt) {
    modelValue(obj,prp,(evt && evt.target && evt.target[atr]));
    }

function modelValue(obj,prp,val) {
    if(obj[prp]==undefined) { throw new Error("Cannot find property '"+prp+"' in object",obj); }    // require defined property to help find coding errors
    return val==undefined
        ? genU.isFunction(obj[prp]) ? obj[prp]()    : obj[prp]
        : genU.isFunction(obj[prp]) ? obj[prp](val) : obj[prp]=val;
    }
```

**Comment by leeoniya** [comment]
yeah, this is similar to `withAttr` (and 1.x's `watch.sync()`).

i'm likely going to remove `domvm.prop()` [1] from mini+ builds very soon rather than documenting its existence at all; it's a completely self-contained util function similar to this. both of these belong in demos and/or a "useful snippets" wiki rather than the core, IMO.

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/utils.js#L130-L139

**Comment by lawrence-dol** [comment]
> i'm likely going to remove domvm.prop()

Agreed. I rolled my own back when working with Mithril because I had very specific requirements (such as backing with local-storage if desired). It's a great concept, that deserves to be highlighted as a utility, but I don't think it needs to be part of DOMVM either.

**Comment by lawrence-dol** [comment]
@leeoniya 

Question, would `oninput: [modelInputHandler,obj,prp,atr]` cause `obj` to be cloned in any way such that the argument passed to `modelInputHandler` would be `arg!==obj`?

I ask because in using the above construct, a different object, not my model is updated in the `oninput` handler, having proven that the model object is correct when the `oninput` array is returned. This causes my model to not be updated on input as expected.

In case the answer is "no", I'm putting a fiddle together now.

**Comment by leeoniya** [comment]
there is no cloning. it just passes the args through [1].

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/patchEvent.js#L45

**Comment by lawrence-dol** [comment]
> there is no cloning. it just passes the args through

Nevermind... it was me, buried in some library code.
