### ISSUE TITLE
Creating unrelated DOM elements interferes with redraw()

### ISSUE THREAD

**Issue by jlgrall** [leeoniya/domvm#170]
If you simply execute: `document.createElement("div");`, it will interfere with the next call to `redraw()`, even if they are completely unrelated and if the created element is not even inserted in the document.

Bug demo: https://jsfiddle.net/jlgrall/z31nrsuj/

**Comment by leeoniya** [comment]
this is simply a side-effect of how devmode's DOM instrumentor [1] works. it wraps the native dom functions with counters, so it'll measure all dom ops, not just domvm's dom ops. it's imperfect but it allows for some more granular things that MutationObservers cannot do.

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/addons/dominstr.js
