### ISSUE TITLE
[Discussion] Don't re-render view if stream wasn't changed

### ISSUE THREAD

**Issue by jlgrall** [leeoniya/domvm#171]
## Idea
If a view returns a stream, that means that until the stream changes, there is no way that it could return a different value.

So it should be possible to make domvm not call `render()` on the views that returned a stream on last `render()`, and which hasn't yet changed.

How it should work: https://jsfiddle.net/jlgrall/cmb3ubd2/

## Current state
I looked at the domvm stream source code and at the playground demo, and it seems that streams are only used to automatically trigger the `redraw()` on their vm. It is really nice because that means that we don't need to manage the calls to `redraw()` when the datas are updated. But I think that it could go further and use the full power of the streams. Because the streams can tell us when a view doesn't need to re-render itself.

## Use case
With this, if you just change 1 style property of an element that has a thousand of sub elements, then only that element's view will need to be re-rendered. That would be very quick, whereas for now, I would probably manage that property outside of domvm, directly changing the style of the element.

**Comment by leeoniya** [comment]
this use-case is covered by `node.patch()` [1], which would avoid re-generating & diffing the sub-tree. let me know if that's sufficient.

[1] http://leeoniya.github.io/domvm/demos/playground/#diff-patch

**Comment by leeoniya** [comment]
i've pondered this a bit more and i don't think i'll go with this for a couple reasons.

right now, streams are just read to get their values and dependent streams are created to trigger redraw. that is, there's no persistence of the streams themselves anywhere in domvm, and i'd like to keep it that way by leaving it up to the user and not sacrificing perf or bloating the lib with more API.

the issue you raise here is already neatly handled by `diff`, where you can return a list of values to diff for changes before a redraw occurs.

```js
// assuming data.name is a stream
const Child = {
  diff: (vm, data) => [data.name()],
  render: (vm, data) => el("h1", data.name),
}
```

this adds a bit of boilerplate here, but does what you're asking for. there's no reason you couldn't create a simple recursive function called from within `diff` that pulls any streams out of `data`, gets their values and returns them for comparison by domvm.
