### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#173]
continuation of #164...

**Comment by leeoniya** [comment]
after several hours of testing, i have some findings.

there does appear to be a problem with listeners leaking, perhaps due to the way the wrapping closure is created. adding `listener._raw = true` prevents the leaks, because the closure is not created, but also doesnt pass the arguments through, just the event. i'll be looking into changing the listener wrapper maybe via `Function.bind` to avoid this.

however, the listener leak is fairly minor, and is not related to the main Node buildup. the main contributor to Node buildup appears to simply be the dom complexity, and no lib i've tested so far is immune. let's takr the following example (no listeners):

```js
let el = domvm.defineElement;

let items = Array(1000).fill("Z");

function View(vm) {
  var editing = -1;

  return () =>
    el("div", [
      el("h2", ++editing),
      el("div", items.map((v,i) =>
        el("div", [
          editing == i
            ? el("input", { value: i, style: { width: "50%" }})
            : el("div", i),
        ])
      )),
    ]);
}

var vm = domvm.createView(View).mount(document.body);

var iter = 1000;

setTimeout(function() {
  var it = setInterval(function() {;
    vm.redraw();

    if (--iter == 0)
      clearInterval(it);
  }, 50)
}, 5000);
```

its graph looks like this:

![domvm](https://user-images.githubusercontent.com/43234/29242834-9b971992-7f59-11e7-8482-081da2f6d792.png)

if i simplify the template to remove `style` and the item-wrapping `div`:

```js
el("div", [
  el("h2", ++editing),
  el("div", items.map((v,i) =>
//  el("div", [
      editing == i
        ? el("input", { value: i })    //  style: { width: "50%" }
        : el("div", i),
//  ])
  )),
]);
```

the leak disappears entirely:

![domvm-simple](https://user-images.githubusercontent.com/43234/29242921-4af0c21c-7f5a-11e7-8e19-f4e46c436cbb.png)

if i only bring back the wrapping div, i get something in between:

![domvm-med](https://user-images.githubusercontent.com/43234/29243012-1403bcea-7f5b-11e7-9bc5-7089f11482b2.png)

mithril gets this:

```js
let items = Array(1000).fill("Z");

var editing = -1;

var View = {
  view: () =>
    m("div", [
      m("h2", ++editing),
      m("div", items.map((v,i) =>
        m("div", [
          editing == i
            ? m("input", { value: i, style: { width: "50%" }})
            : m("div", i),
        ])
      )),
    ])
};

m.mount(document.body, View)

var iter = 1000;

setTimeout(function() {
  var it = setInterval(function() {;
    m.redraw();

    if (--iter == 0)
      clearInterval(it);
  }, 50)
}, 5000);
```
![mithril](https://user-images.githubusercontent.com/43234/29243154-078e2be6-7f5e-11e7-890c-c13c99e3ffc5.png)

and ivi gets this:

```js
import { render } from "ivi";
import * as h from "ivi-html";

var items = Array(1000).fill("Z");
var editing = -1;

function update(items) {
  render(
    h.div().children(
      h.h2().children(++editing),
      h.div().children(items.map((v, i) =>
        h.div().children(
          editing == i
            ? h.inputText().props({ value: i }).style({ width: "50%" })
            : h.div().children(i),
        ))
      )),
    document.body
  );
}

update(items);

var iter = 1000;

setTimeout(function() {
  var i = 0;

  var it = setInterval(function() {;
    update(items);

    if (iter-- == 0)
      clearInterval(it);
  }, 50);
}, 5000);
```

![ivi](https://user-images.githubusercontent.com/43234/29243165-4a7b947a-7f5e-11e7-9726-2dbe1df10f41.png)

i consider ivi to be very well written. it is extremely fast and very explicit in its templates. you can see that it's measurably faster than both mithril and domvm. yet, it too, suffers from the node buildup in a dom tree that isnt all that complex.

i dont think there's anything more i can do to improve the situation since the entire heap is now properly GC'd. the GC is very sensitive to many factors, including available RAM. memory pressure, cpu & available frame budget. i suspect that overall live dom size is a major contributor to GC sluggishness, since my contrived test behaved well (since the dom size dropped to near-0 at some iterations.)

**Comment by lawrence-dol** [comment]
Using my [original fiddle](https://jsfiddle.net/LawrenceDol/oL27ewow/): In Chrome the listeners are now flat and the and nodes grow slowly; In Firefox there's no visible evidence of a leak in Windows Task manager, which probably means the node leak is not fast enough to register without a lot of activity.

![image](https://user-images.githubusercontent.com/8662551/29291632-11968236-80f9-11e7-9734-0df383073fa1.png)

Using my app the results are much the same, except with the more complex DOM the leaking nodes are noticeable in the overall browser memory consumption. After a minute or two scrolling down the translations, it'd grown by about 20 or 30 MiB.

![image](https://user-images.githubusercontent.com/8662551/29292150-e62a4518-80fa-11e7-8697-4ffe0c344a01.png)

**Comment by iamjohnlong** [comment]
Here are my results running this https://jsfiddle.net/392vkyp6/1/

![screen shot 2017-08-14 at 3 25 53 pm](https://user-images.githubusercontent.com/306104/29292655-2658cfe2-8105-11e7-990d-dd455c7caf03.png)

**Comment by lawrence-dol** [comment]
Using my [second fiddle](https://jsfiddle.net/LawrenceDol/rwq2cbyb/), which puts a wrapped listener on the input field, it still seems to leak listeners at the same rates as nodes:

![image](https://user-images.githubusercontent.com/8662551/29292705-004d5e92-80fd-11e7-83d6-483bf08c00fa.png)

**Comment by lawrence-dol** [comment]
Using @iamjohnlong's fiddle, if I add a wrapped listener, the results are interesting. But, in the end, it seems consistent with @leeoniya's observation that DOM complexity affects this.

![image](https://user-images.githubusercontent.com/8662551/29292899-cc0014bc-80fd-11e7-9898-afddd7571d10.png)

**Comment by iamjohnlong** [comment]
@lawrence-dol do you manually click in the fields to test that? or is just rendering the page the test?

**Comment by lawrence-dol** [comment]
@iamjohnlong If you are referring to my fiddle, I click in the first field and then hold down the DownArrow key for about 30 seconds. The fiddle is based on the UI I created for editing translations. Simply rendering is not enough; it's the updates to the DOM that cause leaking.

**Comment by iamjohnlong** [comment]
@ok, I'll try and reproduce what you're doing and post the results.

**Comment by iamjohnlong** [comment]
results of this https://jsfiddle.net/LawrenceDol/rwq2cbyb/

![screen shot 2017-08-14 at 3 45 34 pm](https://user-images.githubusercontent.com/306104/29293272-ca5cef0e-8107-11e7-9b88-299b109488d9.png)

**Comment by leeoniya** [comment]
i'm not seeing any listener leaks either. @lawrence-dol can you try it outside jsfiddle?

![no-leak](https://user-images.githubusercontent.com/43234/29293701-95c74406-8111-11e7-8e88-f57066b4fead.png)

**Comment by lawrence-dol** [comment]
I copied and pasted all the fiddle code into a single HTML page and ran it from localhost, with the same results:

![image](https://user-images.githubusercontent.com/8662551/29294156-d6688240-8102-11e7-89e7-aadb39796867.png)

Checking my Chrome version, it's `Version 60.0.3112.90 (Official Build) (64-bit)`, but an update was just downloaded, so I'll try it again.

**Comment by iamjohnlong** [comment]
ran that code locally.
<img width="642" alt="screen shot 2017-08-14 at 4 24 27 pm" src="https://user-images.githubusercontent.com/306104/29294560-31c7f846-810d-11e7-8b31-cbe698793afb.png">

**Comment by leeoniya** [comment]
i also ran the above on another machine (copy/paste) and could not get the handlers to leak. are you certain that rawgitcdn isnt serving *you* an old cached version?

**Comment by lawrence-dol** [comment]
@leeoniya : Ha! It would appear you are correct. Chrome was using an old version. After forcibly refreshing (and verifying that what I got was different and appeared to correspond to your changes), I have a flat listener line:

![image](https://user-images.githubusercontent.com/8662551/29295119-94d52cca-8107-11e7-8de5-78edd5bf2130.png)

Same for my standalone test page.

**Comment by leeoniya** [comment]
alright, cool.

i think i've had quite enough mem profiling in the past week to hold me over for the next 6 months :D. i don't think there's much more domvm can do to improve the node buildup, as it affects other libs to at least an equal degree. any remaining leaks will have to be handled in userland and maintaining good dom size hygiene.
