### ISSUE TITLE
[RFC] event handler changes

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#174]
while working on eliminating the event listener mem leak in #173, i had a thought.

setting `._raw = true` on event handlers to avoid domvm's wrapper is a bit awkward. what if instead, events defined by a function were left entirely alone. so, `onchange: myFn` would only receive `event`. events that would receive the full argument list `...args, e, vnode, vm, data` would be ones defined by array-wrapped functions: `onchange: [myFn]`.

one implication of this would be that any vm-level and global `onevent` callbacks would only be triggered for wrapped event handlers, but not native/bare handlers.

this is a minor BC, so i'd cut a 3.1.0 release.

cc @lawrence-dol

**Comment by lawrence-dol** [comment]
I think that's a good idea. Nothing quickly comes to mind as to why that would be undesirable. And I don't think it creates an illogical difference.

**Comment by leeoniya** [comment]
@lawrence-dol i've pushed commit that implements these changes, and also should solve the event memleak. can you test it out?
