### ISSUE TITLE
try domvm

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#175]
hey @creationix,

i noticed your comment [1] and wanted to see if you'd like to try out domvm. you may remember that i actually came from Mithril to your https://github.com/creationix/domchanger library [2]. then used both as inspiration for writing domvm.

domvm is spiritually close to domchanger in API (v1 also used JSONML) and does not have built-in routing, ajax, promises, streams, or global auto-redraw - it's just a view layer.

cheers!

[1] https://github.com/MithrilJS/mithril.js/issues/1886#issuecomment-323184646
[2] https://github.com/creationix/domchanger/issues/5

**Comment by leeoniya** [comment]
cc @andraaspar

i saw your lifecycle/redraw convo in Mithril. domvm supports isolated redraw and take a look at [1] and [2], perhaps you'll find domvm's hooks more agreeable, too.

[1] http://leeoniya.github.io/domvm/demos/playground/#lifecycle-hooks
[2] https://github.com/leeoniya/domvm#lifecycle-hooks

**Comment by andraaspar** [comment]
@leeoniya Thanks, I have looked at the docs, and tried out the playground. Feedback:

1. `el` vs `vw` & can't see component classes: I assume this will be difficult to hook up with JSX.
2. I actually like not having to call `redraw` after each event handler.
3. It's hard to translate a Mithril problem to domvm, but:
    1. A component needs to alter the model in a lifecycle hook.
    2. The model may be used to render other components outside the one that altered the model, hence the entire UI needs to be redrawn.
    3. We are in midst of a redraw sequence, in a lifecycle event. We initiate a redraw for the entire UI.
    4. What will happen? Will a new redraw sequence start immediately? Will redraw sequences be nested? Or will the redraw mechanism wait for all lifecycle calls to finish before starting a new redraw sequence? That's what my PR to Mithril was about. How does that work with domvm?

**Comment by leeoniya** [comment]
1. i'm not sure why a JSX hookup would be hard. there's no universal `h`, but that'd just be a wrapper around a switch/case that creates explicit vnode types anyhow. there are some other things that would need to be adapted, but no showstoppers. JSX is much more limited than domvm's factories, so you may lose quite a bit of power by introducing a JSX layer.
2. explicit redraw from events can be avoided at either the global level or per-view level: https://github.com/leeoniya/domvm#autoredraw

> What will happen? Will a new redraw sequence start immediately? Will redraw sequences be nested? Or will the redraw mechanism wait for all lifecycle calls to finish before starting a new redraw sequence? That's what my PR to Mithril was about. How does that work with domvm?

domvm does not have a redraw queue. redraws are async as a side-effect being rAF-debounced per-view, but you can call them synchronously if needed via `vm.redraw(true)`. there's no reason why you can't call a redraw from a lifecycle hook, though there's nothing that'll prevent you from triggering an infinite redraw->hook->redraw loop, given the proper conditions.

**Comment by andraaspar** [comment]
1. OK, one more helper to write.
2. Sweet! I missed that somehow.

> domvm does not have a redraw queue

My issue exactly. I'm still thinking that templates should be static. I should be able to tell which lifecycle is going to follow which one. If renders get nested, it's all messed up.

Lifecycle methods populate part of my model. I need to keep track of what is rendered and what is not, so that I know it is ready to be refreshed from the server. (It was hidden and now it is rendered, so the user expects it to be freshly populated.) That system is messed up by nested lifecycle events.

Also, I find it very important to render stuff correctly for the first time the user sees it. I cannot have flashes of intermediate / old data.

It's difficult. I use workarounds, but a queue in the virtual DOM engine seems like such a simple thing. I don't know why noone does that.

**Comment by leeoniya** [comment]
virtual-dom engines are reactive to the data you feed them. if you set `data.hidden = true; vm.redraw();` then you will get the appropriate dom without any flashes of old data. if i'm not mistaken, what you seem to be trying to accomplish is the inverse - have the view fetch the data and mutate the model, which will then re-refresh the view afterwards. this type of flow is quite difficult to reason about and i doubt many vdom engines can or want to accommodate it.

do you have a concrete example of when this pattern would be better than a top-down data->render approach?

**Comment by andraaspar** [comment]
Maybe I'll just fork my own then! ;)

I have lots, including the one I described above. But for a more obvious one: you're rendering SVG and you need to measure the size of text to draw something at the correct size / position. Or, you actually want to initiate an action when something appears. Scheduling a redraw before the next frame does not sound evil to me.

**Comment by leeoniya** [comment]
> But for a more obvious one: you're rendering SVG and you need to measure the size of text to draw something at the correct size / position.

https://jsfiddle.net/83kg80qf/

**Comment by lawrence-dol** [comment]
@andraaspar :

> *will the redraw mechanism wait for all lifecycle calls to finish before starting a new redraw sequence?*

It's pretty trivial to debounce redraws to the event queue:

````
function viewUpdater(vm) {
    let pending=false;
    return function() {
        if(!pending) {
            pending=true;
            setTimeout(function() {
                pending=false;
                if(vm.render) { vm.redraw(true); }                                                  // ignore redraws before view is actualized
                },0);
            }
        }
    }
````

**Comment by andraaspar** [comment]
@lawrence-dol `setTimeout` allows a frame to be drawn, so the redraw is not immediate. Please see [this Mithril example](https://jsfiddle.net/andraaspar/e5jbaeoz/1/) for the effect I'm trying to avoid.

**Comment by iamjohnlong** [comment]
@andraaspar https://jsfiddle.net/jc90m7cy/

**Comment by lawrence-dol** [comment]
@andraaspar : 

Then, I think, the standard redraw, which debounces with RAF should do the trick.

**Comment by lawrence-dol** [comment]
@andraaspar 

Looking at the example, and drawing on the context you've given here, specifically, "*It was hidden and now it is rendered, so the user expects it to be freshly populated*"...

This seems to me like a standard UI/UX problem in web programming. You want to show "hidden" data, using data fresh from the host when the user clicks "show". But you have an essential disparity: the reveal action is to all intents instantaneous, and the data fetch is necessarily async and requires an indeterminate amount of time. 

This need is nothing specific to DOMVM, Mithril, or any other way that one builds web apps. In essence, what you want to do, logically, is defer the rendering of the data portion of the view until the data is fetched, leaving it blank while the data is pending.

However, if the network is slow, this will suffer from a UX problem of "nothing happened when I clicked!!" if the network response is not nearly instantaneous; the common solution is to display some sort of "throbber" while the network request is pending. This can cause a flicker of the throbber in the normal case if the network is usually fast, in which case it's pretty easy to defer the display of the throbber for a few hundred ms; however I prefer just to have an identically sized icon for the show, throbber and hide actions, so the flicker is not noticeable. You also may elect to render in such a way that only the "show" icon is changed until the data fetch completes.

I apologize if I am stating the obvious, but to do this:

  1. Set the model data in a way that the the View renders a throbber in place of the "show" icon and blank for the data part of the view.
  2. Initiate the request and trigger a redraw.
  3. When the request completes update the model and trigger a redraw.
  4. View redraws now showing a "hide" icon and the data view.

Am I missing some detail?
