### ISSUE TITLE
Custom elements?

### ISSUE THREAD

**Issue by kokujin** [leeoniya/domvm#180]
Is it possible to create custom elements? I did not find any mention of this in the docs. 

The following does not work.

JS
`````
 var customTag = document.getElementsByTagName('my-widget');
     var data = { name: "Denver" };
     domvm.createView(HelloView, data).mount(customTag);
`````

HTML
`````
  <my-widget></my-widget>
`````

Thanks.

**Comment by leeoniya** [comment]
hey @kokujin 

browser support for Custom Elements is extremely limited today [1], so using them in any realistic way requires massive and slow polyfills, which erases the performance benefit you gain from using vdom libraries. in general, i'm in the camp that feels like custom elements & web components are solving an already-solved problem (components, isolation), and they still require JS. you can read some discussions here [2] [3]. scoped css is the remaining bit missing from what can already easily be done without tooling or special syntax.

i would be interested to hear a good argument for adding support for Custom Elements, though current browser support makes any such effort not worthwhile IMO.

[1] http://caniuse.com/#search=Custom%20Elements
[2] https://news.ycombinator.com/item?id=12993718
[3] https://news.ycombinator.com/item?id=13877289

**Comment by leeoniya** [comment]
ah, you're not talking about "Custom Elements". lemme take another look.

**Comment by leeoniya** [comment]
it works fine: https://jsfiddle.net/ogum2r08/

your example uses `getElementsByTagName` which returns a collection. you have to select a specific item in that collection to mount into:

```js
var customTag = document.getElementsByTagName('my-widget'),
    data = { name: "Denver" };

domvm.createView(HelloView, data).mount(customTag[0]);
```

**Comment by kokujin** [comment]
Thanks @leeoniya, that works, but I noticed that I could no re-use my custom element because it really isnt one. The code above just uses DomVm to manipulate the selected DOM element. How does one:

-  Reuse elements
- Access data attributes

using DomVm?

**Comment by leeoniya** [comment]
i'm not sure that i understand what you're trying to do. domvm is not made to manipulate already-created elements. perhaps you're trying to insert an already-created element into a domvm tree? you can do this with https://github.com/leeoniya/domvm#injectelement

could provide a more descriptive example?

**Comment by kokujin** [comment]
I meant something like this:

`````
 <my-widget data-city="Denver" data-lat="" data-lng=""></my-widget>
`````
I would like to render the element based on the attributes , "data-city, data-lat and data-lng" for example,

**Comment by leeoniya** [comment]
domvm does not "absorb" existing html. you have to create the entire widget: https://jsfiddle.net/0vj8ao9a/

the `data-*` attributes don't mean anything to domvm. the `data` is simply whatever you pass into the view.
