### ISSUE TITLE
Event pub/sub between components? 

### ISSUE THREAD

**Issue by kokujin** [leeoniya/domvm#181]
given 2 components:

`````
function View1(vm) {
         return function() {
             return el("div", "View 1");
         };
     }
function View2(vm) {
         return function() {
             return el("div", "View 2");
         };
     }

     // VM 1
     var vm1 = domvm.createView(View1);
     vm1.config({
         onemit: {
             myEvent: function() {
                 console.log('VM 1 reporting');
             }
         }
     });

     // VM 2
     var vm2 = domvm.createView(View2);
     vm2.config({
         onemit: {
             myEvent: function() {
                 console.log('VM 2 reporting');
             }
         }
     });
  vm1.mount(document.body);
  vm2.mount(document.body);
 
 vm1.emit("myEvent"); // Not a global event
`````
How can I make one component, in this example , vm1, broadcast an event that all subscribed components would react to? Thanks

**Comment by kokujin** [comment]
I saw this in the docs, what would be the correct signature then?

`````
onevent: {}
`````

**Comment by leeoniya** [comment]
the emit system bubbles up within the same view tree (similar to native dom events). if you need a global pub/sub it's easy enough to DIY or BYO - there are plenty to pick from.

in general i'm not a fan of pub/sub or multiple subscribers since it makes tge system less predictable because order of registration matters (and is often out of your control) and dictates the order of execution. this makes things quite fragile. it's also why domvm does not support multiple event handlers for the same event type on the same node. you can read more about this here: https://github.com/leeoniya/domvm/issues/177

the way for components to "communicate" is through a shared state that both have access to.

**Comment by kokujin** [comment]
Ok @leeoniya , I would have to implement my own messaging bus then. There still something that I don't understand

`````
var vm2 = domvm.createView(View2);
     vm2.config({
         onemit: {
             myEvent: function() {
                 console.log('VM 2 emitting');
             }
         },
         onevent: function(e, node, vm, data, args) {
             console.log('VM 2 reporting');

         }
     });
     vm2.mount(document.body);

     vm2.emit("myEvent");
 ````
" console.log('VM 2 emitting');"  works as expected, but the "onevent" callback is never triggered, can you point me to a code example using this? Thanks

**Comment by leeoniya** [comment]
> Ok @leeoniya , I would have to implement my own messaging bus then.

the one caveat with this is possible memory leaks when holding onto vm instances if you subscribe but forget to unsubscribe them. also, if you use eg `didMount` and `didUnmount` lifecycle hooks to auto-register/deregister subscribers into a global bus, you may run into perf concerns with huge component counts. i dunno if you were only planning on doing this selectively, but certainly something to keep in mind.

`onemit` is for emit events
`onevent` is for dom events and will fire for any *fancy* listeners: https://github.com/leeoniya/domvm#event-listeners

**Comment by leeoniya** [comment]
@kokujin 

here's a pub/sub implementation that should be leak-free (except the roots, which should be quite manageable). it works by walking the full vtree during `pub()` calls and invoking anything that matches the registered event names under `vm.subs`. this design prevents and dynamic registration/unregistration that's mount-dependent.

https://jsfiddle.net/3gr1cmfh/

**Comment by kokujin** [comment]
Great @leeoniya, I will try your code out asap. Actually, I have tried out a very simple way to maintain state and pub/ sub events using [baoba](https://github.com/Yomguithereal/baobab).

**Comment by leeoniya** [comment]
i prefer the smaller [Freezer](https://github.com/arqex/freezer) ;)
