### ISSUE TITLE
vnode.el._node is undefined in alreadyAdopted

### ISSUE THREAD

**Issue by tropperstyle** [leeoniya/domvm#182]
<img width="843" alt="screen shot 2017-11-10 at 3 08 19 pm" src="https://user-images.githubusercontent.com/28314/32682474-bb02b982-c629-11e7-871c-dbda68d3cfc4.png">

`setType` triggers a root redraw. Not sure if I am triggering a race condition in domvm or if it is something I need to adjust in user land.

**Comment by leeoniya** [comment]
this is gonna be impossible for me to debug without seeing the bigger picture.

unless you're hacking on domvm's internals or directly moving/detaching dom nodes, it's not something that should happen when using the documented APIs.

`alreadyAdopted()` tests whether a dom element linked to an old vnode has already been re-linked (recycled) to a new vnode. this is done as part of the old vtree -> vtree diffing/recycling loop that tries to match up old vnodes to new vnodes and patch them.

hopefully that helps. if not, then i'll need a testcase.

**Comment by tropperstyle** [comment]
Here is a minimal test case:

https://jsfiddle.net/thbsq9sk/

The first time toggle is clicked, ViewB is not appropriately being inserted. A subsequent toggle will throw an error. Though the stack trace is different, this is the exact behavior I am seeing with the original stack trace.

**Comment by leeoniya** [comment]
thanks, looking into it.

**Comment by leeoniya** [comment]
the test case is fixed. let me know if this fixes the original issue.

**Comment by leeoniya** [comment]
sounds like it's trying to unmount an already unmounted vm. why this would happen intermittently on continuous toggles is a mystery.

**Comment by tropperstyle** [comment]
It's not intermittent anymore. In the main app, if initialized with "B", toggling to "A" causes the missing dom element then toggling back to "B" throws the exception as seen [here](https://jsfiddle.net/thbsq9sk/2/)

With your latest commit, If the app is initialized with "A", I can freely toggle back and forth between "B" and "A" without issue. Before this commit, both starting points were problematic.

The error is no longer being thrown in `alreadyAdopted` as seen in the screenshot but in `_removeChild` as in the jsfiddle

**Comment by leeoniya** [comment]
not sure what i'm missing here. i dont see a fiddle that throws anywhere anymore :/

**Comment by tropperstyle** [comment]
From the first part of that same comment:

https://jsfiddle.net/thbsq9sk/2/

**Comment by leeoniya** [comment]
that fiddle does not load for me because you cannot load js files straight from github, they are served with an incorrect mime type. plus the domvm version 908195cfbbc48a2652e23a8fe17e922cd8458e92 is before the latest commit.

is there still an issue after the latest commit?: https://jsfiddle.net/thbsq9sk/4/

**Comment by tropperstyle** [comment]
The fiddle loads fine in Safari. For Chrome and Firefox, need to update the URL to use rawgit to see the exception in `_removeChild`

Prior to your commit I was experiencing the original screenshot error on every toggle. After the commit, I now experience the `_removeChild` error in my main app (trace similar to the fiddle using a version prior to the commit) but only if initialized with screen "B". From here, toggling to "A" removes the dom node, then toggling back to "B" throws the exception.

> If the app is initialized with "A", I can freely toggle back and forth between "B" and "A" without issue.

Does that help?

**Comment by leeoniya** [comment]
ok, so even though the latest commit fixes the `_removeChild` issue in this fiddle, your app still suffers from a problem that is now clearly this one....whereas before it was suffering from it by proxy and showing up in `alreadyAdopted`.

maybe you have nesting of injected vms and the error happens deeper in the tree, i dunno...

i guess you know what i'm gonna say. make another failing fiddle :)

**Comment by leeoniya** [comment]
`ARRAY_FLATTENED` is fired by the template preprocessor and is mostly a possible optimization warning. it shouldnt have any effect.

it sounds like the B view is getting unmounted, but not actually removed from the dom. if you look at the condition that fires `FOREIGN_ELEMENT`, you see that it's the result of `._node` having been cleared off the element during an unmount but the element still being in the dom during the next redraw.

https://github.com/leeoniya/domvm/blob/0e1c915842dfa5f3e7bc332075b036edcbf31e17/src/view/syncChildren.js#L103-L109

**Comment by tropperstyle** [comment]
> it shouldnt have any effect

Right, I only pointed it out because ViewA never makes it into the dom, but thought it have been useful to know that at least this part of the code ran.

> it sounds like the B view is getting unmounted, but not actually removed from the dom.

But it is removed. After the first toggle `div.view-a` and `div.view-b` are missing just as in the original fiddle.

**Comment by leeoniya** [comment]
any progress on a repro?

**Comment by tropperstyle** [comment]
Still unable to get it reproduced in the isolated environment, but here is what I found so far:

https://jsfiddle.net/thbsq9sk/6/

In the real app ViewA and ViewB are very different. I ending up keying the parent `div.screen` to fix my issue. But without `_key`:

Setting a breakpoint here:
https://github.com/leeoniya/domvm/blob/0e1c915842dfa5f3e7bc332075b036edcbf31e17/src/view/syncChildren.js#L121

If launched with ViewB active, when toggling to ViewA:

`lftNode` is ViewA and `lftNode.el` === `<div class="view-a"/>`

If launched with ViewA active, when toggling to ViewB:

`lftNode` is ViewB and `lftNode.el` === `null`

Then following `insertBefore` line then gets hit and the app works as expected.

**Comment by leeoniya** [comment]
`lftNode.el` should be null; i don't quite understand where ViewA is getting hydrated with dom nodes (after the fix).

`createView()` just calls `new ViewModel(...)`. Nothing in the short ViewModel constructor [1] calls `render()`,`redraw()`,`update()`,`mount()` to hydrate or even generate an initial vtree.

It sounds like you're doing something after ViewA init that causes it to hydrate that view too early. Possible a stray redraw() call that ends up here [1].

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/ViewModel.js#L21-L52

[2] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/ViewModel.js#L273

**Comment by tropperstyle** [comment]
Thanks for the insight! You nailed it.

ViewA and ViewB are "singletons" and initialized immediately, with the only other references as the `injectView` calls in the root view.

When my app mounts, it reads a cookie and fires ajax request to login the current user. But ViewA listens for this event and was calling `vm.redraw()` without a guard.

```javascript
// view-a.js
function ViewA(vm) {
  vm.state = {
    loading: false
  };

  vm.api = {
    refresh() {
      vm.state.loading = true;
      vm.redraw();
      // fire async request
    }
  };

  EVENTS.on('login', vm.api.refresh);
}
export default domvm.createView(ViewA);
```

Would `if (vm.node.el)` be the appropriate thing to check against?

**Comment by leeoniya** [comment]
> Would `if (vm.node.el)` be the appropriate thing to check against?

yeah, that should work fine as an isMounted test. but...that's shit DX so i've added 2 patches.

the first is a devmode warning if a prematurely hydrated vm ever reaches `syncChildren()` and fucks up subview mounting.

the second ensures that any userland `update()` or `redraw()` calls only create a vtree but never hydrate.

with these changes you should not need additional guards.

**Comment by leeoniya** [comment]
v3.2.3 with these patches is tagged.

thanks for the report!
