### ISSUE TITLE
How to use browser-prefixed css property names in camelCase styling? (eg. -moz, -webkit)

### ISSUE THREAD

**Issue by Paul-Lategan** [leeoniya/domvm#185]
http://leeoniya.github.io/domvm/#templates

In the docs, there's the option to define styles as a camelCase object:

> el("p", {style: {fontSize: "10pt"}}, "Hello")          // or an object (camelCase only)

<hr>

For example, the CSS property : value of:
`box-shadow : "0px 4px 15px 2px rgba(0,0,0,0.35)"`

becomes:

`boxShadow : "0px 4px 15px 2px rgba(0,0,0,0.35)"`

This works well.

<hr>
How does this work with browser-prefixed classes, such as "-webkit" or "-moz"?

I've tried:

`-webkit-box-shadow : "0px 4px 15px 2px rgba(0,0,0,0.35)"`

as :

`webkitBoxShadow : "0px 4px 15px 2px rgba(0,0,0,0.35)"`

but this doesn't appear to work.

**Comment by lawrence-dol** [comment]
Can you not just quote the key?

    "-webkit-box-shadow" : "0px 4px 15px 2px rgba(0,0,0,0.35)"

**Comment by leeoniya** [comment]
@lawrence-dol no it sets them as `el.style.*` properties.

@Paul-Lategan 

domvm doesnt handle this, but you can make a simple helper for yourself that iterates your css objects and passes them through a prefixing lib such as:

https://github.com/LeaVerou/prefixfree
https://github.com/anseki/cssprefix

```js
`{style: css({boxShadow: ...})}`
```

or whatever :)

**Comment by Paul-Lategan** [comment]
@lawrence-dol @leeoniya  
That works, thanks for the quick reply!

**Comment by leeoniya** [comment]
i added these libs to the readme: https://github.com/leeoniya/domvm#what-domvm-is-not
