### ISSUE TITLE
Nunjucks or mustache templates?

### ISSUE THREAD

**Issue by kokujin** [leeoniya/domvm#188]
Is there a way to use Nunjucks or Mustache for templates instead of Hyperscript? It may be much easier than trying to get rid of the warnings about arrays being flattened. Thanks

**Comment by leeoniya** [comment]
if your main issue is the warnings, you can silence them as shown in the docs [1], they're just performance suggestions and will not cause any app errors (or even impact perf that significantly).

as for whether you can use Nunjucks or Mustache, you would have to provide a compiler layer that would translate them into hyperscript. this would be possible if your mustache or nunjucks parser exposes the AST and/or API to do this translation. you can also take a look at a simple JSX adapter in https://github.com/leeoniya/domvm/issues/179

generally, domvm's hyperscript api provides a richer featureset than can be exposed in more restricted templating languages.

[1] https://github.com/leeoniya/domvm#devmode

**Comment by kokujin** [comment]
Thanks @leeoniya, I will try out one of the micro builds then. About it's usage, I just replace the instances of arrays with el() declarations?

**Comment by leeoniya** [comment]
i think the example given is pretty clear. you can provide children as additional arguments without having to wrap them in an array,
