### ISSUE TITLE
Stream documentation

### ISSUE THREAD

**Issue by explorigin** [leeoniya/domvm#189]
Streams are a powerful feature that only have implicit documentation.  It took me some time to figure out that:
- a stream must make up the entire element body, not passed as an array
- a stream is incompatible with defineElementSpread

**Comment by leeoniya** [comment]
good point. i suppose most of the stream "documentation" in the demo [1]. would that have helped?

> not passed as an array

do you mean cannot be an element in a body array? e.g. `el("div", [myStream])`

> is incompatible with defineElementSpread

that's more or less restating the same thing, right?

[1] http://leeoniya.github.io/domvm/demos/playground/#streams

**Comment by explorigin** [comment]
I did see the demo and that got me started.

> do you mean cannot be an element in a body array? e.g. el("div", [myStream])

Correct

> that's more or less restating the same thing, right?

Yes, but it's not so obvious to those who haven't read the code (which is the point of documentation).  I chose to mention it here for other readers that may also try to implement streams with domvm.

**Comment by leeoniya** [comment]
now that you've gone through the pain of reading the sample code, would you be interested in distilling this into a PR to add to the docs?

**Comment by leeoniya** [comment]
https://github.com/leeoniya/domvm/issues/171#issuecomment-351119738
