### ISSUE TITLE
How to use vm.attach for SSR

### ISSUE THREAD

**Issue by foxdonut** [leeoniya/domvm#192]
@leeoniya greetings!

I am trying to use `vm.attach` for SSR but I am getting the following error:

```
attach.js:22 Uncaught TypeError: Cannot set property '_node' of null
```

Which is in this area of the code:

```js
function attach(vnode, withEl) {
	vnode.el = withEl;
	withEl._node = vnode;
```

I have reproduced the issue with what I hope is a relatively minimal code snippet. The initial HTML within the target element is what the server would have returned. Then I use `vm.attach` to hydrate on the client as per [the documentation](http://leeoniya.github.io/domvm/#isomorphism--ssr).

[Code snippet on codepen is here](https://codepen.io/foxdonut/pen/qVezWz?editors=1010).

What am I doing wrong?

Thank you for your help!

**Comment by leeoniya** [comment]
i'm on a phone ATM but my initial thought is the prettified html. domvm uses `.childNodes` to hydrate the existing dom, which means any whitespace such as tabs and indentation becomes significant. try removing all whitespace between the html tags.

**Comment by foxdonut** [comment]
@leeoniya you're right, that helped!

Now, I get one step further: when I try to do `vm.update(model)`, I get `Uncaught TypeError: Cannot read property '_node' of null` on `patch.js`:

```js
function alreadyAdopted(vnode) {
	return vnode.el._node.parent !== vnode.parent;
}
```

Appreciating your help.

**Comment by leeoniya** [comment]
you should be attaching to the top-level node *that's managed by domvm*. the app's root node is not `#app` but the div inside of it. again, speculation cause on phone.

**Comment by leeoniya** [comment]
actually there's another issue here. each view must have its own dom node (render must return an `el()`). you cannot transparently wrap views in other views as you're doing in the top level AppView.

i may implement this in the future (after fragment support, which is currently WIP)

**Comment by foxdonut** [comment]
@leeoniya getting closer. I've update [the example](https://codepen.io/foxdonut/pen/qVezWz?editors=1010) to attach to the top-level node that is managed by domvm, as you have helpfully instructed.

As for your second comment, I'm not sure what I'm doing wrong. I'm not really wrapping views in other views here; functions like `FilterableProductTableView`, `SearchBarView`, and `ProductTableView` do return an `el()` directly -- perhaps my naming them with the `View` suffix is misleading and not a good naming convention given what a View is in domvm.

Also note that this example works fine without the SSR/attach, that is when using `mount`.

I must be missing something else to get this example to work, any further ideas?

Thanks again for all your help.

**Comment by foxdonut** [comment]
@leeoniya I finally got [my example](https://codepen.io/foxdonut/pen/qVezWz) to work. What I had to change was, instead of rendering `el("tbody", [])` when there were no rows, render nothing at all (`null`).

That is, instead of `el("tbody", rows)`, replace with `rows.length > 0 ? el("tbody", rows) : null`.

Thanks for your help, I appreciate your quick replies!

**Comment by leeoniya** [comment]
huh, interesting. i should do some investigation. i believe i recall some weirdness about the DOM and implicit tbody insertion. at the very least we can document this and/or have a DEVMODE warning

**Comment by foxdonut** [comment]
Cool. Might want to document the importance of whitespace, and which node to attach to, for SSR.

**Comment by leeoniya** [comment]
so it looks like `<tbody>` will always be implicitly inserted *at html parse time*. but if you create the dom via js, it never gets parsed, so there's no `<tbody>`. use devtools to inspect the doms of both tables to witness the madness: https://jsfiddle.net/0qun7yxv/

it should be easy to add a DEVMODE warning to `attach()` by inspecting whether `<table>` vnodes contain any direct `<tr>` descendants in the vtree. i'll add this notice to the docs as well, and clarify that `attach()` must be provided with the root dom element of the corresponding view.

**Comment by foxdonut** [comment]
Excellent! Thanks @leeoniya

**Comment by leeoniya** [comment]
@foxdonut i looked at your example again (on a bigger screen this time).

turns out there was actually a bug in `attach()`!

if you have html `<tbody></tbody>` and `el("tbody", [])`, then domvm tries to traverse the DOM even if the array was empty. this is what was causing your error, sorry.

i added a length check into `attach()` and you can remove that silliness from your code (you'll still need to add the explicit empty `<tbody>` into your html).

if you swap domvm in your codepen to the latest dev version, you should be able to do `el("tbody", [])` without errors. i'll be publishing v3.2.5 later today with this fix.

thanks for the report, lots of birds killed with this one!

[1] https://rawgit.com/leeoniya/domvm/3.x-dev/dist/dev/domvm.dev.min.js

**Comment by foxdonut** [comment]
@leeoniya good to hear that this exercise resulted in something useful!

I tried the link you posted, but unfortunately using `el("tbody", rows)` instead of `rows.length > 0 ? el("tbody", rows) : null` in my [updated example](https://codepen.io/foxdonut/pen/qVezWz?editors=1010) still leads to an error.

**Comment by leeoniya** [comment]
because you're still missing `<tbody></tbody>` in your markup. an empty child array doesnt mean you can skip rendering the parent.

**Comment by foxdonut** [comment]
ah - got it, thanks! :+1:
