### ISSUE TITLE
Very Performant Without Using vDOM?

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#196]
What do you make of the claims of https://radi.js.org/ that bypassing vDOM and doing direct DOM manipulations can be more performant, with less memory use, and less GC pressure than using vDOM?

**Comment by leeoniya** [comment]
non-vdom libraries do tend to use less memory, though not drastically so compared to good vdom implementations. you can easily see which ones do not in the memory metrics here [1]. of those, only `attodom-v0.5.2-keyed` comes close to being as fast as vdom impls. is suspect svelte will also get there when/if they resolve the large regressions they introduced in the latest version. meanwhile, `choo-v6.5.0-keyed` is massively slow, despite having great memory use. preact also does not use a vdom and diffs to the actual dom, but its implementation is is no better than vdom libs - the same may be true of some other libs in there. also, part of attodom's speed comes from doing direct dom manipulation [2], so it cheats a bit to get those numbers.

radi does have an attempt at the js-framework-benchmark here [3] but when i tried to run it i got massive cpu usage and cannot profile the actual perf numbers. probably a bug in the lib or impl, i don't know. its api looks similar to `hyperapp 1.0`. radi's tests and examples are incredibly inadequate. it's also 4.13kb, not 3kb ;)

there have been plenty of claims that avoiding a vdom leads to less complexity, more perf and less mem usage. the only claim that has consistently held up (in the best impls) is the last one and usually at a significant cost to perf. until there's a conforming non-buggy `js-framework-benchmark` implementation of radi, the claims ring pretty hollow to me.

[1] https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html
[2] https://github.com/krausest/js-framework-benchmark/blob/master/attodom-v0.5.2-keyed/src/create-row.js#L21
[3] https://github.com/radi-js/radi/blob/master/examples/large-data.html
