### ISSUE TITLE
[eval] possible event handler changes, delegation

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#2]
currently event handlers are bound via

```js
["p", {onclick: function(e) {...}}]
// or delegated
["p", {onclick: [".moo", function(e) {...}]}]
```

some limitations with this are

1. cannot bind multiple handlers for same event type, though this seems like something to best avoided anyways so that people don't learn to rely on bind-order and `e.stopImmediatePropagation()` & friends
2. delegated handlers are also limited to one. this is more problematic as you can choose to respond with different handlers in different cases.

one way to fix 2) is to simply leave delegation up to the user - it's easy to just run `e.target.matches(sel)` within the handler.

another option is to allow an object with selector keys

```js
{
    "td": function(e) {...},
    ".moo": function(e) {...},
}
```
this seems like the best option to replace the array syntax for delegation. need to evaluate performance implications of diffing another struct, though we can maybe assume these never change contents and just `===`

**Comment by lawrence-dol** [comment]
I instinctively like the selector keys approach. But my understanding of the problem-space is still limited. It does seem to introduce a problem of conflicting matches -- a problem that CSS solved abysmally.

**Comment by leeoniya** [comment]
the key-selector syntax is already implemented in the codebase, btw. i could probably close this.
