### ISSUE TITLE
PR Submission

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#22]
@yosbelms

I appreciate your help, but if you'd like to make a change to the lib, please open an issue to discuss it first before writing code and submitting a PR with docs and everything. Especially in the beginning while you may not understand fully why things are the way they are. Some changes affect uniformity of the rest of the lib that you're not touching, others cannot be done in isolation without rethinking other parts of the whole. It will save you time in writing and me time in reviewing.

**Comment by yosbelms** [comment]
Ok I will change the flow if it makes you more comfortable, I will open issues referencing commits or branches from my fork.

**Comment by leeoniya** [comment]
thanks!
