### ISSUE TITLE
move domvm.config to domvm.view.config

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#23]
now that the lib is modular,  things like `domvm.config({useRaf: false})` are a bit of a misnomer especially since rAF-debouncing is used in multiple modules but mostly hinders debugging/timing in the `view` module for debounced/coalesced redraw.

on the other hand having a config for each module is rather tedious but perhaps preferable to long-ass-but-clear key names in a global config e.g. `routerUseRaf`

needs some pondering...

**Comment by lawrence-dol** [comment]
My two very quick thoughts on this...
      
      Having config-per-module is the right way to go.
      
      Or having a single structured config using router.useRaf, etc.
        Even if it's only logically structured, like git where it's
        physically bi-level but logically n-level.
      
      
        -- 
        Lawrence Dol
        http://think.dolhub.com | http://tech.dolhub.com
      
       
    
      
      From: Github Notification
        Sent: 2016-02-19 10:40:03
        To: Leeoniya/domvm
        Subject: [domvm] move domvm.config to domvm.view.config
        (#23)
      
    
    
      now that the lib is modular, things like domvm.config({useRaf:
          false}) are a bit of a misnomer especially since
        rAF-debouncing is used in multiple modules but mostly hinders
        debugging/timing in the view module for
        debounced/coalesced redraw.
      on the other hand having a config for each module is rather
        tedious but perhaps preferable to long-ass-but-clear key names
        in a global config e.g. routerUseRaf
      needs some pondering...
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by leeoniya** [comment]
> Having config-per-module is the right way to go.

I'm in this camp as well.

**Comment by leeoniya** [comment]
done
