### ISSUE TITLE
extending the vm in app-space

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#26]
@lawrence-dol
@yosbelms

While I want to keep the lib core small, I don't want to enforce sometimes-lengthy-but-uniform ergonomics [1] [2] onto users. I'm thinking of adding a simple global hook that would extend every vm, kinda like `Object.create` or `.prototype.myMethod`.

Example:

```js
domvm.view.extend(function(vm) {
	// node locator
	vm.up = function findNodeAbove(filter) {
		....
	};
	
	// short version to get dom elems
	vm.el = function getDomRef(refName) {
		return vm.refs[refName].el;
	};
	
	// bala dom ref wrapper (https://github.com/finom/bala)
	vm.$ = function getDomRef(refName) {
		return $(vm.el(refName));
	};
});
```
The user will have to be careful not to clobber native methods and understand that any extend would need to be vetted against all domvm version upgrades since collisions may occur as the vm's native API could expand.

This could also serve as a vetting ground for useful future additions to the vm core.

[1] `vm.refs.myRef.el` (dom element)
[2] `vm.redraw(someHugeNum)` (redraw root)

**Comment by lawrence-dol** [comment]
I need to think about this when I am back in the vDOM space in my brain. I generally far and away favor composition over extension, so I would have no problem writing functions that inject `vm`, e.g. `dvm.up(vm,...)`, where dvm is my own module of DOMVM utilities.

One thing I dislike about monkey-patching, ahem, extending like this, is that it's impossible to know from the code you're reading whether it's a DOMVM function or a grafted function, and, if so, from whence it came. If I *were* to use it, I'd likely pick a single-character

In general, then, this capability wouldn't affect me one way or the other, so if it were really, really cheap in terms of size, sure.

**Comment by leeoniya** [comment]
I'm not a huge fan of doing it this way either but if you have a lot of views it becomes boilerplate to always DIY compose. This is a quick method to get terse syntax auto-added to all vms which cannot be done another way. I don't want to go full-imperative and suggest that users create and provide vm-factories to created instances of domvm. You can always create your own 1-char namespace to reduce collisions, `vm.u.*` or just compose yourself as you suggested.

In the docs it would make sense to heavily discourage the use of `extend` within components you intend to share with others and to limit its use to your own codebase.

> so if it were really, really cheap in terms of size

With an optional reset that can blow away foreign extends...

```js
var exts = [];

domvm.view.extend = function(ext, reset) {
    reset && (exts.length = 0);
    exts.push(ext);
};

function extVm(vm) {
    for (var i = 0; i < exts.length; i++)
        exts[i](vm)
    return vm;
}
```

And 3 or 4 places...

```js
return vm;
// switch to
return extVm(vm);
```

Performance overhead would be negligible.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/domvm/commit/1785c4acd5a7278bb8fb6c1e38eb0095372b5d3b

Ended up being even less code: +79 bytes min. Certainly much less than it will save users vs ad-hoc composition of each vm.

**Comment by lawrence-dol** [comment]
This mechanism is cool. I set mine up with a conflict check that you might useful to others (docs example):

````
// Add auto-redraw and auto-prop functions
domvm.view.extend(function(cvm) {
    dvm.extendCpt(cvm,"aRedraw",domvm.watch(function() { cvm.redraw(); }));                               // mutation observer to reduce app.cvm.redraw() boilerplate
    dvm.extendCpt(cvm,"aProp",cvm.aRedraw.prop);
    })

function extendCvm(cvm,nam,val) {
    if(cvm[nam]!=undefined) { throw "Conflict: Cannot extend view-model with `"+nam+"` -- already defined"; }
    cvm[nam]=val;
    }
````
