### ISSUE TITLE
impCtx has gone away

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#29]
PSA: `impCtx` and its step-cousin `vm.imp` are dead! Long live a mixed `model` and explicit `handle`!

The new view signature is:

```js
domvm.view(viewFn, model, handle, opts);
```

`handle` is the replacement for `key` and is the sole definer of how views behave between redraws. It dictates whether a view will be reused or will re-init and destroy state and whether the DOM will be recycled or removed and re-created.

Specifying an `array`, `object`, `function`, `string` or `number` will use that value to compare the `viewFn+handle` pairs between old and new vtrees to determine the persistence and reuse of vms and the DOM across redraws.

Specifying `undefined` or `null` is equivalent to setting `handle` to the `model` itself.

Specifying `false` opts the view out of persistence assumptions and will cause the vm and DOM to be reused even when the model is completely replaced between redraws. This is useful for rendering re-fetched re-decoded JSON data structures.

I will write more about this in the docs and provide samples later.

For the time being it is still called `key`. I'm hestient to rename it to `handle` since the post-1.0 plan is for full congruence between vm and the vm's root node, so I don't want to change `_key` to `_handle` in the node props.

@lawrence-dol

**Comment by kdar** [comment]
Instead of having the view signature change with every API change, would it be better just to have two parameters: the viewFn and then options? Then you can have the model and handle in there too.

**Comment by leeoniya** [comment]
@kdar 

Sorry about this, I should note at the top of the readme that domvm is pre-1.0 and unstable until 4/1.

The signature for View is now stable, though: `(viewFn, model, key/handle, opts)`..precisely because of prior WTF constructs like `domvm.view(viewFn, null, null, null, etc...)`.

The `key/handle` defaults to `model` if it is `null` or `undefined`:

`domvm.view(MyView, model)` === `domvm.view(MyView, model, model)`

in effect, `impCtx` is now arg 2 if a persistent model is provided as arg 3:

`domvm.view(MyView, impCtx, model/key/handle)`

The interplay is fairly subtle and i'm still working out how to clearly document it, since it's important to understand. I wanted to stay with more concise sigs instead of having generic opts with `model:` and `key:`

**Comment by lawrence-dol** [comment]
> `handle` is the replacement for `key` and is the sole definer of how views behave between redraws. It dictates whether a view will be reused or will re-init and destroy state and whether the DOM will be recycled or removed and re-created.

Is this still current? How does the `handle` argument it relate to the special property `_key`? Is the latter applied internally and given the value of `handle`?

**Comment by leeoniya** [comment]
the sig is basically `viewFn, data, persistentThing`

where `peristentThing` (or hande/key/whatever) defaults to `data`  when undefined or null. You can explicitly opt out of persistence by providing `false` for `persistentThing`. it can be a string or numeric key as well.

in the demos you may encounter

`viewFn, model` (persistent model, same as `viewFn, model, model`)

`viewFn, data, model` (persistent model with `data` as a dep injection container)

`viewFn, data, false` (prevents data from being treated as persistent)

`viewFn, data, key` (uses specific key as the persistent thing)

it looks like a lot of confusing options but once you understand the concept i does make sense. this is for sure the hardest concept to grasp in the lib.

**Comment by leeoniya** [comment]
to answer your question, lol, _key has the same effect on nodes as a persistent handle has on views.

**Comment by leeoniya** [comment]
at one point any _key on the root node of a view also became the handle of the view itself if no handle was provided by the parent. i dont remember if this is still the case, will have to look. this is unlikely to afffect normal use either way.

**Comment by lawrence-dol** [comment]
> to answer your question, lol, _key has the same effect on nodes as a persistent handle has on views.

Ahhhh! [light comes on].

Thanks.

**Comment by leeoniya** [comment]
@lawrence-dol 

It appears that i have inadvertently lied to you a bit. There is a in fact a difference between `_key` on nodes and `handle/key` on views. It comes down to the fact that Views are considered stateful and expect persistent models (unless handle is opted out via `false`), but nodes are stateless, dumb and more reusable (less guarantees of state not incidentally being retained due to dom recycling).

So, `move` behavior is the same in both cases. Reordering of a view (with handle) or node with a `_key` will detach and re-insert their doms.

However, `remove` differs. If a view's model disappears but an identical view with a new model is created in its place, the old dom will get destroyed and recreated - it will *not* be recycled to ensure that any state is killed off. For _key-nodes which get replaced with different _key-nodes, the dom *does* get recycled. This affects which lifecyclcle hooks get called also. `will/didInsert` and `will/didRemove` for instance will not run during node reuse, but `will/didReuse` will. Sometimes this behavior seems counter-intuitive especially when setting up animations (and perhaps it should be altered).

`false` handle views (essentially "pure"/stateless views with swappable models), behave the same as nodes if their models change, their dom will get recycled. In essence they act as independently refreshable and stateful "slots" for dumb data.

An excellent way to sanity-check what's going on is to use the provided `DOMInstr` [1] instrumentation lib which will show you exactly what DOM ops domvm does when your data changes and you call `vm.redraw()` (also `vm.update(newModel)` for `false`-handle views).

I've put together a collection of comparisons which may help you get some insight into what happens in each case: https://jsfiddle.net/ey9q9611/

Understanding this behavior is sometimes necessary to avoid surprises, which is not a good thing. I'd like to revisit the presumption of model/handle persistence and perhaps always require explicit keying. Then the explanation would be much simpler: dom will always be reused unless views and nodes have explicit key/handle, in which case dom will always be destroyed/e-created. But there are performance implications to consider. In most apps/demos I've written so far, assuming persistence has been useful, and recycling the dom non-uniformly has allowed for some speed gains.

[1] https://github.com/leeoniya/domvm/blob/master/test/lib/dominstr.js

**Comment by leeoniya** [comment]
TBH, I can't come up with a situation when a `_key` node would be preferable to using a keyed sub-view. It's a hold-over from the old days when views were less powerful and dynamic form element attrs/props were un-synced. There is some use for it internally, but I would advise against using it. It should be telling that not a single demo or bench actually uses this anymore. 

I will probably remove it from the docs before 1.0. Consider it deprecated as far as a public API.

**Comment by leeoniya** [comment]
This was bugging me. `_key` is actually still useful if you want to force specific lifecycle hooks to fire, which becomes important when relying on them to do in/out animations as in #32.

I just pushed a commit that makes the recycle uniform between nodes's _key and view's (handle/model/key). If the key or handle disappears between redraws, the dom will no longer be recycled for use in siblings. There may be a switch added post-1,0 to enable this behavior, but it makes sense for things to be uniform and easily understandable.

The only remaining difference is that _key cannot be an object while a view's key/handle/model can be. There is little remaining in the way of getting to full congruence here, but it's not super critical and will happen post 1.0. I will open a separate todo issue for landing this.

**Comment by lawrence-dol** [comment]
Thanks. I appreciate symmetry in an API; it helps avoid violations of expectations.

**Comment by leeoniya** [comment]
this topic is already on to docs todo. closing this. may reference later.
