### ISSUE TITLE
domvm architecture braindump

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#3]
this is a continuation of #1 as it was getting too long to scroll.

**Comment by leeoniya** [comment]
There's an unpleasant situation in the current api that I'd like to address WRT to "dumb models". Dumb models are plain objects or arrays (lets say json-decoded data) that contain no methods and no "fluent" api.

In the previous thread, i made this list:

A. Model data/state (json from server, etc)
B. Model API, addl state (provided by "hydrating" or wrapping model data, fluent methods)
C. ViewModel, provides a view into one or more models (provides view api & state)
D. Templates (declarative dom structure)
E. DOM

Currently, `domvm` can render dumb models (A) without issues. However, since they expose no domain apis (B), it is awkward to link any event handlers or view apis to domain apis, since none are provided by the model or imported in any way...and the user has to rely on closures/globals. This is baaaad.

The solution is rather simple/elegant. Support optionally importing an object of domain methods and/or state into the vm scope so we can invoke them as needed. **This removes the urge to implement/lock domain methods inside the vm.** We can call it an imported domain `controller`, since that's kinda what it is - a curated collection of external methods needed by the view and not provided by a hydrated "smart"/"fluent" model instance.

Without bloating the current vm init signature `(viewFn, model, _key, rendArgs)` for an optional feature, I propose having a special-case model that provides both the data and the imported domain methods, storage providers, etc:

```js
// plain data model
var dumbModel = {name: "Foo", age: 12};

// special-case structure that provided both the model and external apis/hooks
var smarterModel = {
  data: dumbModel,
  ctrl: {
    saveToServer: (data) {
      // ... do whatever
    }
  }
}

// the view
function ModelView(vm, smarterModel ) {
  var data= smarterModel.data;
  var ctrl = smarterModel.ctrl;

  return {
    render: function() {
      return ["button", {onclick: function(e) { ctrl.saveToServer(data) }}];
    }
  };
};

domvm(ModelView, smarterModel).mount(document.body);
```

Here's the before and after of the infinite scroll example:

Before: https://jsfiddle.net/rhtaxkvL/4/
After: https://jsfiddle.net/rhtaxkvL/7/

It's clear that the second is a huge improvement WRT separation of concerns. The view-related state and methods are not cleanly separated from the domain methods with an explicit import for triggering item fetching in the domain.

**Comment by leeoniya** [comment]
@barneycarroll

So a reasonable question to ask, is: "If domvm isn't a component framework, then what does a component written on top of domvm look like?" The answer to that is, it looks like any other domain model with fluent methods. `domvm` does not enforce that a component be a single or several adjacent nodes in a view tree. You are free to structure things that way if you want, but your component can expose multiple, disjoint views that the consumer can arrange as they see fit. This brings us back to your initial confusion with why you may want to enclose the view definition inside of the model - because this is the *component* model.

As an example, let's say that we want to make a NavMenu component that accepts a json sitemap, the current active page key and exposes multiple views: TopNav, SideNav, FootNav. Then it is consumed by a parent component. I will not go through the full implementation here but just the basic API/structure.

```js
// site component
function MyApp(opts) {
	this.nav = new NavMenu(opts.sitemap, opts.currPage);
	
	// root view
	function MyAppView(vm, myApp) {
		return {
			render: () => ["#myApp", [
				["#header", [
					["h1", "Welcome To My Site!!"],
					myApp.nav.topNav,
				]],
				myApp.nav.sideNav,
				["#content", "Lorem Ipsum"],
				["#footer", [
					myApp.nav.footNav,
					["div", "Footer Crap"],
				]],
			]]
		}
	}
	
	this.vm = domvm(MyAppView, this);
}

// nav component with multiple exposed views
function NavMenu(sitemap, currPage) {
	this.sitemap = sitemap;
	
	// renderers for disjoint sub-views
	function TopNavView() { return {render: () => {}} }
	function SideNavView() { return {render: () => {}} }
	function FootNavView() { return {render: () => {}} }
	
	// exposed vms
	this.topNav = domvm(TopNavView, this);
	this.sideNav = domvm(SideNavView, this);
	this.footNav = domvm(FootNavView, this);
	
	this.goto(currPage);
}

// NavMenu api that can be invoked by internal sub-views
// from click handlers or externally by other consumers
NavMenu.prototype = {
	goto: function(currPage) {
		this.currPage = currPage;
		this.redrawAll();
	},
	redrawAll: function() {
		this.topNav.redraw();
		this.sideNav.redraw();
		this.footNav.redraw();
	}
}

var opts = {
	sitemap: {},			// some sitemap tree
	currpage: "home",
}

var app = new MyApp(opts);
app.vm.mount(document.body);
```

With this structure, you can call `app.nav.redrawAll()` which will only redraw the disjoint top, side and foot sub-views. Alternatively, you can instead call `app.vm.redraw()` which will redraw everything.

> WRT 'outgoing animations', might I suggest the onunload method allow the user to return either undefined (meaning they are simply using the hook to execute arbitrary teardown side-effects for state management) or a thennable, at which point DOMVM defers DOM patching to the resolution? I think this would be a more robust, flexible and simple implementation than providing a timer — which would mean duplication of animation logic at best (possibility for author error at worst), and would fit nicely with animation libraries that provide a resolution hook which — thereby authors are free to perform logic for variable or unspecified duration in their animations.

Yes, this is what i was thinking to do initially. But as I pointed out, while it is flexible, it is not automatically robust. Because if `redraw()` is invoked from elsewhere before the teardown promise is resolved, you end up with a undefined behavior as the internal vdom no longer matches the real DOM. For it to be robust, there needs to be some sort of locking implementation that queues up any redraws within the branch/tree until that promise is resolved (if ever!). You're putting the control of the dom cleanup (which is critical for diffing correctness) entirely in the hands of the user who is responsible for resolving the promise and also do nothing that affects the tree before then. If anything, it is very fragile. The way to lock and queue other ops is also not very obvious to me but it is not something that is trivial. By returning a delay or passing in a `delay()` function that can be invoked I do not give the end user full control over promise resolution, therefore while i cannot guarantee that nothing has happened to the tree during animation, i can at least guarantee that the dom cleanup is always performed after the timeout, making it significantly more robust than putting full control in the hands of the user.

**Comment by leeoniya** [comment]
There's an unpleasant situation in the current api that I'd like to address WRT to "dumb models". Dumb models are plain objects or arrays (lets say json-decoded data) that contain no methods and no "fluent" api.

In the previous thread, i made this list:

A. Model data/state (json from server, etc)
B. Model API, addl state (provided by "hydrating" or wrapping model data, fluent methods)
C. ViewModel, provides a view into one or more models (provides view api & state)
D. Templates (declarative dom structure)
E. DOM

Currently, `domvm` can render dumb models (A) without issues. However, since they expose no domain apis (B), it is awkward to link any event handlers or view apis to domain apis, since none are provided by the model or imported in any way...and the user has to rely on closures/globals. This is baaaad.

The solution is rather simple/elegant. Support optionally importing an object of domain methods and/or state into the vm scope so we can invoke them as needed. **This removes the urge to implement/lock domain methods inside the vm.** We can call it an imported domain `controller`, since that's kinda what it is - a curated collection of external methods needed by the view and not provided by a hydrated "smart"/"fluent" model instance.

Without bloating the current vm init signature `(viewFn, model, _key, rendArgs)` for an optional feature, I propose (and have implemented 5f0af78b2aa10e3669de9ac179ed618c5655169d & 5eef9aa88b0517a97add44f0b573b34820eff6c9) having a special-case model that provides both the data and the imported domain methods, storage providers, etc:

```js
// plain data model
var dumbModel = {name: "Foo", age: 12};

// special-case structure that provides both
// the model and external apis/hooks
var smarterModel = {
  model: dumbModel,
  ctrl: {
    saveToServer: function(data) {
      // ... do whatever
    }
  }
};

// the view
function ModelView(vm, smarterModel ) {
  var data= smarterModel.model;
  var ctrl = smarterModel.ctrl;

  return {
    render: function() {
      return ["button", {onclick: function(e) { ctrl.saveToServer(data) }}];
    }
  };
}

domvm(ModelView, smarterModel).mount(document.body);
```

Here's the before and after of the infinite scroll example:

Before: https://jsfiddle.net/rhtaxkvL/4/
After: https://jsfiddle.net/rhtaxkvL/9/

It's clear that the second version is a huge improvement WRT separation of concerns. The view-related state and methods are now cleanly separated from the domain methods with an explicit import for triggering item fetching in the domain.

**Comment by sprat** [comment]
Continuing the discussion started in https://github.com/sprat/domned/issues/1... I've not read the whole thread here and the previous one, but I'll do that very soon.

I prefer a hyperscript function because I just find it more readable and composable. But as you stated, it has probably an impact on performance. For small apps, I don't really care, so I'd like to write something like that:
```javascript
h.a('Click here').click(function () { /* ... */ });
// or
h.a('Click here').on('click', function () { /* ... */ });
```
I would be a kind of builder pattern. For sure, I can implement it on top of domvm nodes, better keep domvm simple.

About npm/node compatibility: it's probably ok, it's just a matter of:
- generating a ``package.json`` file via ``npm init``
- setting the ``index`` field in ``package.json``, so that it can be imported by other npm packages
- uploading a release on npm when everything is ready. Meanwhile, we can use the github link to express the dependency to domvm for our own packages.

**Comment by leeoniya** [comment]
@sprat if you're reading, you may also want to look at the ongoing discussion here: https://github.com/trueadm/inferno/commit/134a90005cc8a3900bd601666dd1aa474c0abb6f as a few things have changed since the #1 and some of the jsfiddle examples there might be broken in subtle ways.

I don't think I said anything about a performance overhead. I just said that in my initial testing i was not able to get any performance benefit, though in theory there should have been one (see the discussion in the Inferno commit). I'm still investigating whether it's worth to have Hyperscript or a verbose object def instead of JSONML as the core template structure. There are trade-offs in different areas for each option. Everyone has their opinion how to curry/chain hyperscript and while there is some IDE benefit, I'd rather opt for concise, very minifiable templates by default (they're very easy to understand and dont have a million signatures like jquery).

Threre's more to Node/npm than just publishing. I'm almost certain domvm will not work out of the box without some tweaks. I need to figure out which dependencies (if any) are needed and where they can be avoided. There are existing and ever-expanding Qunit tests that I would want to fully pass and integrated to track regressions as well as automatic Closure compiler minification. If you are familiar with any of these aspects, I would welcome your help as long as you carefully vet what's missing, needed and not just slap together 500MB of devDependencies that can be avoided. If you would like to uncover and report bugs and write more tests, that would also be great :)

I will spend this evening opening a bunch of different discussion points on various to-be-implemented features and todo items.

**Comment by sprat** [comment]
About packaging/deployment: I'm not saying it's ready to release! Just that creating a package.json file is necessary to start using it npm-based/browserified builds. I'll then report problems if I encounter any. As you say, you/we must probably also run the unit tests and generate the minified build via some npm scripts. If you look at my domned library, you'll see that I personally don't like the gulp/grunt approach, I prefer using regular npm scripts for "building" my apps/libraries. See http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/ for the rationale. I think it fits your point of view too - the "no build step" approach. You just have to minify the source file to generate the minified build!

**Comment by sprat** [comment]
About the hyperscript function:

I evaluated many virtual-DOM implementation before and I've noticed that no a single implementation use the same hyperscript function as another. Their API is probably just a matter of taste. That's why I don't think it should be implemented in the core of domvm. Either it could be an aside feature provided by domvm, or you may let the user of the library implement their own. However, if someone want to implement his own hyperscript function on top of domvm (my case), it should be something relatively easy to do. In my case, as I want to implement a kind of builder pattern, it would probably easier to do if the core domvm structure was an object instead of an array. But that's possible nevertheless.

In my experience with the Nagare python framework, we often build HTML incrementally. I mean, we create a node, then add children in for loops or add attributes depending on some conditions. In python, we have a `with` construct that creates an inner context. This construct can be used in Nagare when building nodes . So we can write nested python code that ressemble their HTML counterpart. This feature requires a "builder" approach. That's probably why I am biased towards this approach for building vdom nodes. For sure, there are always other ways to write that kind of stuff: use Array's `map` and `filter`, use "boolean" attributes, etc. It just a matter of taste / code readability / expressiveness concern.

**Comment by sprat** [comment]
About dumb models:

Why not just let people wrap their dumb model into smart models themselves instead of implementing a special-case in domvm? I've probably missed something...

In fact, that's exactly what we do at my company: we wrap our dumb data objects in smart models and use these smart models as components with views. These smart models may know how to load/save the data to the database, how to process the underlying data... so it add some value on top of the dumb data.

When building an application, it's often hard to decide up-front what are the responsibilities of the component we are building. At first, the component is often dumb. Then you add processing methods. Then persistence: so you extract the data in a data object and deal with load/save. Finally you decide you need an abstraction and you're passing data into the component and delegate things to a parent component... In my opinion, the view library has nothing to do with this, so each case should be handled the same way by the library.

**Comment by leeoniya** [comment]
the main reason for special casing is that the wrapping can happen at runtime and the wrapper object can get recreated during each redraw, so i cannot diff the nodes using oldModel === newModel, meaning keys would always be required.

**Comment by leeoniya** [comment]
if your models are completely recreated anyways like from json on every redraw, then you're right and it wouldnt matter and keys would be needed regardless, but i think that case is less common than having persistent models after initial creation.

**Comment by leeoniya** [comment]
but i guess i can just say if you create wrappers they must be stateful. however, that may screw up template ergonomics sonce now your wrapper creation must live outside of `render()` and in the parent view's closure/state.

perhaps this is an okay disclaimer. i personally dont like the special case either but it does bring with it a level of consistency since "vm.ctx" is exported api/state and dep-injected {ctx: ..., model: ...} is imported scope/state.

**Comment by leeoniya** [comment]
i was actually considering moving all the `vm` native functions under `vm._.*` and leaving the rest available to expose whatever api you wanted, instead of having it under `vm.ctx.*` but then `vm._.redraw()` and `vm._.mount()` etc become clumsy :(

**Comment by sprat** [comment]
I need to figure out how (and what) you do the dirty checking, but I meant doing something like that for smart wrappers around dumb data:

```javascript
function SmartWrapper() {
    this.data = this.loadJSON();
    this.view = [SmartWrapperView, this];
}

// called by the view in response to an action
SmartWrapper.prototype.processData = function (value) {
    this.data.someValue = value;
}

SmartWrapper.prototype.loadJSON = function () {
    // load JSON from server...
    return {};
};
```

**Comment by sprat** [comment]
And in general, when we have view state, we tend to wrap our business-related components into UI components, with the UI view(s) eventually calling the business-related component view(s). You use the view closure for that, we use regular objects instead, but it's probably equally fine.

**Comment by sprat** [comment]
As for you last comment:

I plan to create a "View" concept doing whatever is needed around the component's render function, including wrapping the vm object into my hyperscript function before calling the component's render function. At least, that's how I've done that in the other libraries I tried. So, no need to change the vm API.

**Comment by leeoniya** [comment]
take a look at #6 in the meantime. i'll respond in a bit...

**Comment by leeoniya** [comment]
as you said, there is no requirement to use the vm's closure or to expose any api. if you have more monolithic ui/business objects then you can do exactly as ypur example and have your model hold both view state and domain state. you could also "export" any functions that need to interact with the template or ev handlers by just setting them on the model dorectly from the view closure.

your coupling can be as tight as you want. but i wanted to leave the freedom for maximum decoupling if needed.

**Comment by leeoniya** [comment]
> I need to figure out how (and what) you do the dirty checking

there is no dirty checking. when you do `vm.redraw()`, render is called in that view and all sub-views to regenerate the template in full, then the dom is patched using the prior vtree for full diff. the only thing i do is to ensure the vms are persisted by matching up `oldViewFn === newViewFn  && oldModel === newModel ` within the same parent branch.

**Comment by leeoniya** [comment]
@sprat
more patterns in the wiki also: https://github.com/leeoniya/domvm/wiki/View-Model-Patterns

**Comment by cloudspeech** [comment]
The infinite-scroll examples are all broken at the moment. Would love to see corrected versions.

**Comment by leeoniya** [comment]
sry about that. here you go.

https://jsfiddle.net/rhtaxkvL/14/

**Comment by leeoniya** [comment]
Short story, `splModel` is gone, it was too weird. Long story, I'm gonna write up a wiki page about distinction between `model` (which are used for diff in the absence of a key) vs `impCtx` (additional dependency injection).

`impCtx` can be updated imperatively during any redraw via `vm.redraw(newImpCtx)` or from a parent tpl via `[SubView, model, key, newImpCtx]`. In both these cases, the `impCtx` is replaces the prior `vm.imp` and is also passed into the returned view's `render(impCtx)` func as the only arg.

**Comment by leeoniya** [comment]
here's a more optimized version that doesn't recreate the onscroll handler on every scroll event and only recalcs the loadLine when loading more:

https://jsfiddle.net/rhtaxkvL/15/

**Comment by leeoniya** [comment]
@cloudspeech

I've published the router and split the lib into a few modules. The API has changed slightly.

`domvm()` is now `domvm.view()`

`vm.html()` is now `domvm.html(vm.node)`

Since I cannot commit to keeping all the jsfiddles up to date (and also because i cannot change already published fiddles), please refer to the infinite-scroll demo here: https://github.com/leeoniya/domvm/blob/master/demos/infinite-scroll.html

it's also available on `gh-pages`: https://leeoniya.github.io/domvm/demos/infinite-scroll.html

**Comment by yosbelms** [comment]
Actually we do:
```js
//Function -> Function -> Template
function PersonView(vm, person) {
    return function(){
        return ['div', person.name]
    }
}

domvm.view(Person, person)
```
Why not:
```js
//Function -> Template
function PersonView(vm, person) {
    return ['div', person.name]
}

domvm.view(Person, person)
```
I understand the benefits of the private scope enforced by the current architecture, but it can be easily resolved with second architecture example by doing:
```js
function PersonViewFactory(person) {
    // privated scope
    return function PersonView(vm, person) {
        return ["div", person.name]
    }
}

// create a view with private scope
var PersonView = PersonViewFactory(person);
domvm.view(PersonView)

// alternatinelly
domvm.view(PersonViewFactory(person))
```
The actual private scope enforcement is not necesary, I think.

**Comment by leeoniya** [comment]
@yosbelms

Then the `vm` is not available in the private scope until a render happens (and you expose it) which means you cannot set up `vm.on()` listeners or `vm.hook()` for lifecycle events, or do other view config ahead of initial render. So it serves more than just enforcing a private scope.

In your example `PersonView` takes on the role of `.render()` that is invoked on every redraw. The private closure is the init which is meant to accept stateful args (the "component" signature") whereas the render is a stateless template generator which relies on closured state from the private scope. `render()` can accept new data as args declaratively or passed through via `vm.redraw()` calls.

domvm is not a raw vdom lib where you simply have a render func and some data you pass to it. I understand and appreciate the simplicity of those libs but that's one level lower than domvm aims. There you're 100% in charge of the structure as well as related boilerplate for vdom patching, etc. Libs like snabbdom, kivi, vidom and many others already fill that space nicely.

With ES6 arrow funcs, the sig much nicer:

```js
function PersonView(vm, person) {
	return () => ["div", person.name];
}
```

**Comment by leeoniya** [comment]
https://github.com/leeoniya/domvm/issues/3#issuecomment-176264616 above, discusses how `.render()`'s args and purpose differs conceptually from those of the private scope closure. I understand you want just the stateless `render()` without the closure to write a bit less code but I don't see that happening in domvm.

Keep in mind that you can have your stateless/scopeless render funcs if you don't need granular redraw control. In fact, most of my apps work exactly this way. There is only enforced scope when you need to make an independently redrawable sub-view or you need to expose an api to specific branch.

For example, you could do this to keep your template functions pure and even external

```js
var tplPerson= (person) =>
	["div",
		["strong", person.name],
		" has pets...",
		tplPets(person.pets),
	];

var tplPets = (pets) =>
	["ul", pets.map(pet =>
		["li", pet.name]
	)];

function PersonView(vm, model, key, impCtx) {
	return tplPerson;
}

var bob = {name: "Bob", pets: ["Fluffy", "Missy"]};

var vm = domvm.view(PersonView, null, null, bob);
```

The last init line needs a bit of explaining. It basically feeds `bob` into the view as `impCtx` (imported external context) rather than the `model`. While `model` is fixated during init to the view and cannot be changed, `impCtx` is always passed into `.render(impCtx)` and can be updated during any `vm.redraw(impCtx)` call or declaratively in any tpl via `[PersonView, null, null, jack]`. Models are used for diff/patch considerations since they are considered persistent, while `impCtx` can be swapped in/out whenever (it's a dep-injection container for the view that can be used to pass through storage provider instances, routers, etc. that may be needed or could change but should not be part of the vdom diff).

There's a shorthand for the ugly `null, null` sig. Pass a `false` key which indicates the second arg is `impCtx` rather than a model. Cleaner, but more convoluted:

```js
var vm = domvm.view(PersonView, bob, false);
```

**Comment by leeoniya** [comment]
Actually, almost forgot, `this` inside `render()` is the `model` [1]. so you can forget `impCtx` and simply do:

```js
var tplPerson = () =>
	["div",
		["strong", this.name],
		" has pets...",
		tplPets(this.pets),
	];

var tplPets = (pets) =>
	["ul", pets.map(pet =>
		["li", pet.name]
	)];

function PersonView(vm) {
	return tplPerson;
}

var bob = {name: "Bob", pets: ["Fluffy", "Missy"]};

var vm = domvm.view(PersonView, bob);
```

The only bit of weirdness is that the top-level `tplPerson` must pull the model via `this` rather than an arg. But you get the benefit of persistent treatment/vdom-tracking for `bob` even without being explicitly keyed. Either way, the behavior is easily accomplished.

[1] https://github.com/leeoniya/domvm/blob/master/src/view.js#L216

**Comment by leeoniya** [comment]
thinking about it a bit more, maybe `.render(model, impCtx)` would be better. `vm.redraw(impCtx)` would still update as before. but there'd be no magic `this` knowledge or relying solely on `impCtx` to pass anything through to an unclosured render func.

but in this case it would also need `key` to keep everything uniform and in order. `render(model, key, impCtx)` then.

**Comment by yosbelms** [comment]
@leeoniya After playing around few hours with `domvm` I realize why it is like that and the benefits of the state keeping inside the colsure.

**Comment by leeoniya** [comment]
@yosbelms 

after sleeping on it, i've decided to match `render`'s signature and calling context to that of the view: `viewFn.call(vm.exp, vm, model, key, impCtx);`

even though `impCtx` is now last, it's preferable to access it via `vm.imp` anyways via the first arg. having the `model` as `this` was a bit magical. `this` will now be the same as the view: the exported view context `vm.exp = {}` that's designed to expose any view state / API from the private closure.

**Comment by leeoniya** [comment]
done in https://github.com/leeoniya/domvm/commit/cd2a10f233a02606b7d1d1aaa75205a31484edc0

**Comment by yosbelms** [comment]
cd2a10f :+1:
