### ISSUE TITLE
Solicit some feedback (round 2)

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#30]
Hello good people!

With 1.0 slated for 4/1, it seems like a good point for a follow-up to #1.

Since #1, a lot of API polish, bug squashing and question answering has taken place. More features, tests and modules have been added, along with extra demos for different use cases. There are still docs to finish and tests to add (lifecycle hooks, router, observers, isomorphism), but the ergonomics of the lib are in a happy, wart-free place.

For those new to domvm and wondering about perf/size. It is modular and ~6k gzipped for all modules. It is currently the fastest [threaditjs](http://threaditjs.com/) implementation [demo](http://leeoniya.github.io/domvm/demos/threaditjs/) (open console for timings), besting the next fastest (Mithril) by at least 100% and is one of the quickest on dbmonster bench [demo](http://leeoniya.github.io/domvm/test/bench/dbmonster/), only marginally surpassed at high mutation rates by raw vdom diff/patch libs like kivi, citojs and Inferno.

demos can be found in `/demos` as well as `/test/bench`, the `gh-pages` branch is usually in sync with `master`, so can be viewed on github pages: http://leeoniya.github.io/domvm/...

@matthiasak

Regarding https://medium.com/@matthiasak/mithril-isomorphic-universal-experiment-cb645d1a9238#.e37n0h3w4

Sub-view composition and redraw has been a solved problem in domvm since Day 1 and was one of the main reasons I moved away from Mithril. Node-level patching support is also possible and was added a while back [demo](http://leeoniya.github.io/domvm/test/bench/patch/)

@sebadoom

Regarding https://auth0.com/blog/2016/01/07/more-benchmarks-virtual-dom-vs-angular-12-vs-mithril-js-vs-the-rest/

Would you be interested in an implementation of these benches in domvm?

Feedback and/or contribs are welcome, cheers!

@lawrence-dol
@yosbelms
@barneycarroll
@iamjohnlong
@koglerjs
@mikegleasonjr
@pdfernhout
@whitecolor

**Comment by lawrence-dol** [comment]
I would be.

**Comment by leeoniya** [comment]
as a side-note, i'd also like to get both of the following implemented:

https://github.com/localvoid/uibench
https://github.com/vdom-benchmark/vdom-benchmark

**Comment by lawrence-dol** [comment]
> I simply don't have the time nor the desire to chase the last few % in unrealistic stress tests (which dbmonster is).

I get that. Nor do I. I thought you were asking if we're interested "... in [seeing] an implementation" not "... interested in [doing] an implementation". I would if I had time, because memory use and GC pressure is a useful metric to weed out libraries which achieve performance by caching cheats instead of good code. In other words those that trade memory for performance. Resources are resources, so CPU use and memory use both matter.

**Comment by leeoniya** [comment]
@lawrence-dol 

There are certainly some known trade-offs in a few places. Here is what they are and how they impact perf/mem.

- By using JSONML instead of HyperScript, there is an initial array allocation for each node before it is converted into a vtree node from the templates. this has been discussed [1] and somewhat evaluated. I did not find a significant impact on perf or mem here. But the analysis was high level and it's possible there is something to be gained, though for large node counts this mem difference is dwarfed by DOM objects. There are some ergonomic advantages to using arrays over HyperScript, so the trade-offs are not entirely clear. This is something I want to revisit maybe for 2.0.

- Low-level vdom libs that rely on template data coming through as args of pure functions have much cheaper diff passes than domvm. While domvm "only" gets 70/s at 0% mutation, Inferno and kivi get 160/s. This is something I plan to address in a 1.x release, and it could piggyback on `_guard: true` to identify fully static branches in the template so there is no rebuild or diff overhead and just straight recycling of the old branch. This strategy is a bit ad-hoc, but will work well. In addition, each node can gain a custom `_diff`/`nodeShouldUpdate` that can similarly avoid rebuild/diff and reuse the old tree. I don't really know how much of this will be necessary in real life, considering the perf is already near peak.

These are the main two differentiators between domvm and the fastest possible libs. domvm is designed to be extremely flexible/composable, so it gives up a bit of performance for a huge gain in ergonomics and syntax. These tradeoffs are not accidental, but intentional and in my experience definitely worth it.

[1] https://github.com/trueadm/inferno/commit/134a90005cc8a3900bd601666dd1aa474c0abb6f#commitcomment-15365143

**Comment by lawrence-dol** [comment]
@leeoniya 

> it gives up a bit of performance for a huge gain in ergonomics and syntax. These tradeoffs are not accidental, but intentional and in my experience definitely worth it.

That I completely agree with.
