### ISSUE TITLE
Calendar example has TypeError at dominstr.js 116

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#31]
The calendar example () throws this exception for all mouse clicks:

```
14:23:05.566 TypeError: can't redefine non-configurable property "innerText"
DOMInstr/this.start() dominstr.js:116
opts.hooks.willRedraw() calendar.html:70
u.execAll/<() util.js:64
forEach() self-hosted:216
u.execAll() util.js:63
redraw() view.js:195
call() util.js:110
1 dominstr.js:116:1
```

FireFox: 44.0.2 on Windows 10.0.10240.

**Comment by leeoniya** [comment]
huh. i wonder if they moved which prototype `innerText` lives on.

works okay for me in Firefox 45 (current). can you please verify?

**Comment by leeoniya** [comment]
ah, that's right, it's non-standard Microsoft stuff. Looks like Mozilla just added it in 45 [1]

i didn't notice this whole time cause i'm usually on Nightly which is already at 48.0a1.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText

**Comment by leeoniya** [comment]
it should actually just be removed. `innerText` is not used anywhere in the lib. i think when i was writing the instrumentor i wanted it to just be generic so figured i would cover all DOM manip methods.

if you want to PR the removal, i'll merge it. otherwise give me a bit.

**Comment by lawrence-dol** [comment]
I don't mind doing the PR. I've not done one before (gasp), so be merciful. But I looked into the code already to track down the source. 

I have the latest production FF pending update; came down about half an hour ago, but I haven't restarted it yet.

**Comment by leeoniya** [comment]
dont worry about it.

done in https://github.com/leeoniya/domvm/commit/e8ed270556d78dc3118a2f28f62558f7b3a89c02
