### ISSUE TITLE
Routing and a missing link

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#34]
I am having a little trouble trying to get my basic application airborne. I can't seem to make the connection between the initial route and initialization. My route is set up in the router:

```js
    var exported            =this || {};

    function init() {                                                                                   // self-contained initialization avoids leaking temp objects into module closure
        router.config({
            useHist         : true,
            root            : "/"+window.location.pathname,

            init: function() {
                /**/console.log("[**] router config init",window.location.pathname);
                appMain.state.view=domvm.view(appMain.View,{ appMain: appMain, router: router });
                appMain.state.view.mount(document.body);
                appMain.state.view.hook({
                    willRedraw: function() {
                        /**/console.log("[**] Redraw App");
                        },
                    didRedraw: function() {
                        /**/console.log("[**] Redraw App done");
                        },
                    });

                router.refresh();
                },
            });
        Object.freeze(exported);
        }

    exported.root=Object.freeze({
        path: "/",

        onenter: function(segs) {
            /**/console.log("[**] Entered root path");
            document.title=setTitle();
            },
        })

    init();
```

(I use a pattern whereby I assign `this` to `exported` and then make separate assignments into `exported`.)

The console logs:

    20:10:10.810 [**] router config init /temjs/App1 AppScript;01:164:235
    20:10:10.812 Could not find route1 AppScript;01:37:473

Though what actually displays is "Could not find route", suggesting the trailing `1` in the copied text is a Firefox bug.

**Comment by leeoniya** [comment]
Have you looked at https://github.com/leeoniya/domvm#route-module yet?

I would recommend trying the router in hash mode first (`useHist: false`). Also, setting `root            : "/"+window.location.pathname` doesn't make sense. Root is a static prefix that will be prepended to all route paths during regex route compilation; it is meant to define a uniform route root and only applies to history mode routing (not hash).

**Comment by lawrence-dol** [comment]
> Have you looked at https://github.com/leeoniya/domvm#route-module yet?

Yes, I've read all the docs thoroughly and examined the ThreadIt.js code. I am just missing the immediate connection in setting up the route. I believe I am overlooking something simple, but subtle.

I don't understand the sentence:

> The router argument passed to the closure is the same one returned by externally. However, until the closure returns the routes, it is not fully initialized and cannot be used from inside for routing yet. If you [prefer] to keep everything in the closure, you can set up some config

In `ThreadIt.js` the router returns an entirely different object from the `router` argument it's given. I basically copied `ThreadItRouter`, with minor adaptions for my module structure.

> I would recommend trying the router in hash mode first

I've already tried it both ways.

> Also, setting root : "/"+window.location.pathname doesn't make sense.

It does for once off init of the router if you want it to adapt to an unknown installation location (which I do). I may well be misunderstanding it's use and significance.

> only applies to history mode routing (not hash).

Yes, I got that from the docs.

PS: Thanks for this library; I am enthusiastic about building something real with it.

**Comment by leeoniya** [comment]
> I assume it should be "... returned externally"

yes.

> However, in ThreadIt.js the router returns an entirely different object from the router argument it's given

In both cases, the `router` is *the* `api` [1],[2]. Externally and within `init` it is after route compilation (so can be used for routing). But in the router closure it's not yet fully initialized, cause you havent returned the routes yet (duh).

> It does for once off init of the router if you want it to adapt to an unknown installation location (which I do). I may well be misunderstanding it's use and significance.

Here's a different explanation for why this won't work.

Imagine your defined root is `/myApp` and single defined route path is `/threads`. The compiled route is `/myApp/threads` and matched by thr router against `window.location.pathname`. This is all good and well if your user hits *any* path initially, not just the root path. If the user lands initially in `/myApp/threads`, the compiled routes will remain the same.

If you use the `window.location.pathname` to dynamically define the root, then when the user lands in `/myApp/threads`, your compiled route will now be `/myApp/threads` + `/threads`. So the root must be static because it allows the routes to be compiled uniformly regardless which route the user opens the app in. This does not apply in hash mode because the `root` is irrelevant since the router simply grabs `window.location.hash`.

If you have a more complete (but reduced-case) app example, I will be able to help you better.

[1] https://github.com/leeoniya/domvm/blob/master/src/route.js#L114
[2] https://github.com/leeoniya/domvm/blob/master/src/route.js#L126

**Comment by lawrence-dol** [comment]
OK, if I can't resolve it quickly on Monday morning, I'll work up a jsfiddle, and if that doesn't pinpoint it for me, I'll post a link to it. Just thought I might be overlooking something simple.

**Comment by leeoniya** [comment]
BTW, it's uniformly how views/vms work.

```js
function MyView(vm, data) {
  // vm is not yet fully initialized here, so cannot be used for `redraw()`
  // until the render() template generator is returned from this closure
  return function() {
     return ["div", "foo"];
  };
}

// externally, the returned vm is initialized
var myVm = domvm.view(MyView, data);
```

Same with router:

```js
function MyRouter(router, data) {
  // router is not yet fully initialized here, so cannot be used for `goto()` or `refresh()`
  // until the routes are returned from this closure
  return {
    home: {...}
  };
}

// externally, the returned router is initialized
var router = domvm.view(MyRouter, data);
```

The only distinguishing aspect is that the router's config can take an init callback that runs once the routes have been initialized/compiled. I could add the same `init` option to the vm's config to have 100% uniformity.

**Comment by lawrence-dol** [comment]
Resolved this problem. I was expecting `this` to be set since the Router module is typically shown with a leading-uppercase, indicating a constructor. So I wasn't explicitly returning anything from the function.

**Comment by lawrence-dol** [comment]
I would argue that no element of DOMVM, nor it's example should use constructor semantics if they are not, in fact, invoked as a constructor.

**Comment by leeoniya** [comment]
Right, they're technically init closures.

In views, `this` === `vm.api`, so you can expose view state and methods. Generally though I'm in the `this` considered harmful camp (especially for JS, where the context can be defined ad-hoc at the call site). In the router `this` is left alone.

I dont use `this` in any examples, docs or demos when inside either the route or view closures. I only reference the closure as `constructor` once in the docs and perhaps it should be removed.

All that being said, I think using Title-case is appropriate. There is no use of `new` or `this` anywhere and there should be no assumption that there are such semantics. I would be fine with removing "constructor" wording from the docs, though. For all intents and purposes, these view closures in practice have the same characteristics as constructors...they init once per instance and retain state. There is no reason to make them look like lesser helper functions.

my $0.02.

**Comment by lawrence-dol** [comment]
> I'm in the "this considered harmful" camp.

As am I, which is why I have the style that treats all constructors as module initializers and assigns `var exported=this` at the top and contains all functions within the initializing closure. Except for that one assignment I never use `this` at all. But I do use `new` in invoking one of these "module" constructors; that is, in making a "new" module instance.

> All that being said, I think using Title-case is appropriate.

With this I will respectfully disagree. Title case is all important in JavaScript to signal something that should be invoked using new. But, hey, it's your lib.

> For all intents and purposes, these view closures in practice have the same characteristics as constructors... they init once per instance and retain state.

Then why not simply invoke them as constructors and follow the principle of least surprise? Especially because the surprise is forced on users of the lib, and not limited to its internals.

It's easy enough for me to work-around, but now my code contains a surprising artifact that needs to be explained to each engineer who works on it.

**Comment by lawrence-dol** [comment]
With all that said, if it's limited to the router, it's not that big a deal. But I suspect it applies to all VMs except for pre-constructed ones (static state with injected context).

**Comment by leeoniya** [comment]
There is nothing that enforces specific naming conventions in your app code; use whatever case you feel comfortable with. I prefer title-case, so the docs are written this way. The expectations set up by the docs is an orthogonal discussion and has no bearing on the lib's semantics. I see your point, and would be happy to revisit altering the docs if in fact many users turn out to have your expectations.

*However*, use of the lib in undocumented ways is explicitly undefined and should be considered "subject to change without notice". My semver contract is only to the docs and existing tests. Obviously, at this stage while the docs are sparse, it's hard to know what is intentionally omitted rather than simply incomplete.

Making them real constructors is not currently feasible since `domvm.view()` does much more than simply execute the closure. I don't want to give the impression that you could simply use `new` on the view closures because you absolutely cannot.

**Comment by leeoniya** [comment]
> With all that said, if it's limited to the router, it's not that big a deal. But I suspect it applies to all VMs except for pre-constructed ones (static state with injected context).

It applies to all vms. You simply cannot use `new`. If you want to use a convention that implies this within your own codebase, then feel free to do so.

For me, there is greater usefulness in seeing which are stateful components and which are render helpers. You can always use a lowercase prefix if you prefer: `function vwContent() {...}`

**Comment by lawrence-dol** [comment]
> There is nothing that enforces specific naming conventions in your app code

Doh! Of course, you are quite right. How's that for pure habit kicking in. I'll need to think about how I want to handle this in my context.

And for that matter, that was something I disliked about Mithril; it's conventions bled into the user's code in several places.

> My semver contract is only to the docs and existing tests.

That's fine -- I'd expect nothing more.

> I don't want to give the impression that you could simply use new on the view closures because you absolutely cannot.

Hmmm. That raises the question as to under which circumstances the closure will be invoked vs. the VM be simply used. Is that documented yet?

**Comment by leeoniya** [comment]
i'm gonna close this, since it no longer relates to routing. we can open a new issue for this discussion if needed.

**Comment by lawrence-dol** [comment]
Was just about to do the same.

**Comment by leeoniya** [comment]
> Hmmm. That raises the question as to under which circumstances the closure will be invoked vs. the VM be simply used. Is that documented yet?

declarative `[myView, data]` within another template will invoke it once. and imperative `domvm.view(myView, data)` will invoke it once. that's the whole story.
