### ISSUE TITLE
Mount appends view to element content

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#35]
Not sure if this would be considered a bug or not, but the mount function appends the view content to that of the element on which it's mounted. That seems a little counter-intuitive and it also prevents a very simple script-block warning implementation.

`````
<body>
    <div>This application requires JavaScript to work.</div>
    <script src="AppScript;01"></script>
</body>
`````

Result:

```
This application requires JavaScript to work.

This is my view
```

Instead of:

```
This is my view
```

**Comment by leeoniya** [comment]
i went back and forth on this for a while :)

This is how `mount` works in most vdom libs. I considered `.appendTo`, `mountIn` but decided to just stick with `mount`.

What you want to do can be accomplished by `.mount(target, true)`.

**Comment by lawrence-dol** [comment]
> What you want to do can be accomplished by .mount(target, true)

Good enough.

**Comment by iamjohnlong** [comment]
it'd be nice to tag stuff like this to add to the docs.

**Comment by leeoniya** [comment]
yes, there's a A LOT to add to the docs. wanna help? ;)

**Comment by iamjohnlong** [comment]
Yes, I'm working on it when I have spare time. Unfortunately I have a deadline at work right now slated for April 1st which is slowing my capacity to help. Fortunately I'm including the use of domvm.

**Comment by lawrence-dol** [comment]
I do want to help. But first I need to learn what I am documenting. It's also good to flesh out the docs when things have stabilized a bit (post 1.0). Otherwise you end up with the situation with the docs are incorrect, and that's worse (IMO).

Can issues like this be tagged in some way to be revisited post-1.0 so docs can be done when the dust has settled? Appreciating that there needs to be a minimal middle-ground or DOMVM won't gain traction.

**Comment by franzliedke** [comment]
Just a quick suggestion: Instead of `.mount(target, true)`, you could add a second method (maybe called `mountOverriding(target)`) that internally sets that boolean flag.

That way, you can avoid these non-intuitive boolean flags - really helps when reading code.

**Comment by leeoniya** [comment]
i opened #36 to track most of what still needs to be documented.

@iamjohnlong 
> Yes, I'm working on it when I have spare time.

@lawrence-dol
> I do want to help. But first I need to learn what I am documenting

Of course. It's very valuable to get others to explain things in ways that may seem not so obvious to me, since i am the most biased person here.

@franzliedke

Yeah, it's a bit of a wart. But i'm also a sucker for short method names. I toyed with moving this functionality into the isomorphic `attach`, since it already *nearly* works this way (accepting the root node). It didnt work out so well, because `attach` can never clear the contents (since it must absorb the existing dom), except with...you guessed it: another boolean flag :)

My most agreeable option was `.mountAt` or `mountTo` but then i was thinking maybe `mount` should be `mountIn`...which is weird. meh. Not opposed to something short and obvious, but `mountOverriding` ain't it :\

**Comment by lawrence-dol** [comment]
Maybe `mountInto` and `mountOnto` or `mountOver`?

I'm actually a little curious how the redraw semantics can work without replacing the entire contents. Do the existing content nodes get hydrated into the view I provide?

**Comment by leeoniya** [comment]
> I'm actually a little curious how the redraw semantics can work without replacing the entire contents. Do the existing content nodes get hydrated into the view I provide?

yes. after the vtree is built `attach` just walks it and the dom in parallel, simply setting node.el to the existing one. it also attaches handlers and sets props which cannot be represented in an html string. then everything works as usual.

**Comment by leeoniya** [comment]
> Maybe `mountInto` and `mountOnto` or `mountOver`?

`mountAt` would be my choice. However, I'm not sure how much this is needed. Yes it would make it more clear (maybe), but `mount` in general is not a thing used very often to begin with. Is it worth adding another method for clarity of something usually called only once per app, or a few times at most if using domvm for in-page widgets?

In addition there are other trailing boolean args in other places. I'm not a fan of eliminating all boolean args in favor of Java-esque method names and counts. Certainly, I don't want `someMethod(arg1, true, arg2, false)` in the api, but a single trailing boolean is bearable.

For 1.0, I'd like to test and document what exists. Time/users will tell whether more clarity is needed once the docs are complete and logical. Things like `mountAt` are easy to add later, but difficult to remove.

**Comment by lawrence-dol** [comment]
I actually had the same thought even as I made my suggestions. I agree with you and say no, it's utterly unnecessary. Having a boolean on mount tells me immediately that there is probably an optional use case. Sure, I have to look at the docs, but what the heck.

**Comment by leeoniya** [comment]
@franzliedke 

btw, if you want a dedicated method, you can uses domvm's assisted monkey-patching https://github.com/leeoniya/domvm/issues/26:

```js
domvm.view.extend(function(vm) {
  vm.mountAt = function(rootEl) {
    return vm.mount(rootEl, true);
  };
})
```

**Comment by lawrence-dol** [comment]
@leeoniya,

> if you want a dedicated method, you can use domvm's assisted monkey-patching

How so? From what I can tell, the array of extensions are simply automatically invoked while creating the view:

    u.execAll(vmExts, [vm]);

That would not be the effect of adding `mountAt` I would expect.

Also, what *would* be useful would be an extender in `domvm` itself that added the function to any of the modules after checking for conflicts:

    domvm.extend("view.myFunction",function() { ... }); // Okay
    domvm.extend("router.mount",function() { ... }); // Conflict! throws clear error

Just a thought.

**Comment by leeoniya** [comment]
> How so? From what I can tell, the array of extensions are simply automatically invoked while creating the view:

right, so...

```js
var vm = domvm.view(MyView, data);     // created view now has patched-in mountAt

vm.mountAt(document.body);
```

**Comment by lawrence-dol** [comment]
> created view now has patched-in mountAt

Face-palm. Too much code in my head at one time. 

That's rather nice.
