### ISSUE TITLE
missing docs

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#36]
Here is my (non-exhaustive) list of things to document. I will keep it updated as they are finished or as more are added.

**API**
- `domvm.utils.repaint(vnode)` + any other useful util methods
- `vm.patch()`
  - `vm.patch(oldNode, newTpl)`
  - `vm.patch(oldNode, {style:..., class:...})`
- `vm.api` (=== `this` in render() and init closure)
- `domvm.view.extend(function(vm) {...})` (view monkey-patching)
- `vm.unmount()`
- `vm.mount(target, true)` will treat target as root and clear it first
- `vm.update(newModel)` for `false`-handle views (stateful slots)
- namespaced refs: `_ref: "a.b.c"` => `vm.refs.a.b.c`
- exposed refs (`_ref: "^moo"`)
  - using them for a restricted event bus/selective sub-view redraw
- node-level `_diff: [cmpFn, data1, data2]` as alternative to splitting off sub-views & caching old values
- vm-level `vm.diff(function(model) {return [model.data1, model.data2];});`
- returning `false` from `render()` as sub-view perf optim (inactive sub-views, 0-diff)
- explicit tagging of child arrays `kids._expl = true`
- `willUpdate` vm hook
- passing hooks into sub-view from parent via `opts`
- `["p.moo", {class: "active"}` is additive and results in `<p class="moo active">`
- `watch`, `hooks` and `evctx` params in view opts
- full sigs of all callbacks/user-supplied funcs
- examples of using `_data`
- entire `watch` module
  - w.get/post/etc
    - signatures
    - success/error callbacks
  - w.prop
    - async props with initial values
    - asyc prop.update()
    - pass `false` to mutate without firing handler, or alternate handler
    - `middleWare` param for validation/value transforming
  - w.sync
  - w.fire
- todo: add vm.route.extend?

**General**
- explain what that vm is the lib's native api portion of the ViewModel
- make it clear that all views require a single root node
- the fact that `name` and `_ref` implicitly set _key if not present
- no need for explicit props of some common input attrs, like ".checked" etc..
- more detailed lifeycle hooks docs
- more routing examples
- document vtree/vm architecture https://github.com/leeoniya/domvm/issues/72#issuecomment-217569703

**Footguns**
- add section explaining handle/key and model persistence implications for state retention and DOM recycling #83 
- if model is destroyed and recreated on every redraw() (like via JSON.parse), opt view out of persistence to ensure dom is reused rather than re-created: `[myView, tempData, false]`
- encourage use of sub-renderers to break up templates instead of sub-views when not necessary, since perf is better and nodes can carry persistent state via a combo of `_ref` and `_data`
- explain that using _key is not a perf optimization and not required if model is persistent. and should be used only for json-style re-created data or to enforce destruction of state and prevent dom recycle.
- show that while viewFn (init closure) and render() sigs are the same, the former is immutable while latter is mutable in cases of non-persistent models via `vm.update(newModel)` or `[myView, newModel, false]`
- add section about ensuring that dynamic form elem props are always re-synced back to model
- dont re-create event handlers inline, pull them out of render()
- explain that dom event handlers have a sig of `handler(arg1..., e, node, vm)` if defined as `onclick: [handler, arg1, arg2]`, else `handler(e, node, vm)`.
- debugging slow perf using DOMInstr
- shorthand id/class attrs on elems must be in `div#id.class1.class2...` order
- more visible docs about explicit child array restrictions & work-around
- `mount(body, true)` from in-body script, ensure to wrap in `DOMContentLoaded`: https://github.com/leeoniya/domvm/issues/56#issuecomment-213210948
- avoid holding references to the `vm.refs` object to dom nodes #58

@lawrence-dol
@iamjohnlong

**Comment by lawrence-dol** [comment]
Can you tag this "Help Wanted" so it stands out in the issue list, please?

**Comment by leeoniya** [comment]
i've added some broad categorization

**Comment by ysharplanguage** [comment]
Promising work! Maybe of interest for domvm also, some time later: https://gist.github.com/ysharplanguage/cad1ea5f4d9319c777ec0780a61908d1

**Comment by leeoniya** [comment]
@ysharplanguage

Interesting, though this syntax is not something i'd personally want to write code in.

> (more roundtrip-friendly from JSON to markup & vice versa, and which allows the first child of an explicit child array to be a text node or a getter)

A getter cannot be JSON serialized or converted to html, so it's not gonna be round-trip friendly in any scenario, right? I'm not sure this amount of additional template baggage is worth the uniformity to allow firstChild text nodes in explicit child arrays, considering how easy it is to work around this if you need to.

**Comment by ysharplanguage** [comment]
@leeoniya I agree personal preferences wrt. overhead between different notations is something not to overlook and ought to encourage going for whatever is leaner rather than what is not. In that instance, the overhead is exactly 3 characters per element node (quotes and colon), which may or may not be acceptable by most (personally, I'm fine with to trade it for more uniformity, but granted, maybe I'm the only one :) ...)

As for serializing getters, true, that's not straightforward, and the added cost/complexity of relying on some, say, JS [AST](http://jointjs.com/demos/javascript-ast) support, may not be worth it -- so, yes, I too would exclude those use cases where the view functions spit out virtual doms with getters.

I just shared it as I stumbled upon this slight change over JSONML per chance and found it interesting, in the context of bi-di transfos of JSON from/to XML/HTML-alike markup, with a notation where (unlike JSONML) only the array index 0 needs to play a special role.

Thanks for your feedback's good points, anyway :)

**Comment by leeoniya** [comment]
It's not necessarily the amount of characters per node, it's the amount of template characters *in total* that you have to grok whenever looking at the source, which becomes significant pollution in large structures (for me at least).

**Comment by ysharplanguage** [comment]
I hear you, especially since in the case of domvm, it's about something that is actually *authored* (and maintained), and not just machine-generated. Reckoned.

**Comment by lawrence-dol** [comment]
> though this syntax is not something i'd personally want to write code in

I tend to agree, even though I do like uniformity/consistency. It's interesting to me that the "special" nature of the first child argument is mentally grating, but pragmatically hasn't caused me problems yet.

**Comment by leeoniya** [comment]
the reason that it does not happen in real life is because most explicit child arrays happen as a side-effect of `map` operations over uniform arrays of objects. you would not have a resulting uniform child array of strings (it would make no sense). and child arrays that are non-uniform are usually authored by hand and have no benefit to be arrays at all when you could avoid the extra brackets anyways.

at the end of the day explicit child arrays are more a convenince feature indentical to sub-array flattening and is most useful for iterators that return arrays of template nodes.

**Comment by leeoniya** [comment]
@lawrence-dol poke.

Any interest/time to help with this? Also, how's the coding going?

**Comment by lawrence-dol** [comment]
Yes, I am interested in helping out with this. In my "spare"
        time... which is, of course, in the time I make for it... which
        means, I should do a little bit here and there as time permits.
        We need to work on this if we are to see any significant uptake,
        I think.
      
      My project is continuing apace, though has been interrupted for
        the last few weeks with other high priority stuff for existing
        customers. The next phase is to implement the comms support,
        which will bury me deep for several weeks.
      I've been keeping an eye on the Mithril rewrite too. Will be
        interesting to peruse the docs when they are ready.
      
      
        -- 
        Lawrence Dol
        http://think.dolhub.com | http://tech.dolhub.com
      
    
    
      
      From: Github Notification
        Sent: 2016-06-04 14:21:13
        To: Leeoniya/domvm
        CC: Lawrence Dol (Personal), Mention
        Subject: Re: [leeoniya/domvm] missing docs (#36)
      
    
    
      @lawrence-dol
        poke.
      Any interest/time to help with this? Also, how's the coding
        going?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by leeoniya** [comment]
> I've been keeping an eye on the Mithril rewrite too. Will be interesting to peruse the docs when they are ready

Ditto, it's looking pretty good so far but there's still a lot of work left.

BTW, I just pushed a commit that implements object pooling in domvm's vtree, reducing the mem allocs and GC pressure significantly and improving 15-20% on perf. This puts it into Inferno, kivi and Mithril-rewrite territory in terms of performance.

**Comment by lawrence-dol** [comment]
> reducing the mem allocs and GC pressure significantly and improving 15-20% on perf

Nice. Good work.

**Comment by yosbelms** [comment]
> BTW, I just pushed a commit that implements object pooling in domvm's vtree, reducing the mem allocs...

@leeoniya can you point me to that commit please?

**Comment by leeoniya** [comment]
@yosbelms

https://github.com/leeoniya/domvm/commit/673bc65451ad85e1b2f7360e98a9a27a81a1af60

It's present in 1.2.4, but this version has a serious regression in it causing several demos to be broken (likely related to the new vnode recycling). All tests show green, but that just means there arent yet enough tests (or rather sloppy QA on my part).

Don't use until 1.2.5, hopefully later today.

**Comment by leeoniya** [comment]
v1.2.5 is out with the fixes.

**Comment by yosbelms** [comment]
@leeoniya, fine, would be sane to test demos along with unit tests before new releases, I think all domvm based apps (including demos) should'nt "know" about nodes existence, nodes should remain as privated part of the underlaying architecture. This is a good way to avoid bad influence of code refactoring such as broken demos you mentioned above.

**Comment by leeoniya** [comment]
@yosbelms this refactoring was fully internal. none of the demos "know" about the vnodes, there were no external (or even internal) api changes. no tests had to be changed either.

the breakage was a side-effect of double-freeing the same vnodes back into the pool (by a redundant cleanup pass) and then being picked up more than once by different parts (often nested) of the same template. this only became clear on the 3rd non-rAF-coalesced redraw since the vnodes do not start being recycled until then.

that being said, i want to make the QA process less manual and welcome any help with writing more tests that would help catch stuff like this. unfortunately this isn't my 9-5, so my time/energy is rather limited :/

**Comment by lawrence-dol** [comment]
@leeoniya 

Do you have any thoughts/preferences/requirements as to the structure of the docs? Any objections to breaking them into logical units with an index vs. one huge page?

**Comment by leeoniya** [comment]
no objections to splitting, but we should decide if the topics are split by complexity (which helps people learn), or by API (which helps with reference).

Personally I prefer to stick with the 80/20 rule, leaving the more nuanced parts for later while giving most users what they need to get pretty far before WTFs start to kick in.

That being said, I'd probably want to discuss how to use DOMInstr early rather than late so that people can understand how their view structure affects performance and recycling behavior. That way there are more people asking about why something is not working as expected and the lib can be refined for v2, or the docs can be tweaked to highlight common misunderstandings.

**Comment by lawrence-dol** [comment]
I'd lean toward an 80/20 topical format with each topic split into Fundamentals and Experts section, and a separate alphabetical cross-reference index page that links to the appropriate places. That way the same pages can serve as a learning tool and a reference tool.

I'd be quite happy to set up the outline once the format is agreed, or set something up by way of example for you to review. In my other life I teach, so I am pretty good at that kind of thing. I might be able to work on it this coming weekend; but definitely not the following two (vacation and then teaching on Saturday).

**Comment by lawrence-dol** [comment]
I'd lean toward an 80/20 topical format with each topic split into Fundamentals and Experts section, and a separate alphabetical cross-reference index page that links to the appropriate places. That way the same pages can serve as a learning tool and a reference tool.

I'd be quite happy to set up the outline once the format is agreed, or set something up by way of example for you to review. In my other life I teach, so I am pretty good at that kind of thing. I might be able to work on it this coming weekend; but definitely not the following two (vacation and then teaching on Saturday).

**Comment by yosbelms** [comment]
https://github.com/leeoniya/domvm/issues/104#issuecomment-263949311

My concern is the devs new to domvm, since the default branch is 2.x and there isn't a link to docs in the readme.md. I think domvm is a great work, it must be learned, used, shared, but newcomers could feel bashed by the missing docs.

**Comment by leeoniya** [comment]
i'm starting on v2 docs. one thing i'd like to have is jsfiddle links to all doc examples.

aside from missing things in v1 docs, is there anything else that could be improved? like order of feature introduction? etc?

cc @grumpi

**Comment by grumpi** [comment]
I do like the style of v1 docs: A brief explanation of the core concept at work with demo(s) attached. You manage to get to the point without rambling about tangential issues.

I think the order of feature introduction is fine. I've been using the docs as a quick reference to look up the feature I want to use.

I think a good way to introduce more advanced functionality is to do that by mentioning that it exists in the appropriate section, then elaborate in another demo (with comments), if necessary.

**Comment by lawrence-dol** [comment]
I agree with @grumpi. Despite being sparse they've been useful and I'd like to see the main V2 retain that style, with hyperlinks to pages with more detail and depth.

I would move the building section to the end, as an addendum since it's not relevant to using DOMVM.

When I transition to V2 I'll keep notes for feedback.

**Comment by leeoniya** [comment]
> I would move the building section to the end, as an addendum since it's not relevant to using DOMVM.

Given that several builds are now provided as part of the dist, this makes sense to move out. Maybe to a wiki. At some point I'd like to sever the jsfiddle dependency and create a similar lightweight playground around Codemirror which can be served directly via `rawgit` or `gh-pages`, obviously built using domvm :)

If you guys have some free time, that might be a quick & fun endeavor.

**Comment by leeoniya** [comment]
I've cut down on the philosophy section. It's more to the point now I think.

I'd like to keep the main readme to be sales pitch only: intro, features, demos, benchmarks and at-a-glance sample that's easy to grok and someone can play with via jsfiddle.

The key distinguishing feature of domvm is its flexibility, allowing views that can be nearly fully decoupled from the rest of your code and composed as easily as declarative alternatives. To this end, I'd like to focus on "patterns" up front. That is, show the same simple app written in several patterns. I've done this so far, but concerned about an overwhelming amount of similar-looking code being too much in a readme. If only markdown allowed some accordion stlye presentation so we can just unfold each patter progressively without forcing people to scroll for each pattern :/

**Comment by grumpi** [comment]
> sales pitch only: intro, features, demos, benchmarks and at-a-glance sample

I think it's a good idea to link to a "quick reference" like the one you had on the front page of domvm 1.x-dev. A good place to link might be from "can be learned in under an hour". I found the quick reference very compelling because it showed how things **are** simple, instead of just claiming it.

> show the same simple app written in several patterns

That's good. You could even present the simplest examples side-by-side on `gh-pages`.

**Comment by leeoniya** [comment]
this is waaay out of date now.
