### ISSUE TITLE
Base watcher fetch function

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#37]
All the watcher AJAX wrappers defer to initFetch, which is a good internal name reflecting the asynchronous nature. Could we add one more generic exported function, `fetch(mth, url, cb, opts)`, to allow any HTTP method to be used so that the others become mere common-case conveniences?

There is, in fact, an argument to be made that get, delete, post, put and patch should be in the application wrapper and that only `fetch` should be provided, but I think that they make a nice common-case-subset API.

    fetch: function(mth, url, cb, opts) {
        return initFetch(mth, url, null, cb, opts);
    },

    get: function(url, cb, opts) {
        return initFetch("get", url, null, cb, opts);
    },

    ...

For example, one of my existing APIs uses LINK and UNLINK.

**Comment by leeoniya** [comment]
yeah, this could be useful. the main reason for the wrappers is to be able to avoid the `body`/`params` argument for HTTP verbs which dont (or cannot) have one.

however, i'm discovering that even `get` can benefit from `params` (similar to jquery) so you don't have to assemble your own query strings. but that means you have *2* optional arguments before the callback(s): `meth, url, query, body, cb, opts`.

since these methods are not perf-sensitive, perhaps having a single "fetch" with multiple signatures would be best? personally i prefer not to have multi sigs, but enforced optional params are hard to swallow as well.

i'm using this helper in a demo i'm currently writing, and can't say i enjoy having it live in app-space:

```js

function toQueryString(obj) {
	var parts = [];
	for (var i in obj) {
		if (obj.hasOwnProperty(i)) {
			parts.push(encodeURIComponent(i) + "=" + encodeURIComponent(obj[i]));
		}
	}
	return "?" + parts.join("&");
}
```

**Comment by lawrence-dol** [comment]
I just noticed the duality of setting the method:

`````
function initFetch(method, url, body, cb, opts) {
    opts = opts || {};

    opts.method = (opts.method || method).toUpperCase();
`````

If there's not a concrete use case for this I would either force it from the argument or at most override the options with the argument. 

`````
function initFetch(mth, url, body, cb, opts) {
    opts = opts || {};

    opts.method = mth.toUpperCase();
    // ~or, if you must~
    opts.method = (mth || opts.method).toUpperCase();
`````

It is, I think, really "surprising" when:

    get("https://example.com/api/apples",...,opts)

deletes the `apples` collection the `opts` happened to have `method: DELETE` for some unexpected reason. The principle would be either specify the method in the argument, or the options, but not both.

**Comment by lawrence-dol** [comment]
> [I'm] using this helper in a demo [I'm] currently writing, and can't say [I] enjoy having it live in app-space

I agree; it's one of those guaranteed to need in any real app using a network API (NAPI). But I wouldn't abandon the core method functions just yet; as I said they make a good standard API for 99% of apps. Expanding their signature to allow a query data object would be great, and both query data and content where allowed by the HTTP spec (put, patch, post, delete?).

**Comment by leeoniya** [comment]
> I think, really "surprising" when:

agreed. removing opt overrides of any explicit (!= null) param is the way to go.

in fact, perhaps it would be good to remove `opts` from the wrappers entirely and offer `fetch(url, opts, cb)`

**Comment by leeoniya** [comment]
what about...

`.get(url, query, cb)` & `get(url, cb)`
`.post(url, query, body, cb)` & `post(url, body, cb)`
`.fetch(url, opts, cb)`

**Comment by lawrence-dol** [comment]
I like that; though I would keep put, delete and patch, since every NAPI I've ever built uses them. (I happen to be a big fan of generic, curated, RESTful NAPIs.)

I think I would like to allow query to be an object that was to-string'd for us. As an already valid string it's very easy to just append to the URL, although having domvm append it with a `?` or not would be one argument for allowing a string arg too; e.g:

````
function get(url,qry,cbk) {
    if(typeof(qry)==-"Function") { cbk=qyr; qry=null; }
    if(typeof(qry)==-"object") { qry=toQueryString(qry); }
    if(qry!=null) { url+="?"+qry; }
    ...
````

**Comment by leeoniya** [comment]
> I like that; though I would keep put, delete and patch, since every NAPI I've ever built uses them. (I happen to be a big fan of generic, curated, RESTful NAPIs.)

yeah, i just used post as an example for a method that has a body, i'll keep the rest as well.

i'll poke at these later tonight.

**Comment by lawrence-dol** [comment]
There is an argument that because JS does not validate function argument, that having get, put, post, patch and delete with identical arguments is ideal, and fetch with logically consistent arguments.

````
get(url,dta,cbk) // data is query data and optional
put(url,dta,cbk) // data is content data
patch(url,dta,cbk) // data is content data
delete(url,dta,cbk) // data is content data
fetch(mth,url,cbk,qrydta,condta) // query and content data are separate
````

That way changing or copy/paste `get` to a `put` does not result in mistakes because an argument needed to be moved, added or removed.

But I don't know how strongly I'd make this argument. Just putting it out there as an idea.

**Comment by leeoniya** [comment]
good points.

maybe it makes sense not to add `query` convenience into methods other than `get`. but then there's HEAD, OPTIONS.

i think your suggestion would work well. especially if there's a query-builder helper provided that can simply be tagged onto any url.

**Comment by leeoniya** [comment]
```js
// all query & body optional

get(url,query,cbk)
delete(url,query,cbk)
post(url,body,cbk)
put(url,body,cbk)
patch(url,body,cbk)
// bodyOrQuery is query for "get"/"delete", else body
fetch(mth, url, bodyOrQuery, cbk, opts)
// straight pass-through, same sig as standard `fetch`
fetch(url, opts)
```

**Comment by lawrence-dol** [comment]
That's better than mine, but I don't think I'd do fetch like this unless there was a helper that looked like:

```
addQuery(url,qry); // adds ?... if qry!=null and not empty

...

w.post(w.addQuery(url,qry),function() {
    ...
    });

// though if w is longer, it's a little bit verbose:
autoRedraw.post(autoRedraw.addQuery(url,qry),function() {
    ...
    });
```

Hmmm.

**Comment by leeoniya** [comment]
`w.query(..)` would just return an empty string if the query is non-buildable, i'd rather not wrap simple concat functionality.

**Comment by leeoniya** [comment]
i think i'll drop `bodyOrQuery` from `fetch`, it's too magical. it'll just be optional `body` and i'll leave the query building up to the user via the helper.

**Comment by leeoniya** [comment]
technically there's nothing `watch` related about the query helper, i can stick it in domvm.util or domvm.watch, but you still need to alias those for breavity :/

**Comment by lawrence-dol** [comment]
> would just return an empty string if the query is non-buildable, i'd rather not wrap simple concat functionality.

If I may push back just a little, it's not just concat but the decision to append anything at all to the URL.

    var qry={};
    ...
    url+="?"+w.query(qry);

adds a phantom `?`, needing then to always do something like this to avoid it:

    qry=w.query(qry);
    if(qry.length!=0) { url+="?"+qry; }

**Comment by lawrence-dol** [comment]
>  there's nothing watch related about the query helper ... you still need to alias those for brevity

Agreed. I have found myself with the following globally available to my entire program (within it's top-level closure):

`````
var dvm={
    u                   : domvm.util,
    v                   : domvm.view,
    w                   : domvm.watch,
    }

dvm.v.extend(function(vm) {
    vm.aRedraw=dvm.w(function(vm) {                                                                 // mutation observer to reduce app.vm.redraw() boilerplate
        vm.redraw();
        });
    vm.mRedraw=domvm.watch();                                                                       // no-op mutation observer for ajax methods
    vm.aProp=vm.aRedraw.prop;
    vm.mProp=vm.mRedraw.prop;
    })
`````

I am not at all sure I like either construct yet.

**Comment by leeoniya** [comment]
> If I may push back just a little, it's not just concat but the decision to append anything at all to the URL.

the point is that you never have to deal with "?" if `w.query()`  already returns it to you only when the query is buildable, else it will bring back an *empty string*. There would never be a phantom "?" or any additional checks in your app, you simply append the output of the query helper unconditionally.

**Comment by lawrence-dol** [comment]
> if w.query() already returns it to you only when the query is buildable,

Missed that detail. Then, yes, same end result, simpler spec. I seem to be running a little foggy today. Sorry.

**Comment by leeoniya** [comment]
Some things to note:

- w.fetch and w.query have been added
- trailing opts argument has been dropped from wrappers, use w.fetch if opts are needed
- opts.method cannot override explicit method set in args
- optional `query` argument has been added to `get` and `delete` wrappers
- For fetch/post/put/patch wrappers, `body` is not optional, since it's rarely absent in practice and code needed to make it optional adds complexity and bytes.

The entire watch module needs tests written! I know w.sync is broken in some ways for sure.

**Comment by leeoniya** [comment]
closing. original concerns addressed.
