### ISSUE TITLE
Debugging: Concat unminimized

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#38]
Would it be simple to include unminified copies of the two distribution JS files, by which I mean either just plain concatenated (ideally with comments stripped out), for debugging?

**Comment by leeoniya** [comment]
sorry, i dont see much benefit in this. feel free to DIY.

you can include all the modules as-is from /src in script tags and it will work fine. no concat, min or building needed.

**Comment by lawrence-dol** [comment]
Fair enough; was looking for a quicker swap out than that (my web server's built in support includes replacing xyz.js and xyz.min.js with the flip of a switch).

No worries -- had to ask.

**Comment by leeoniya** [comment]
concat is not a difficult on-liner. it does have a hard dependency on electricity though ;)

**Comment by lawrence-dol** [comment]
I've already taken care of it. As you said, trivial enough.
