### ISSUE TITLE
vm.refs[] => vm.refs() to allow objects as _ref?

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#39]
~~i've decided to change~~ `vm.refs` from an array to a getter function. app code updates should be trivial (unless you were iterating vm.refs): `vm.refs[key]` will become `vm.refs(key)`.

this is necessary for future-proofing the lib and allowing the internal `refs` impl to be non-uniform. the change will pave the way for _ref as well as _key on nodes to be objects OR values, transparently backed by Map, Weakmap or Hash.

invoking vm.refs with multiple args should bring back an array of vnodes while invoking it with 0 args should bring back an object containing both the Map and the Hash where object and value refs are held respectively.

expect the change to drop in the next few days.

**Comment by leeoniya** [comment]
@lawrence-dol

**Comment by leeoniya** [comment]
i may reconsider/back-burner the multi-arg idea.

perhaps i'd want to use it as a setter at some point.

**Comment by lawrence-dol** [comment]
Very good. This is the time to identify and fix the cruft. This is what file find/replace is for.

**Comment by leeoniya** [comment]
@lawrence-dol 

implemented in this branch: https://github.com/leeoniya/domvm/tree/object-refs-weakmaps

an inevitable outcome of this is that you can no longer do `vm.refs.myRef` but have to do `vm.refs("myRef")`, it makes the app-space code more "stringy" than i'd prefer. unfortunately, i don't think this situation is avoidable.

**Comment by lawrence-dol** [comment]
> I've added it to the polyfills collection.

I noted that. Does the polyfill contain only WeakMaps or fills for all ES6 collections (they should be useful).

I also noted that the polyfills folder contains "fastclick.js", but my impression was that this was only used by demos and not by DOMVM. Assuming I'm correct in that, may I be so bold as to suggest it should be separated such that the distributed polyfills are only and exactly what DOMVM needs, lest we become bloated from polyfills?

**Comment by leeoniya** [comment]
oops, forgot to commit the src. fixed [1] from [2].

> I also noted that the polyfills folder contains "fastclick.js"

right, it's not part of the build script and not included in the `polyfills.min.js`, i will move it out to demos/lib. i think it's in src because i have the whole folder sym-linked into a sub-folder in demos.

[1] https://github.com/leeoniya/domvm/blob/object-refs-weakmaps/src/polyfills/es6-collections.js
[2] https://github.com/WebReflection/es6-collections

**Comment by leeoniya** [comment]
okay, i'm rethinking this.

_refs as objects actually has less flexibility than using strings. for example, with an object you cannot ref multiple nodes belonging to this object like "myObj123.qty" and "myObj123.price". in addition namespacing/ref structuring becomes impossible.

so rather than allowing refs to be objects, what's eeded is to get a unique string identifier to a persistent object. so we still need a Map or WeakMap, but more as a utility.

this can just be left up to the user. similar to the discussion/impl in #32 and generating uids in a weakmap held within the vm. the refs access semantics are also better just with hashes.

maybe leaving things the way they are is more beneficial.

**Comment by leeoniya** [comment]
fastclick has been removed.
_ref namespacing has been implemented as it's more valuable than the more limited object _refs

**Comment by iamjohnlong** [comment]
fyi I'm happy you went in this direction, the uses case is a lot cleaner. :+1:
