### ISSUE TITLE
Event emitter stops on first handler.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#41]
The event emitter stops at the first `vm` to define a handler for that event.

````
function emit(event) {
    var args = Array.prototype.slice.call(arguments, 1);

    var targ = vm;

    while (targ) {
        if (targ.events[event]) {
            u.execAll(targ.events[event], args);
            break; // <==
        }
        targ = targ.parent;
    }
}
````

However, it's not uncommon for handlers to apply finer-grained filtering to events and choose to take no action for specific reasons. 

A simple example is a key handler which only takes action for specific keys (say a filter-bar search box which is using key-down for debouncing) and allow the event to otherwise propagate (say to the filter-bar container which clears all filters on ESCAPE or immediately commits all filters on ENTER).

All GUI systems I've worked with allow the handler to indicate somehow that the event has been fully "handled" (i.e. to consume the event). With formal event objects this is typically by calling `evt.consume()`. With free-style event objects this is typically by returning `true` from the handler (less well defined and less clear without consulting docs).

Regardless, having first vm with a handler infer consumption is a serious limitation.

Am I to assume that if it chooses to forgo handling it is expected to re-emit that event? If so, what are the implications for event-loop race-conditions and other factors (like micro-tasks and execution order, etc). And the implications if multiple handlers at the same level forgo handling (which would re-emit the same event multiple times).

There are also semantics for multiple handlers at each level; I took the tack of executing all handlers, and then propagating the event up if none of them had consumed it.

**Comment by leeoniya** [comment]
before i read the entire issue, are you aware that this is NOT for dom event handlers? `emit` is meant to shuttle notifs & data up the view hierarchy.

dom events will bubble normally through the constructed dom until you return `false` from a handler. so everything you're saying about input handling will work normally.

i've found no need to have synthetic events hit multiple handlers on their way up. usually the events you emit() are very explicit and have specific handlers crafted for them. in the case that you really do have a deep tree where every node for some reason has identical handlers, then yes, the event should be re-emitted.

**Comment by lawrence-dol** [comment]
Ahh. Okay. I actually do recall reading about that distinction, but it had slipped my mind. In this case, yes the synthetic events will be handled by some single unknown party further up.

Mark this for docs review? (BTW, how are you doing that; I was expecting a label on the issue. It would be useful for myself and others to be able to see where the conceptual holes are in order to fill them.)

**Comment by leeoniya** [comment]
i'm adding them here: https://github.com/leeoniya/domvm/issues/36

you don't get notified cause i just edit the original comment.

this behavior is by design, and is already documented as such: https://github.com/leeoniya/domvm#synthetic-events-emit-on

**Comment by lawrence-dol** [comment]
That's the problem with pre-reading the docs with nothing to hang it on; you forget what's there and what's not. I am going to have to get in the habit of reviewing whats there *before* I open an issue. Sorry about this.
