### ISSUE TITLE
weekli demo (partial)

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#42]
Hey guys,

Added a partial 100-LOC implementation [1] \(source [2]\) of weekli [3]. It only covers the interesting parts with events and delegation. I didn't do any mediaquery listeners to flip it to a mobile layout or do anything like `divs` w/ `display: table` toggling. It does have an exposed api though, which it uses to pick some random hours on init.

Pretty happy with how the delegation semantics worked out. I was worried not being able to bind multiple `mousedown` handlers would be problematic, but turned out to be easily worked around as well as more optimal for perf.

[1] http://leeoniya.github.io/domvm/demos/weekli.html
[2] https://github.com/leeoniya/domvm/blob/master/demos/weekli.html
[3] http://collnwalkr.github.io/weekli/

--
@lawrence-dol @iamjohnlong @collnwalkr @barneycarroll @yosbelms

**Comment by iamjohnlong** [comment]
Passing the hash of selectors to bind events as: 

```js
var onMousedown = {
    "*":		function(e, node) { mouseIsDown = true; },
    ".day":		function(e, node) { toggleDay(node.data); },
    ".hour":	function(e, node) { toggleHour(node.data); },
    ".dayhour":	function(e, node) { setDayHour.apply(null, node.data); setSelected = node.props.class.indexOf("sel") == -1; },
};
```

Is this documented? That's pretty bad ass. Nice work man.

**Comment by leeoniya** [comment]
yeah, it's buried in the tpl reference, that thing is _dense_ with goodies :)

[1] https://github.com/leeoniya/domvm/blob/master/README.md#template-reference

**Comment by lawrence-dol** [comment]
Agree with @iamjohnlong.
