### ISSUE TITLE
Search a template to locate specific table cells and augment them

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#47]
Having just built a table template (e.g. below), is there a way I can safely and uniformly location particular cells and either augment or overlay their contents? I need to create input fields & text areas which are sized to overlay a rectangular area of cells in this table. I don't want to be depending on DOMVM internals which might change.

Ideally I'd do this by positioning the elements relative to top left of cell x,y and the bottom left of cell' x',y'. But I can't conceive of any way to position siblings relative to other siblings or their contents.

If I was dealing with the rendered DOM I'd tag the cells on interest and overlay the input fields. But, crucially, this must all happen in a single frame render since there must not be a flicker of display then display with inputs.

I am also trying to avoid creating several thousand VMs for each of the cells and avoid complicating the creation of base grid structure with the (quite numerous things that can augment it, include providing customers the ability to provide there own augmentation around this grid structure.

So, ideally I want an end result that can say "position this widget at row 3, col 7, width 10 cols height 2 cols, offset +/- n pixels.

````
function view(vm,mdl) {
    return function render() {
        var txt=mdl.text();

        if(txt.length==0) { return []; }

        var dsptxt=[ "table.display-panel", buildRows(vm,txt) ];

        // invoke customer supplied code here and get a list of augmenting objects
        // augment dsptxt cells here

        return dsptxt;
    };
}

function buildRows(vm,txt) {
    var arr=[];
    arr.push([ "tr.hidden",buildCols(vm,"th",txt[0])]);
    for(var xa=0,ln=txt.length; xa<ln; xa++) {
        arr.push([ "tr", buildCols(vm,"td",txt[xa])]);
    }
    return arr;
}

function buildCols(vm,typ,row) {
    var arr=[];
    for(var xa=0,ln=row.length; xa<ln; xa++) {
        arr.push([ typ, row[xa] ]);
    }
    return arr;
}
````

**Comment by leeoniya** [comment]
there are a few ways to get things done. let' start with the most obvious one first.

`dsptxt` is just a jsonml structure (which you have built, not relying on any vtree internals).

why not create a custom helper/locator function that simply walks `dsptxt` and mutates it as needed prior to returning it?

**Comment by lawrence-dol** [comment]
> `dsptxt` is just a jsonml structure

Doh. I am still in a Mithril mindset where `m` returned something Mithril built.

**Comment by leeoniya** [comment]
yeah, it's one of a few downsides of hyperscript...until some standard spec for vtrees arrives. one of several reasons for domvm using a somewhat standardized jsonml intermediate.

**Comment by lawrence-dol** [comment]
I am correct in my assumption that there's no way to calculate the position of any given cell, relative to the top/left of the container without rendering into the actual DOM, right? Which by any trickery will still cause a display flicker of at least one frame. 

I am trying to avoid resorting to a canvas, which I know from experience with the application I am replacing will result in a mountain of extra work and a loss in "free" customization from CSS.

**Comment by lawrence-dol** [comment]
> a somewhat standardized jsonml intermediate

I actually like the way the templates pan out... I am still just getting used to the implications.

**Comment by leeoniya** [comment]
> I am correct in my assumption that there's no way to calculate the position of any given cell, relative to the top/left of the container without rendering into the actual DOM, right?

right, unless you have fixed sizes for everything and can calc it yourself. the browser needs to run layout/reflow to get any measurements.

there are some tricks you can do, like temporarily set css to visibility: hidden, or position: fixed + huge negative margins to render the table off-screen.

however, absolute positioning + offsets seems like the wrong way to go here. why not just place the inputs inside the cells with width/height 100%? it's not like you're adding inputs to some foreign table...

perhaps i just dont see the bigger picture...

**Comment by lawrence-dol** [comment]
> why not just place the inputs inside the cells with width/height 100%?

That's loosely the current plan, but with some complications. The cell is just an anchor point and the widgets need to be able to cover multiple cells and be relatively offset by px/rem/em/etc. The primary difficulty is calculating the width and height for those that span multiple cells. Using 100% for that might entail deleting neighboring cells vertically and horizontally and adding row/col spans.

But I'm not looking for you to solve the problem, just making sure there's nothing in the bigger picture that makes it easier than I currently think it is.

**Comment by leeoniya** [comment]
yeah, it's a hard problem to solve in general and any solutions that actually overlay existing dom nodes have the fragility of layout changing out underneath them during scroll/resize or other expensive-to-recompute-and-redraw events.

the most robust solution would probably be to dynamically set rowspans/colspans and have your locator/augmenter take this into account, but again, without the big picture it's impossible to make any meaningful recommendations.

[1] looks like a good grid component if you're willing to ingest a 400-500k min lib D:

Interestingly, it carries a pikaday.js dependency [2].

[1] http://docs.handsontable.com/0.17.0/demo-merge-cells.html
[2] https://github.com/handsontable/handsontable/tree/master/dist

**Comment by lawrence-dol** [comment]
Yeah, it's nice, but I have a 200 to 500 K *total* app goal, including CSS and images. And I need total control over the augmentation. This is all going to be hand-rolled and lean on CSS as much as possible.

**Comment by lawrence-dol** [comment]
> declarative and arbitrary parametric constraints

Indeed. I consider the design of CSS (not the concept) to be one of the biggest fails in recent software history.

**Comment by leeoniya** [comment]
At least we finally have `flexbox`, `box-sizing: border-box`, insanely fast js engines and evergreen browsers. The horrors of IE6/7 dev are becoming repressed memories.

**Comment by lawrence-dol** [comment]
The world today is definitely more palatable than that of 10, even 5 years ago.

I'm reading the white-paper for CCSS now.

**Comment by lawrence-dol** [comment]
It may be of interest to anyone reading this thread in the future that the solution was in the end very simple simple: Each cell is relative, each enhancement object is then absolute positioned in the origin cell with width/height of `(n*100)+"%"` where `n` is the number of rows or columns to span and z-order is +1.

**Comment by leeoniya** [comment]
wouldnt this only work when you have uniform/fixed cell widths/heights?

**Comment by lawrence-dol** [comment]
Yes, which is what I do have. But that's a good point to note; again my context is coming from my particular problem space. It's a fixed-cell layout grid, where the cells change size, adapting to the viewport, but each cell is uniform width and height.

**Comment by leeoniya** [comment]
that "detail" is the difference between needing a 200k slow and non-obvious solution and a 0.2k obvious and fast one :D

**Comment by lawrence-dol** [comment]
Yeah, you overlook the details sometimes when you're in the process of re-imagining a 70 KLOC Java GUI program as a brand new concept within the browser.
