### ISSUE TITLE
The ambiguity of simple text first-child of element.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#51]
Sorry, but this inconsistency/restriction is really nagging at me. This is important because in the post-processing of a v-tree, consistency makes things remarkably easier to do and reason about.

Given this:

````
["textarea", {rows: 50},[           // Array may be a node or children list...
    "text",                         // this is ambiguous: element or text?
    ["br"],                         // this is unambiguously an element
]]
````

Why is this ambiguity not resolvable without concat by simply including a null or undefined first element?

````
["textarea", {rows: 50},[           // Array may be a node or children list...
    null,                           // ... but a node name can't be null.
    "text",                         // So this is now unambiguously text, no?
    ["br"],                         // And this is still unambiguously an element
]]
````

Would that not be syntactically consistent and more coherent than concat?

The other possibility is to require that contents always be an array (though, no doubt this is the reason for your perception of bracket-soup). The bracket-soup argument doesn't seem to hold much merit to me because we already have bracket-soup and a fully regular and consistent maze of brackets will be consistently easier than one with some of the brackets optional and with surprising results (like unnecessary ambiguity):

````
["textarea", {rows: 50},["br"]]     // "br" can be assumed to be text
["textarea", {rows: 50},[["br"]]]   // "br" must be an element

["textarea", {rows: 50},            // Not valid; third element must be an array
    "text",                         // ... if it's included at all
    ["br"],                         
]

["textarea", {rows: 50},[           // Must be a children list...
    "text",                         // Therefore this is unambiguously text?
    ["br"],                         // Unambiguously an element with no content
]]
````

Thoughts? The `null` fits with current templates; the child-array-always is more rigorously consistent.

**Comment by leeoniya** [comment]
The `null` first element workaround works well already [1].

I'm evaluating moving to Hyperscript from JSONML for 2.x, which would emit vnodes directly and have stricter sigs (single arg valueOrArray body): `h(tag, props, body), h(tag, body), h(tag, props), h(tag)`. And maybe another for views `v(viewFn, model, handle, opts)`. It depends on how much benefit there will be for speed and GC pressure. The point is to reduce extra heap allocations by not having a memory-hungry initial representation and to let the user be more aware and in control of any perf/mem penalties paid. A lot of internal checks and secondary passes in the lib could be done away with if the incoming structure was uniform.

These helpers will emit a uniform vnode object tree which you could patch before returning it from `render()` and domvm will ingest directly. Currently you don't really have access to the vtree until after the init.

This will not require a bottom-up rewrite of the lib or any changes to the API (aside from mechanical template conversion). For your application it may mean having to additionally modify some of your post-processing code by working directly on a uniform but un-injected vtree branches. I remember you saying you didn't want to rely on the internals, but this would be a decent middle ground.

[1] https://jsfiddle.net/L2hz0g3g/

**Comment by lawrence-dol** [comment]
I'm fairly neutral on the HS vs JSONML in my code; I patched the functions you have above and the resulting templates were negligibly different and I ended up on the fence. The `null` work-around combined with a children array gives me the uniformity I desire.

I am not fussed about making mechanical changes to my view generators should this ever change. Though a cross-over period of supporting both would assist if that's possible. Or, more likely a compatible set of functions in 1.x so we can change templates before transitioning to 2.x. 

I assume these would all be in the view-model? So `vm.h("br")` and so on.

It does sound like it would be helpful in reducing size and increasing efficiency in DOMVM. So worthy of consideration. The size aspect might be a wash.

One negative I did encounter was that I now had to inject `vm` into some helper functions that simply return view fragments and heretofore did not need it. I was tempted to put `h` and `v` functions into my app's global namespace for this reason.

**Comment by leeoniya** [comment]
> I'm fairly neutral on the HS vs JSONML in my code

This is not about ergonomics at all but 100% about perf/mem. By handling the real vnodes, you could do a lot more, like set up a caching layer that avoids regenerating them and simply re-return them, etc. In addition a lot of checks can be bypassed and every node will not require both an array and object allocation. There's at least a 50% mem useage decrease and hopefully less GC jank and more perf. Time (and testing) will tell.

> Though a cross-over period of supporting both would assist if that's possible. Or, more likely a compatible set of functions in 1.x so we can change templates before transitioning to 2.x.

Supporting both in the same codebase is probably not realistic. Some helper functins could be made but they would be so simple that having to insert them would be the same effort required just to change the templates over. For a transition that'll be purely mechanical, it's probably not worthwhile.

> I assume these would all be in the view-model? So vm.h("br") and so on.

No.

> I was tempted to put h and v functions into my app's global namespace for this reason.

Yes, `v` is just the existing `domvm.view()` and `h` would be `domvm.view.node()`.

**Comment by leeoniya** [comment]
gonna close this.

this won't happen in 1.x, since requiring child arrays will break existing code and there's no way to differentiate templates that adhere to this from ones that don't.
