### ISSUE TITLE
autofocus works on hard refresh (ctrl-f5) but not on soft f5

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#52]
I have, for only the first field in my display:

````
[
    "input.field.text", {
        style                       : { height: fld.rHeight+"00%", width: "calc("+fld.rWidth+"00% + 12px)" },
        maxLength                   : fld.length,
        autocomplete                : "F"+fld.sCol+"-"+fld.eCol+"-"+fld.length,
        autofocus                   : true,
    },
]
````

DOMVM renders (noting `autofocus=""` on the first field instead of `autofocus`):

````
<input class="field text" autofocus="" autocomplete="F3-3-1" maxlength="1" style="height: 100%; width: calc(100% + 12px);">
...
<input class="field text" autocomplete="F7-79-73" maxlength="73" style="height: 100%; width: calc(7300% + 12px);">
````

It doesn't work in setting focus to the field.

**Comment by leeoniya** [comment]
domvm does the correct thing here [1]. it doesnt construct the html string anyway but uses a normal setAttribute() call.

why autofocus doesnt work is another question that'll need to be figured out. it probably has to do with `redraw()` being wrapped in a requestAnimationFrame() call internally.

does anything change if you first set `domvm.view.config({useRaf: false})`?

[1] http://www.w3.org/TR/html-markup/syntax.html#syntax-attr-empty

**Comment by leeoniya** [comment]
you can work around this for the time being in a didRedraw hook, a _ref and a .focus() call

**Comment by lawrence-dol** [comment]
> does anything change if you first set...

No. It only seems to acquire focus when I CTL-F5; plain F5 never works and with control it seems to work about 99% of the time.

It doesn't matter in the long run, because I will need to specifically set focus as new data comes in from the host; using autofocus was unlikely to survive anyway. I thought this might indicate a bug in boolean attribute setting [1].

[1] Another thing I can't believe got past standardization: `abc` == true, `abc=""` == true, `abc="true"` == false, `abc="abc"` == true!?

**Comment by leeoniya** [comment]
yeah, the spec makes a Piccaso [1] look uniform by comparison. so goes design-by-committee.

[1] https://s-media-cache-ak0.pinimg.com/236x/49/2c/de/492cde9177cdbc3335ff49546e8a8b79.jpg

**Comment by lawrence-dol** [comment]
This is one area where I need a DOM element reference to request focus for the field. I am presuming a `_ref` and a `setTimeout` or `tick` will accomplish that?

**Comment by leeoniya** [comment]
you could use `tick` by itself or any `did*` hooks (which are all ticked).

**Comment by lawrence-dol** [comment]
Using `autofocus` is unreliable at best, and doesn't work for routing and other view changes. It was much simpler to simply implement:

````java
genU.defer(function() {
    vm.refs[firstFldRef].el.focus();
    });
````
