### ISSUE TITLE
new: subview redraw optimization

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#54]
Subviews can now return `false` instead of a template from `render()` to indicate "no changes", à la React's `shouldComponentUpdate`.

This results in a large reduction in heap allocations and significant perf increase if you can do your own cheap data caching & diff. A primary use case is any SPA where many large & expensive sections/tabs are "inactive" and can be ignored during redraws.

I was looking for ways to optimize the 1%-mutations dbmonster case and realized that the mutations happen at row level rather than cell level. This meant that i could simply cache and do `oldRowData === newRowData` and avoid a ton of tpl/diff/patch work by short-circuiting their redraws.

The numbers are (on my laptop):
- 2.1x perf at 1% mutations (70fps vs 145fps)
- 1.2x perf at 50% mutations (30fps vs 35fps)
- 0.95x perf at 100% mutations (27fps vs 25.5fps)

You can see the optimized dbmonster at [1]. It only involved creating a tiny caching/diffing sub-view and cutting-pasting the row template into it.

The regression at 100% is because subviews carry a slight overhead which becomes measurable with high sub-view counts. This is known and needs more investigating as it's not obvious where the overhead accumulates.

Originally I planned to do this via a `false` return & redraw prevention from `willRedraw` hooks, but relying on hooks is more expensive and clunkier to set up.

[1] https://github.com/leeoniya/domvm/blob/1.x-dev/test/bench/dbmonster/app.js
## 

@lawrence-dol @iamjohnlong

**Comment by lawrence-dol** [comment]
I have a use-case for this in my current project; thanks. Will have to implement it as soon at the opportunity presents.

**Comment by leeoniya** [comment]
One thing to remember in the active/inactive scenario is to run something like `vm.patch(vm.node, {class: "inactive"})` before returning `false` for the first time to actually hide the newly-inactive subview. the view template itself can just always render the class based on the app state `["section.tab", {class: tab.state}, ...]`

**Comment by lawrence-dol** [comment]
This seems not to work. I get an exception whenever I try to return `null`:

````
20:27:25.908 TypeError: raw.length is null
procNode() AppScript;01:204
initNode() AppScript;01:136
redraw() AppScript;01:106
moveTo() AppScript;01:97
buildNode/<() AppScript;01:160
forEach() self-hosted:208
buildNode() AppScript;01:158
redraw() AppScript;01:113
call() AppScript;01:81
1 AppScript;01:204:15
````

**Comment by leeoniya** [comment]
implemented viewport occlusion culling in dbmonster [1]; we are now at ludicrous speed [2] D:

@trueadm time to up your `lazy` game :) feel free to steal code.

[1] https://github.com/leeoniya/domvm/commit/f53f1fcc871590413b005e1b2de60fe5ce3006bb
[2] https://www.youtube.com/watch?v=ygE01sOhzz0

**Comment by trueadm** [comment]
@leeoniya Inferno does not use occlusion culling. It's dangerous and completely unusable in many use-cases. Inferno still renders and updates items out of viewport, it just staggers their update.

**Comment by leeoniya** [comment]
ah, carry on then :)

> It's dangerous and completely unusable in many use-cases

can you clarify when it is dangerous?

**Comment by trueadm** [comment]
@leeoniya If you avoid patching something off-screen, it can have detrimental effects. For example, custom elements, videos, iframes, audio, lightboxes/dialog boxes. Furthermore, what if any of those elements gets removed from the DOM? You're not patching them, so you aren't removing them either.

Viewport occlusion was the hot thing years ago, even Angular had a go at it. It was deemed a waste of time due to the amount of edge cases it brought with it. I recommend you read up on the new React layout engine that Seb is working on: https://github.com/facebook/react/issues/6170.

**Comment by leeoniya** [comment]
@trueadm

> Furthermore, what if any of those elements gets removed from the DOM?

> even Angular had a go at it. It was deemed a waste of time due to the amount of edge cases it brought with it

Right, as my edit mentions, this is absolutely not applicable in the general case. However, for user-space apps where you have certain knowns (such as the dbmonster bench), it can yield much better results than the best general-case optimization.

I'm not about to use this version for perf comparisons or to make claims without a huge disclaimer. I should probably split off the 3 versions into `naive`, `db-immut`, `db-immut + culled`.

The `New Core Algorithm` thread is nearly void of details. I've subscribed to it though. Anyways, thanks for chiming in.

**Comment by trueadm** [comment]
@leeoniya Do you have URL for your culling benchmark for me to test?

Also that's a very naive assumption. 85%? How did you work out that figure. I'd honestly say less than 15% given the fact that `getBoundingClientRect` will break as soon as you add CSS3 transformations, static positioning or sticky positioning to the picture.

React want to own the entire styling spectrum within React. No CSS, no SASS, everything is handled by React via inline styles. That means React can know everything about styling – the exact reason why this stuff is prone to breaking.

**Comment by leeoniya** [comment]
@trueadm 

> Do you have URL for your culling benchmark for me to test?

It's up on gh-pages: http://leeoniya.github.io/domvm/test/bench/dbmonster/

That being said, Inferno can get close to these speeds without any special user-space optims, but I was curious how it would do if culling was *also* added :)

> Also that's a very naive assumption. 85%? How did you work out that figure.

In my experience, the overwhelming majority of interfaces is 85% static (at least various admin UIs). If we start talking heavy animations, games streaming huge quantities of data. Then I think vdom/diffing frameworks are the wrong technology for the task given that we have Canvas and WebGL and imperative/dedicated SVG libs, Web Workers, asm.js, WebAssembly, JITs. Again, IMO.

> given the fact that getBoundingClientRect will break as soon as you add CSS3 transformations, static positioning or sticky positioning to the picture.

This is interesting, will need to investigate.

> React want to own the entire styling spectrum within React. No CSS, no SASS, everything is handled by React via inline styles. That means React can know everything about styling – the exact reason why this stuff is prone to breaking.

This makes a lot of sense in the context of React Native, but maybe not so much from an HTML5 perspective, me thinks.

**Comment by trueadm** [comment]
@leeoniya Web workers make a negative impact in most cases, not until shared buffers come into play will they give decent performance in things like animation and rendering. There's far too much overhead in communication between workers.

WebGL is no replacement for the DOM. One day I wish, but then you'd have to drop many of the things that people love – CSS, SVG, Video, Canvas, proper font rendering etc. I've gone down that route already and it's not ready yet.

Inferno is already a JIT friendly library, about on-par now with Kivi (minus stateful components, but you can use stateless components with much better performance).

It's an interesting space to be in really. Lots of progression. I'm happy that Inferno has been leading the pack and others have been copying too, including React. That's the great thing about OS.
