### ISSUE TITLE
Idiomatic way to set model value to match value of input?

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#55]
Is there a recommended or idiomatic way to make a value in the model always reflect the value of an input field?

I know I can do something like:

    ...
    onkeypress: function(evt) { model.value=evt.target.value; }
    oninput:    function(evt) { model.value=evt.target.value; }
    onchange:   function(evt) { model.value=evt.target.value; }
    ...

But is there a better way? For example, the scoreboard demo makes use of `vm.refs`, but that is not desirable in my case because the machine generated fields are not named.

When I create the corresponding input from the field model, I want to immediately link the model's value to the input field in such a way that any change to the input field immediately updates the model without doing a redraw. It is not necessary to link in the other direction, though if I did I assume changing the model and redrawing would do the job.

In Mithril I would have used `m.withAttr`, but before I recreate that I want to be sure that DOMVM hasn't solved the problem better.

**Comment by leeoniya** [comment]
there's something like `m.withAttr`:

`watch.sync`: https://jsfiddle.net/kztsdapm/1/

**Comment by leeoniya** [comment]
btw, i wasn't aware that `oninput` was a standardized thing, i thought it was something specific to Mithril, like jQuery's focusin was back in the day. good to know.

**Comment by lawrence-dol** [comment]
Will `w.sync` handle the situation when it's changed in order to sync it with the input value (i.e. I type in the input triggering the input event) that it won't trigger a redraw? Since the value is being synced to the DOM value, the DOM does not need to be updated. All I want to do is ensure that the model is kept in sync with user input so that if a redraw happens for other reasons and the input is recreated it will have the correct value.

**Comment by leeoniya** [comment]
`w.sync` triggers your `watch` handler after invoking the getter & setter. nothing in `watch` module invokes redraw, it only ever fires your passed-in handler (if you've provided one).

**Comment by leeoniya** [comment]
eg: https://jsfiddle.net/krsd2aj0/2/

```js
function GridView(vm, grid) {
	function onCellInput(e, node, vm) {
		var rc = node.data.split(":");
		grid[rc[0]][rc[1]] = e.target.value;

		console.log(JSON.stringify(grid));
	}
	
	return function() {
		return ["table", {oninput: onCellInput},
			grid.map(function(row, r) {
				return ["tr",
					row.map(function(cell, c) {
						return ["td",
							["input", {value: cell, _data: r+":"+c}]
						]
					})
				]
			})
		]
	}
}

var grid = [
	[123,456],
	[789,095],
];

domvm.view(GridView, grid).mount(document.body);
```

**Comment by lawrence-dol** [comment]
Yep OK. So I can just write a special `prop` get/set function that accepts a special flag that tells it whether it's being updated as a result of the event or externally. Then I can trigger redraw when external, and not when from the event (I don't want to redraw for fields where the model is just tracking the input value and has no effect anywhere else in the view).

I am really quite liking the "just write the obvious code" with DOMVM; seems to do exactly what I want, no more, no less.

Isn't `oninput` nice?!

**Comment by lawrence-dol** [comment]
> w.sync triggers your watch handler after invoking the getter & setter.

Light bulb moment; I already have a utility "prop" function that does exactly that whenever a property is set so that I can take action "on change".

**Comment by leeoniya** [comment]
> Then I can trigger redraw when external, and not when from the event

both `w.sync` and `w.prop()` are already capable of preventing the handler from firing (or firing an alternate callback) and you can pass a `w.prop()` into it for the `w.sync`'s setter + `false`.

it doesnt work elegantly for delegated versions because which `w.prop` you need to set is dynamic, i'll ponder it and get back to you.

**Comment by leeoniya** [comment]
got it working nicely with delegation: https://jsfiddle.net/krsd2aj0/11/

explicit `w.prop()` setting (via button) invokes redraw(), while `w.sync` only sets the model data (and prevents handler firing via `false`). see console.

the changes are not pushed to the repo yet, give me a few hours.

**Comment by leeoniya** [comment]
pushed.

**Comment by lawrence-dol** [comment]
Thanks, that's nice. And, yeah, I don't overuse get/set properties.
