### ISSUE TITLE
Trouble recreating the view when model changes

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#56]
I have a view component with private state, which I want to be recreated whenever a particular model value is changed. I've tried using the documented key, but that does not cause the view to recreate.

Right now I am fudging my check within the render function, but that seems clumsy and wrong:

```js
// PARENT VIEW'S RENDER (WANT THE HOST MODEL DISPLAY SERIAL NUMBER TO TRIGGER
// RECREATION

    return function render(vm) {
        return [ "div.temjs", atr, [
            [ dsppnl.view,hstmdl.display()/*,hstmdl.serialNumber()*/ ],
            [ stspnl.view,hstmdl.status () ],
        ]];
    };


// SUBCOMPONENT VIEW

exported.view=view;
function view(vm,hstdta) {
    var txt=hstdta.text();
    var cls=hstdta.cellClasses();
    var srl=undefined;

    if(txt.length==0) { return []; }

    return function render() {
        // THE SERIAL NUMBER IS THE KEY THAT SHOULD CAUSE THE VIEW RECREATION
        if(srl!==hostSystemModel.serialNumber()) {
            displayGrid=buildGrid(vm,txt,cls);
            hstdta.fldList().forEach(function(fld,idx,arr) {
                cell(fld.sRow,fld.sCol,field(fld,idx,arr,cls[fld.sRow-1][fld.sCol-1]));
            srl=hostSystemModel.serialNumber();
            });
        }
        // ^^^^^^^^^^^^^^^^^^^

        var dspbdy=[
            "div.display-box",{
                oncopy                  : recordScreen,
            },[
                ["div.display-background"],
                ["table.display-panel.C"+hstdta.dspCol(), displayGrid],
            ],
        ];

        return dspbdy;
    };
}
````

**Comment by leeoniya** [comment]
seems to work for me: https://jsfiddle.net/u2ptsmqq/1/

can you make a functional jsfiddle that shows exhibits the problem?

**Comment by lawrence-dol** [comment]
I've screwed something else up that I'll need to resolve first before I can get back to this specific issue, but it looks like this is a side-effect of that.

**Comment by lawrence-dol** [comment]
It is working to rebuild the view, as you have in your example fiddle; the other problem was causing wonky out of sync behavior which I've now fixed.

But even though it rebuilds as expected when the model data is changed, after the first correct display, it falls over with a TypeError in `hydrateNode` from an undefined _node:

````
16:10:49.421 TypeError: sibAtIdx._node is undefined
hydrateNode() AppScript;01:169
hydrateNode() AppScript;01:172
redraw() AppScript;01:114
call() AppScript;01:81
1 AppScript;01:169:79
````

The code from line 169 and 172 is:

````
function hydrateNode(node,withEl,sibAtIdx,parentEl){var wasDry=!node.el;while(sibAtIdx&&sibAtIdx._node.removed)
sibAtIdx=sibAtIdx.nextSibling;wasDry&&fireHook(node.vm,"willMount",node.vm);if(node.type==u.TYPE_ELEM){if(wasDry){node.el=withEl||(node.ns?doc.createElementNS(NS[node.ns],node.tag):doc.createElement(node.tag));node.props&&patchProps(node);}
if(u.isArr(node.body)){for(var i=0,nextSib=node.el.firstChild;i<node.body.length;i++)
nextSib=hydrateNode(node.body[i],null,nextSib);}
````

I'll dig more and try to replicate in a fiddle if I can't solve it soon. The weird thing is if I just move the code that's in the VM init, which only processes the host data, it all works. But that code produces (should produce) an identical result from any given host data. I'll verify that next.

**Comment by leeoniya** [comment]
if `sibAtIdx` is undefined, it means the expected amount of children in the old vtree vs the actual dom does not match. i'll def need to have a reproducible test case to look into this further.

**Comment by lawrence-dol** [comment]
Is there anything I can do in my code to cause that? Which I should look for first. Redraws where the model doesn't change work as expected.

And I take back the bit about moving the view init code; this exception trips regardless of where I have that code, and always when the model changes.

Just FYI, here is the current view code:

````
function view(vm,hstdta,hstsrl) {
    var txt=hstdta.text();
    var cls=hstdta.cellClasses();
    var srl;

    if(txt.length==0) { return []; }

    displayGrid=buildGrid(vm,txt,cls);
    hstdta.fldList().forEach(function(fld,idx,arr) {
        cell(fld.sRow,fld.sCol,field(fld,idx,arr,cls[fld.sRow-1][fld.sCol-1]));
        });

    /**/console.log("[**] rebuild",srl,hostSystemModel.serialNumber());
    return function render() {
        /**/console.log("[**] render:",srl,hostSystemModel.serialNumber());
        if(srl==hostSystemModel.serialNumber()) {
            return false;
            }
        srl=hostSystemModel.serialNumber();

        var dspbdy=[
            "div.display-box",{
                oncopy                  : recordScreen,
                },[
                ["div.display-background"],
                ["table.display-panel.C"+hstdta.dspCol(), displayGrid],
                ],
            ];

        return dspbdy;
        };
    }
````

**Comment by leeoniya** [comment]
if you're not modifying the dom structure or vtree manually, app code should never be able to cause a sibAtIdx error.

the lib's vtree somehow gets out of sync with the real dom. maybe it incorrectly removes an unrenderable node or splices something out prematurely. it thinks there are more live dom nodes because the vtree is larger than the real thing.

i really cannot give you any more insight without seeing a test case to debug :(

**Comment by lawrence-dol** [comment]
> if you're not modifying the dom structure or vtree manually, app code should never be able to cause a `sibAtIdx` error.

I'm not. This one's going to be fun. However it was working a couple of days ago, *after* updating to DOMVM 1.1.0, so there's *something* in my code tripping it. So I am going to work forwards from the last working state with Git and find out *what* buggered it. That should shed light on *why*.

**Comment by leeoniya** [comment]
@lawrence-dol any news?

**Comment by lawrence-dol** [comment]
Not yet. But it's my sole focus today. My first attempt to code-review the changes using Git failed. Unfortunately, (a) the project is a stage where constant refactoring happens as I fix design flaws, and (b) I went for 12 hours straight without doing a single commit so I have a lot of changes between when it worked and when it broke, including the significant unrelated breakage which masked this problem. So for the next few hours I'll be remaking all the changes from the last working state until I find the one that causes this problem specifically, starting with the simple refactors to reduce the noise when the real problem surfaces.

I'll have the trigger isolated pretty soon.

**Comment by lawrence-dol** [comment]
I have pinned down what triggers the exception. It's the addition of the key value to the second of my two top-level components.

Succeeds:

    return function render(vm) {
        return [ "div.temjs", rooatr, [
            [ dsppnl.view,hstmdl.displayData(),hstmdl.serialNumber() ],
            [ stspnl.view,hstmdl.statusData ()                       ],
            ]];
        };

Fails:

    return function render(vm) {
        return [ "div.temjs", rooatr, [
            [ dsppnl.view,hstmdl.displayData(),hstmdl.serialNumber() ],
            [ stspnl.view,hstmdl.statusData (),hstmdl.serialNumber() ],
            ]];
        };

This is completely unexpected. With the changes replicated to this point, the exception is non-fatal, in that my application still seems to work. So I will continue remaking the remaining changes and see if that part changes.

**Comment by lawrence-dol** [comment]
OK, now I have the key. It's the addition of the serial number to *both* sub-views that causes things to be fatal. So...

Works:

    return function render(vm) {
        return [ "div.temjs", rooatr, [
            [ dsppnl.view,hstmdl.displayData() ],
            [ stspnl.view,hstmdl.statusData () ],
            ]];
        };

Non-fatal exception in console:

    return function render(vm) {
        return [ "div.temjs", rooatr, [
            [ dsppnl.view,hstmdl.displayData(),hstmdl.serialNumber() ],
            [ stspnl.view,hstmdl.statusData () ],
            ]];
        };

Fatal exception in console:

    return function render(vm) {
        return [ "div.temjs", rooatr, [
            [ dsppnl.view,hstmdl.displayData(),hstmdl.serialNumber() ],
            [ stspnl.view,hstmdl.statusData (),hstmdl.serialNumber() ],
            ]];
        };

This is working with the first sub-view initializing the unchanging parts derived from the host model every time. If I want that, I need the key argument so it knows when to rebuild the vm rather than just re-render.

**Comment by leeoniya** [comment]
thanks for the research.

this is odd. the lib uses the unique combo of viewFn+key to do the diffing, so assigning the same key should work fine as long as the viewFns are different. lemme run a test....

**Comment by leeoniya** [comment]
@lawrence-dol

still cannot reproduce, looks like a failing demo will still be needed :(

Here's a version with differing sibling sub-views that are keyed by the same serial working without issue:

https://jsfiddle.net/u2ptsmqq/3/

**Comment by lawrence-dol** [comment]
Never fear; I'll dig further as soon as I have my app all caught up. I have a crude work-around that works, but I want to leverage this part. And experience has taught me you pursue this kind of thing while you have code that will replicate it or it will come back to bite you at the worst possible time.

**Comment by lawrence-dol** [comment]
No luck replicating the problem yet. I am going to build up a view that matches what I produce in my app and see if it's the dom complexity that trips up.

**Comment by lawrence-dol** [comment]
No luck yet. Tomorrow I'm going to try the opposite approach by cutting out code until I can pinpoint what the magic bit is that makes the difference.

My views are pretty boring, though the resulting tree is a few thousand elements.

**Comment by leeoniya** [comment]
@lawrence-dol

> PS: I am finding DOMVM much more intuitive than Mithril so far. I'm actually looking forward to working on the docs after I get this product to the customer and have some breathing room.

If you'd like to say a couple words about your domvm experience on this Reddit thread [1], I would not be opposed ;)

[1] https://www.reddit.com/r/javascript/comments/4ft52t/domvm_v11_a_fast_isomorphic_view_layer_router_in/

**Comment by lawrence-dol** [comment]
@leeoniya : No problem.

https://www.reddit.com/r/javascript/comments/4ft52t/domvm_v11_a_fast_isomorphic_view_layer_router_in/d2c05bt

**Comment by lawrence-dol** [comment]
OK, I've finally got a SSC program in JS fiddle that fails:

https://jsfiddle.net/LawrenceDol/5znu9u0b/

Pressing any key will render, changing counts. Pressing PageUp or PageDown changes the key and immediately fails with the aforementioned exception.

What's really weird is that simply moving the code from script tags and into the jsfiddle code pane does not exhibit this problem. (cf. https://jsfiddle.net/LawrenceDol/5znu9u0b/26/)

Code is:

````
<div>This application requires JavaScript to work.</div>
<script src="https://cdn.rawgit.com/leeoniya/domvm/1.x-dev/dist/domvm.min.js"></script>
<script>
var AppMain=function()
{
"use strict";

let key=0;
function RootView(vm) {
    function keyDown(evt) {
        console.log(evt);
        let nam=(evt.key || evt.code);
        if(nam=="PageUp"  ) { --key; evt.preventDefault(); }
        if(nam=="PageDown") { ++key; evt.preventDefault(); }
        vm.redraw();
    }

    return function() {
        console.log("[**] RootView render",key);
        return [ "div", { onkeydown: keyDown }, [
            [ SubView   ,{ test: "Test Model" },key ],
        ]];
    };
}

function SubView(vm,mdl) {
    let cnt=0;
    return function() {
        console.log("[**] SubView render");
        return ["div.test", JSON.stringify(mdl)," :: ",key," :: ",++cnt];
    };
}

domvm.view(RootView).mount(document.body,true);
return {};
};

new AppMain();
</script>

````

**Comment by lawrence-dol** [comment]
Ahh, changing the jsfiddle JavaScript option from "onload" to "No Wrap - In <body>" causes it to fail when the code is in the script pane too.

https://jsfiddle.net/LawrenceDol/5znu9u0b/28/

**Comment by leeoniya** [comment]
> @leeoniya : No problem.

thanks!

> Ahh, changing the jsfiddle JavaScript option from "onLoad" to "No wrap - in " causes it to fail when the code is in the script pane too.

wow, no wonder i haven't run into this, what a convoluted issue. though likely trivial to fix now. will look into this soon.

**Comment by leeoniya** [comment]
ok, i understand the problem. here's the situation...

When you use `.mount(elem, true)`, domvm first clears the contents `elem` by setting `textContent` to an empty string [1]. In the case when the `<script>` is within the target element itself, you start with this:

```html
<body>
  <script>
    ...
  </script>
</body>
```

and end up with this after it executes, because it cannot clear the empty newline/textnode which has not been streamed yet after the last script tag:

```html
<body>

</body>
```

but not this, as you'd expect:

```html
<body></body>
```

this leads to a target element which contains

```html
<body>
<div id="myApp">...</div></body>
```

rather than

```html
<body><div id="myApp">...</div></body>
```

So the leading textNode remains in the dom and does not match the vtree. So you can get various `sibAtIdx` errors, etc.

Why this error triggers on some keys but not other keys is quite odd and maybe worth investigating separately.

Now for some solutions. First a couple simple workarounds:

1. If you want to keep the script in the body, make sure there's no whitespace between your `<script>` and `<body>` tags.
2. Wrap your `mount(targ, true)` code in `DOMContentLoaded` handler. This way the entire body can be replaced via `textContent`, not just body-up-to-that-point: https://jsfiddle.net/5znu9u0b/29/

I'm not sure there's much I can do in the lib to circumvent this issue, I think it will just need to be documented.

[1] https://github.com/leeoniya/domvm/blob/1.x-dev/src/view.js#L116

**Comment by lawrence-dol** [comment]
I consider this issue resolved, but it should be tagged for revisiting for documentation purposes. It's quite the subtle trap.

**Comment by lawrence-dol** [comment]
I've elected to just use a standard HTML for my apps with a the DOMContentLoaded:

````
<!DOCTYPE HTML>

<html>
<head>
    <title>My DOMVM App</title>
</head>

<body>
    <div>This application requires JavaScript to work.</div>

    <script src="AppScript;01"></script>
    <script>
    // ensure HTML is fully parsed before replacing body
    document.addEventListener("DOMContentLoaded", function() {                                      
        new AppMain({
            // config here
            });
        });
    </script>
</body>
</html>
````

This might be a useful addition to the docs when we get there.

**Comment by leeoniya** [comment]
btw, Github's highlighting works like this:

```
    ```html
    <body></body>
    ```

    ```js
    var x = "";
    ```
```

**Comment by lawrence-dol** [comment]
Cool. I didn't know that.
