### ISSUE TITLE
Clarification: Accessing the DOM and potential for memory leaks

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#58]
More of a clarification for later documentation...

Do DOMVM apps inherently avoid most causes of memory leaks in JavaScript by avoiding cyclical links between DOM and the JavaScript code, or is `_ref` something to be careful using?

I am at the point where I need to do some interrogation of DOM attributes, where I generally prefer to attach events to the component and then walk the DOM relative the event target if I need to, rather than attaching a handler to every one of 3.8K cells in a grid.

What's the idiomatic recommendation for interacting with the DOM elements? I do not expect to store references to any DOM nodes in my application state.

**Comment by leeoniya** [comment]
The `vm.refs` object is destroyed and recreated on every redraw. The refs get re-collected on every vtree rebuild/reuse. So just avoid storing direct DOM node references (as they can be removed or reused and no longer represent what you expect). Also avoid aliasing and storing `vm.refs`, e.g. `var r = vm.refs` since this will prevent the GC from cleaning those up.

Other than that, i can't think of anything else to avoid.

**Comment by leeoniya** [comment]
> I am at the point where I need to do some interrogation of DOM attributes, where I generally prefer to attach events to the component and then walk the DOM relative the event target if I need to, rather than attaching a handler to every one of 3.8K cells in a grid.

You can also write a custom node locator that walks the vtree to get to the cell you need. And accessing its `.el`. In the case of several thousand cells there might be a perf benefit to this, but it's hard to say without knowing the exact situation.

If you do find a memory leak (not impossible), then let me know. There always the possibility of internal oversights, like old vtree references, etc.

**Comment by lawrence-dol** [comment]
> what are the specifics of this? ... you dont need to touch the DOM or set attributes.

I am not manipulating the DOM at all; just tagging parts with data that I later use. In this specific case I am tagging each cell with it's logical row/column so I can reflect the row/column in a status bar when a cell is clicked. I'll need to do something similar on focus so that I can do the same. It's just something 5250 users like to do. 

In addition there is context sensitive help on the host that requires knowing what cell the cursor is logically in when the help key is pressed.

What advantage does `_data` offer over just setting a `data-xxx` attribute?

**Comment by leeoniya** [comment]
> What advantage does _data offer over just setting a data-xxx attribute?

well, there is no setAttribute calls (domvm does not handle  setting el.dataList internally), also _data can contain non-string values, like objects/arrays.

**Comment by lawrence-dol** [comment]
Cool. How do I access the `_data` on the element?

**Comment by leeoniya** [comment]
`node.data`

**Comment by lawrence-dol** [comment]
That's nice; implemented using `_data`.

**Comment by leeoniya** [comment]
this is in the docs todo already, i added a bit to mention not holding refs
