### ISSUE TITLE
Redraws should always be, async, queued and coalesced.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#60]
I want to make the argument that telling a DOMVM vm to "redraw" is really telling it that one of the models on which it depends has been updated and that it needs to redraw at the end of the current event cycle. It is nothing more than an indication that the view is now out of step with the model.

If it lies within DOMVM's power to make it easy to request a redraw instead of redrawing inline it absolutely should do so, rather than have every application reinvent some kind of coalescing/deferred-redraw logic.

For example, if an event causes 17 different model properties to change, it should not execute the redraw code 17 within that even handler; it is necessary only to do it once. 

As well, immediately changing the view often results in counter-intuitive behavior per below.

Here is a fiddle based on the test branch for #57 that doesn't crash with an exception but does loose input on the two properties that don't use `domvm.watch` because of the counter-intuitive action of updating the views inline.

https://jsfiddle.net/LawrenceDol/yjyhm9se/

In this case it happens because the built-in "change function" is invoked before the value is actually updated internally because one of the purposes of the change function is to override, even suppress the change under some conditions. So during view rendering, the property value is refetched before it's been updated. 

Note the console output of:

````
17:34:49.049 Property: new value 2 new value 2a _display:104:13
17:34:49.050 Property: new value 2 undefined _display:104:13
17:34:49.051 Property Value: new value 2 _display:112:13
17:34:49.051 Property: new value 3 undefined _display:104:13
17:34:49.051 Property Value: new value 3 _display:112:13
17:34:49.053 Property Value: new value 2a _display:112:13
````

Where the property starts to change, is accessed for read, and then the change completes. The access for read is due to the `redraw`.

If there is some reason why redraw cannot always coalesce within the same event, then there should be a separate function that never executes in line, such as `modelUpdated` or `update`, similar to what all GUI toolkits offer. Ideally, such a function should only set a flag that a redraw is required, and that flag would be checked (if this is possible) at the end of every event handled by the application. It would be less desirable to simply queue a new event (though that would be better than nothing), since that, in turn, will result in possible event queuing race conditions.

This is not intended to describe how the end-result is achieved, but rather, the semantics of that end-result. It is possible that this might be, of necessity, an application-level construction, though that would be unfortunate. Such a feature would mitigate or eliminate #57.

PS: Since `update` is already used, perhaps `remodel`.

**Comment by leeoniya** [comment]
All redraw calls are already coalesced by rAF (unless you disable this), which makes the most general sense to me since you could do async things within a single event callback and there is no good way to determine when everything is in a state that is ready/settled for redraw. I could possibly add promise handling here but it may complicate things significantly for vtree sync and impose fragility, etc.

Let's distill what you'd like to get done. Correct me if I'm wrong, as I'm only inferring off your own implementation of `prop` and description.

You want a `change` middleware function for `prop` that can either mutate the change or prevent the change completely (maybe by returning same value)...thus also preventing redraw triggering. The primary use of this is validation or auto-correct/auto-formatting.

What your fiddle does for f1/f2 is strange.

```js
f2 : prop("initial f2",vm.safeRedraw),
f3 : prop("initial f3",vm.unsafeRedraw),
```

And your prop impl then fires these redraws as if they were change-handling functions, passing into them both old and new values:

```js
if(chgfnc) { 
	var tmpval=chgfnc(newval,curval);
	if(tmpval!==undefined) { newval=tmpval; }
}
curval=newval; 
```

I addition, it fires the redraw before the value of the prop is actually changed. None of this makes sense to me.

Is my middleware-for-validation/prevent-redraw assumption correct? If so, then we can work forwards from that.

**Comment by leeoniya** [comment]
if the prop middleware callback is what you're looking for, i can add it as a third arg to `w.prop` [1]

[1] https://github.com/leeoniya/domvm/blob/1.x-dev/src/watch.js#L103

**Comment by lawrence-dol** [comment]
> if the prop middleware callback is what you're looking for, i can add it as a third arg to w.prop

If that seems a useful enhancement in general, then that would make sense; I have found it immensely useful. But in general, there are numerous variations on a prop get/set so you should not feel compelled to try to be all that you can be on this.

My custom property actually does more than just this; I cut it down for the fiddle. It also can optional store and retrieve values from local storage for persistence and supports direct encoding to JSON for simple values. The whole thing is:

````
function prop(curval,chgcbk,prpnam) {
    if(prpnam) {
        var stgval=localStorage.getItem(prpnam);
        if(stgval!==undefined) { curval=stgval; }                                                   // value in storage overrides initial value
        }

    function getset(setval,skpcbk) {
        if(setval!==undefined && setval!==curval) {
            if(chgcbk && !skpcbk) {
                var ovrval=chgcbk(setval,curval);
                if(ovrval!==undefined) { setval=ovrval; }                                           // override value with callback response
                }
            if(prpnam) { localStorage.setItem(prpnam,setval); }
            curval=setval;
            }
        return curval;
        };

    getset.toJSON = function() {
        return curval;
        };

    if(chgcbk && curval!=null) { setTimeout(function() { chgcbk(curval,null); },0); }               // schedule initial "change" for next event loop
    return getset;
    }
````

**Comment by lawrence-dol** [comment]
> ... The primary use of this is validation or auto-correct/auto-formatting.
> 
> What your fiddle does for f2/f3 is strange. You pass the redraw funcs as the chgfnc:
> ...
> And your prop impl then fires these redraws as if they were change-handling functions, passing into them both old and new values:
> ...
> [In] addition, it fires the redraw before the value of the prop is actually changed. None of this makes sense to me.

It makes perfect sense if the change function does not alter or veto the pending change *and* the expectation that "redraw" is only triggering a redraw not doing one inline. In this specific context the change function is simply being used to (I thought) trigger redraw.

> Is my middleware-for-validation/prevent-redraw assumption correct? If so, then we can work forwards from that.

Not entirely; the design of the function is highly generic. 

My primary point in all of this is the argument is that redrawing inline is never useful for the app (not speaking to the lib internals), and often counter intuitive. While the only tool the app has *right now* is to call `redraw`, it should be the normal case to only *flag* redraw since all you really want to do is tell the lib that the model has changed and the library needs to redraw at the next paint cycle.

My solution to this is simple in application land, but my experience is that almost every vDOM lib gets this wrong certainly, Mithril does (and Leo went through four broken implementations related to this problem); what apps *really* want is something like this (the name, remodel, is experimental):

````
dovvm.view.extend(function(vm) {
    vm.remodel=(function() {
        let pnd=false;
        return function() {
            if(pnd) { return; }
            pnd=true;
            setTimeout(function() { pnd=false; vm.redraw(); },0);
        }
    }());
}
````

This queues a repaint anytime the property is changed, but only one no matter how many redraws are done on the same view-model. This is what I use as my change function.

**Comment by leeoniya** [comment]
in either case, `var ovrval=chgcbk(setval,curval);` where `chgcbk` is `redraw` makes no sense. you could simply pass the `vm` into your prop and invoke redraw if/after the prop has changed/persisted and can be re-queried from this getter with the updated value.

invoking redraw before you settle the value for re-querying (presumably by render/template) and expecting that redraw() will be queued to execute at some point in the future is completely unintuitive, surprising and fragile. redraws are already coalesced by rAF, so invoking it 1000x within the same frame will only fire it once. u simply cannot complain that things are not being coalesced after explicitly disabling it via `useRaf: false`: https://jsfiddle.net/oe4o3p8e/

what you're doing by using `setTimeout` is a hack (you could also use `u.tick`) because all it does is delay redraw by 4ms, which happens to be enough time for the prop to settle. BUT if it is not enough time, like async ops, or slow i/o, then it will again re-render the old value.

> If that seems a useful enhancement in general, then that would make sense;

I've considered adding this before, so it makes sense to me.

**Comment by lawrence-dol** [comment]
> you could simply pass the vm into your prop and invoke redraw if/after the prop has changed/persisted and can be re-queried from this getter with the updated value.

That would be true, *if* the `prop` function was aware of DOMVM (or previously Mithril); it's not.

> invoking redraw before you settle the value for re-querying (presumably by render/template) and expecting that redraw() will be queued to execute at some point in the future is completely unintuitive, surprising and fragile

Here I think your expectations collide with mine, given my prior GUI experience with event queues (using and providing) and how they *must* operate to give the guarantees they do, and their correlation to the JavaScript event queue (which is so ingrained it will and can never change; hence entirely segregated web-workers instead of parallel multithreading; which is a **good*** thing).

There is nothing at all fragile, unintuitive or surprising about signalling the paint system that a change has occurred and having a guarantee that nothing further will happen until after the current event completes. It's a guarantee that sane GUI programming is built upon, and every attempt to get away from it has ended in a disaster of race conditions and threading issues. EVERY SINGLE GUI toolkit operates on an event queue for exactly this reason. Even Java's AWT was retroactively refitted in this way after a slurry of ongoing deadlock conditions from it's original locking multithreaded design.

> what you're doing by using setTimeout is a hack (you could also use u.tick) because all it does is delay redraw by 4ms, which happens to be enough time for the prop to settle. BUT if it is not enough time, like async ops, or slow i/o, then it will again re-render the old value.

No, it's not. Because the timeout must enqueue and event to invoke it's handler, regardless of the timeout specified. It may not happen for a few milliseconds longer, but it must happen on another event. So the effect is to guarantee that the action happen in a future event, which in turn guarantees that this event runs to completion first so the property altering code is guaranteed to complete before the redraw can happen. There's no question of there being enough time. 

Coalescing like this is absolutely mandatory in any complex system. You simply can't keep tabs on everything to do it any other way. The only thing you need to reason about is "a redraw will happen in the most timely fashion possible after this even completes". The multiple event handlers may trigger redraw on the same vm for different reasons. Some may even run and *not* trigger redraw because there was no need (a generic key handler that actions only some keys) -- this is something the Mithril got badly wrong and it resulted in a ton of extra work where it was trivial to cause key lag while typing (I still have the fiddle, I think, if you are interested).

**Comment by lawrence-dol** [comment]
> u simply cannot complain that things are not being coalesced after explicitly disabling it via useRaf: false

I agree; that's not what I am disputing, though I didn't get what `useRaf` meant at first and had only used it at some point because you said to try it. My point is already made in the previous post.

This does highlight a lessor bug, though. If the default and proper operation of redraw is to use RAF, then it should not be disabled by `domvm.config({});` Instead, any unspecified properties should be defaulted into the config. This point could be debated, but I would argue it's far less surprising that turning off things you didn't know about at time of writing (or, more importantly, that were added later).

**Comment by lawrence-dol** [comment]
PS: I am expressing an opinion here, albeit one strongly held and based on long experience. I am perfectly happy with my work-around, that DOMVM's good design allows to be seamless. I have no entitlement expectations of it being implemented, one way or the other, though of course I hope you'll take the time to consider and understand the problem space as I've explained it.

However, I feel that others will have the same issues and many may not even realize it. I feel it's significant that I've never had cause to do it any other way.

**Comment by leeoniya** [comment]
Let's consider the the coalescing point addressed.

> There is nothing at all fragile, unintuitive or surprising about signalling the paint system that a change has occurred and having a guarantee that nothing further will happen until after the current event completes.

Can you explain how this can be guaranteed without global blocking or a framework that has its hands in your model's semantics? Why does redrawing/queueing till the "next frame" guarantee that all our model changes have settled? How do we know when to "flush" the transaction of all queued redraws?

You're essentially saying there is a reliable way to infer when all model changes are settled following some `vm.queueRedraw()`.

```js
vm.queueRedraw();
// something asynchronous
// some fast model change
// some blocking model change
```

Can you show me an example of a js framework or just a fiddle that allows you to bring your own models and will properly redraw the above code where queueRedraw is delayed until the next frame and "something asynchronous" takes 40ms and "some blocking model change" takes 100ms?

**Comment by lawrence-dol** [comment]
> Why does redrawing/queueing till the "next frame" guarantee that all our model changes have settled?

It doesn't, and it shouldn't with respect to **all** model changes. The key word is "settled" being applied to the entire model, which you wrongly inferring from my code which relies only on the current property change being "settled" in your parlance.

My function, tentatively named `remodel` (mostly because `update` and `redraw` are already used) simply signals the system that a particular view needs updating because a model on which it depends has been changed. But does so in a way that guarantees no action to that effect will take place on this event (and especially not inline; anything less that that would actually be fine). This is, of course, a distraction from the overall point.

In any GUI eventing system, doing things to the view inline is an inherently fragile thing. Because now suddenly, things change underneath you and following the function invocation trail in all circumstances can be hell, or even impossible. Queuing signals that cause asynchronous actions, like redraw, that re-root the call stack at the event invocation become absolutely necessary in any system that is more than trivially complex.

Queuing the redraw simply guarantees that eventually and in a timely fashion your view will certainly be updated to match the model. It may be updated between now and then for other unrelated reasons. That doesn't matter because the model is always in a renderable state even when indeterminate things like network actions are pending (which is why we do things like show throbbers). 

What matters is that the view doesn't get changed prematurely **in the middle** of executing your current event handler; **that** is what causes surprising edge-cases. 

The other thing that matters is having good intuitive control over **whether** the redraw is done so that events that don't change the model don't cause an unnecessary redraw (which is why Mithril's redraw on every event unless suppressed by using `redrawStrategy` fails).

If you are interested, this issue, though from a different angle was discussed in Mithril, where the point was also missed and the redraw-suppression hack survived. The whole thread is of interest, but it gets specific at:

https://github.com/lhorie/mithril.js/issues/378#issuecomment-66503658

It all boils down to the fact that no one piece of code in any system can say "redraw is not needed", but any piece of code can reliably say "redraw is needed". However, there's a vast difference between "redraw is needed" and "reconstruct the view right now".

> Can you show me an example of a js framework or just a fiddle that allows you to bring your own models and will properly redraw the above code where queueRedraw is delayed until the next frame and "something asynchronous" takes 40ms and "some blocking model change" takes 100ms?

Yes. DOMVM is the framework. And queued redraws will achieve the desired effect.

````
vm.queueRedraw();
// something asynchronous starts
// some fast model change (queue request is noop because already queued)
// some blocking model change (model will show throbber until complete)
redraw (from first queued request)
// blocking change completes and queues redraw
redraw (from second queued request)
````

Redraw has just been done, separately and exactly and only as many times as needed. And it's trivially easy to reason about.

**Comment by lawrence-dol** [comment]
Clarification on my earlier comment of:

> There is nothing at all fragile, unintuitive or surprising about signalling the paint system that a change has occurred and having a guarantee that nothing further will happen until after the current event completes.

It should read: There is nothing at all fragile, unintuitive or surprising about signalling the paint system that a change has occurred and having a guarantee that nothing further with respect to that signal will happen until after the current event completes. IOW it is a pure signal.

**Comment by leeoniya** [comment]
can you clarify "current event" and "completed". neither of these are exact definitions that map to obvious code.

by current event completed do you mean function return?

if your queueRedraw call preceeds some model change in the same function, there is no way to determine if/when any post-enqueing operations have "completed". the next frame may perhaps guarantee that any synchronous ops have completed but that is not sufficient to automatically default any redraws to the *following* frame.

**Comment by leeoniya** [comment]
> What matters is that the view doesn't get changed prematurely in the middle of executing your current event handler; that is what causes surprising edge-cases.

Can you show me when this actually occurs (without disabling rAF)?

**Comment by lawrence-dol** [comment]
> can you clarify "current event" and "completed". neither of these are exact definitions that map to obvious code.

I should be more exact. I mean the execution of the current event handler callback, irrespective of whether there are other event handlers attached to the event, whether at the current or some ancestor node.

> Can you show me when this actually occurs (without disabling rAF)?

No. But the very fact that `redraw` can be altered by config (even if it's done without realization of the ramifications by a newbie such as happened with me) means that code cannot rely on its behavior.

I code to the documented specification, not the coded behavior, unless it's very clear from the context that the behavior is reliable and there's no documentation to the contrary; IOW as long as there is no reasonable alternate implementation of the documented or inferred API contract. So as long as it's legitimate to change `redraw` behavior I can't rely on RAF being used.

Absent that guarantee, I am <strike>asking for</strike>, no, suggesting that such a guarantee is going to be needed by most or all apps and suggesting that either `redraw` provides it (by internally creating `draw` that doesn't) or some new function, which I have tentatively called `remodel` for lack of a better idea.

Again, I personally am happy with extending DOMVM to provide that guarantee; but I want DOMVM to be the best in class... so I make my suggestions and provide the justification for you to weigh.

**Comment by leeoniya** [comment]
useRaf/false is a debugging tool and is undocumented. its use does exist in some perf/bench demos because leaving it enabled has ramifications for accurate timing feedback. it is not something that you should expect to be used in normal production code.

if you need a way to `Object.freeze` the config, then this is something to consider adding.

**Comment by lawrence-dol** [comment]
> useRaf/false is a debugging tool and is undocumented.

Fair enough.

Then `config({})` should not cause RAF to be **not** used. Therefore config values should be explicitly defaulted if not specified.

Also, arguably, non of the demos should use it without a clarifying comment that it for the purposes of accurate timing only. Currently, calendar, threadit, 2500-words, dbmonster, patch and speedtest do.

And a note in #36 Footguns for this specifically and for config in general (because undocumented or not, people are going to find it). :-)

**Comment by lawrence-dol** [comment]
By the way, if you'd like to see the result with Mithril spamming redraws, someone in the thread had forked my fiddle, so I was able to easily restore it:

http://jsfiddle.net/LawrenceDol/e65j8ept/

**Comment by leeoniya** [comment]
at least in windows, the default repeat rate is 30/s [1], so i think domvm would behave similarly even with rAF coalescing. it's when you start doing sub-16ms redraw calls that the grouping has any effect.

[1] https://technet.microsoft.com/en-us/library/cc978659.aspx

**Comment by lawrence-dol** [comment]
DOMVM does not behave like Mithril in this case; because DOMVM does not assume that every event changes a model and therefore that every event needs to cause a redraw. This is a markedly better decision, IMO. And, in fact, input events do not need to redraw since by definition, the view is already updated before the event is even triggered.

**Comment by leeoniya** [comment]
@lawrence-dol 

i've opened #63 to address the useRaf/config guards and docs.

 can we now consider *this* issue resolved?

**Comment by lawrence-dol** [comment]
> can we now consider this issue resolved?

I think so, though I will continue to use my deferred redraw mechanism, I think, since it allows for (IMO) a better balance of coalescing and has the ability to throttle redraws to a higher number that's fast enough for the user but could avoid lots of overhead on the system. 

In the end theoretical frame-rate is irrelevant after it exceeds the user's perception, but right now, if every key stroke causes a change (which I have in practice since I am logging all keys to a status line while developing), it pegs my CPU at 33% of an AMD Phenom II quad-core at 3.4 GHz for no visible change holding down a key when a field is full, because the status is being blanked and then reset in the same physical event. While this is an artificial situation (for debugging) it's not hard to imagine a real app that has this result. And my solution doesn't impede separate concerns for animations or other things that need a higher frame rate because it's orthogonal to any other redrawing.

Thanks for considering this.

**Comment by leeoniya** [comment]
right, you can make your own throttler/debouncer that wraps your calls to `vm.redraw()` and use it globally or selectively in places where it makes sense to drop the fps.

**Comment by lawrence-dol** [comment]
> you can make your own throttler/debouncer that wraps your calls to vm.redraw() and use it

Exactly. One reason I prefer the explicitness of DOMVM and a good example of why it seems to have struck a much better balance. You'll noticed that I've brought thinking habits from Mithril and sometimes forget that such things are totally within my control.

**Comment by leeoniya** [comment]
@lawrence-dol w.prop middleware arg has been added and can be used to inject a validation or transformer func.
