### ISSUE TITLE
View-Model extension conflict check?

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#61]
The `vm` extension idea is excellent and can mitigate a lot of "the library should have this and that" issues of contention.

But, could the DOMVM vm please provide the following function for extending so that conflicts do not silently cause strange effects, perhaps as an argument to the extension function itself?

```
function extend(nam,val) {
    if(this[nam]!=undefined) { throw "Conflict: Cannot extend view-model with `"+nam+"` - already defined"; }
    this[nam]=val;
    };
```

Used like this:

```
domvm.view.extend(function(vm) {
    vm.extend("state",{});

    // Used directly as a property mutation preprocessor; must have no args and return undefined
    var remodel=function() {
        if(!vm.state.redrawPending) {
            vm.state.redrawPending=true;
            setTimeout(function() {
                vm.state.redrawPending=false;
                vm.redraw();
                },0);
            }
        };
    vm.extend("remodel",remodel);
    });
```

or if an argument: 

```
domvm.view.extend(function(vm,extend) {
    extend("state",{});
    ...
```

**Comment by leeoniya** [comment]
i'd prefer to discourage the use of non-namespaced `extend` in general. the main reason is that internal changes between 1.x versions may still cause non-silent breakage, where there should be no breakage, period.

if you instead use eg `vm.z.*` for extending, then there are no surprises and a much lower chance that 1.x changes will clobber your [hopefully unique] namespace.

**Comment by lawrence-dol** [comment]
The problem with namespaced extensions is that to make them collision proof with respect to arbitrary 3rd party code is to make them cumbersome to use. In the face of a large pool of ready-to-use components, global extensions become impossible to manage or unwieldy in invocation unless the "component" can choose a default namespace. For example, who wants to call `vm.extension.com.mycompany.remodel()`?

**Comment by leeoniya** [comment]
didnt think you'd take my simple, not-that-gnarly proposal and go full-java on it, lol.

**Comment by lawrence-dol** [comment]
If only protecting against collision with DOMVM either my check or `vm.x.abc()` would work OK. But I dream of a future with ready-made DOMVM components that are plug-n-play, because DOMVM has the infrastructure and design the make that feasible. :-D

**Comment by leeoniya** [comment]
> But I dream of a future with ready-made DOMVM components that are plug-n-play

You mean some future where domvm has > 5 users? D:
