### ISSUE TITLE
Event handlers get the wrong VM

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#62]
This is strange. The vm passed to event handlers appears to be incorrect. I was expecting to always get the vm containing the node on which the event was fired.

See fiddle: https://jsfiddle.net/LawrenceDol/z3dzhgc2/

Note that regardless of which input box you type into it shows the render function for SubView2. When typing into the first, it should have the vm for SubView1.

Checked on Firefox and Chrome.

**Comment by leeoniya** [comment]
confirmed, this is a regression in 1.1.0. working on a fix.

**Comment by leeoniya** [comment]
btw, i think `cdn.rawgit` is doing some caching of old ver. see: https://jsfiddle.net/z3dzhgc2/6/

**Comment by lawrence-dol** [comment]
Confirmed fixed on 1.x-dev.
