### ISSUE TITLE
 `config({})` should not cause useRaf: false

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#63]
@lawrence-dol

> Then `config({})` should not cause RAF to **not** be used. Therefore config values should be explicitly defaulted if not specified.

> Also, arguably, none of the demos should use it without a clarifying comment that it for the purposes of accurate timing only. Currently, calendar, threadit, 2500-words, dbmonster, patch and speedtest do.

> And a note in #36 Footguns for this specifically and for config in general (because undocumented or not, people are going to find it). :-)

**Comment by leeoniya** [comment]
@lawrence-dol

there's now a loop that pulls options in [1], so this issue should be resolved. also, `useRaf` is gone.

can you confirm/close this?

[1] https://github.com/leeoniya/domvm/blob/1.x-dev/src/view.js#L39-L42

**Comment by lawrence-dol** [comment]
Without monkeying with the source, I can't see anyway to verify that the config is surviving, but the code certainly looks correct. Also, I can't close this issue, presumably because I am not the owner. But from my point of view, this can be closed.
