### ISSUE TITLE
Update dbmonster FPS counter

### ISSUE THREAD

**Issue by trueadm** [leeoniya/domvm#64]
The one in circulation is currently broken. Please update it to use the latest one from localvoid:

https://github.com/localvoid/perf-monitor

**Comment by leeoniya** [comment]
@trueadm thanks!

honest question, though. how much sense does it make to replace it for us when basically all impls [1] will use the broken one? changing the env for a prescribed bench especially such a core component cant be beneficial.

how inaccurate is the current one? does it lie significantly more for some impls than for others. while i do want accuracy in the absolute, the relative accuracy for benches is more important, no?

[1] https://github.com/mathieuancelin/js-repaint-perfs

**Comment by trueadm** [comment]
It's nothing to do with the ENV, it's to do with the tool that gives you the repaint stats at the bottom right of the screen. :)

**Comment by leeoniya** [comment]
i know, i didn't mean ENV.js, i meant "env" as in the environment in general, including the monitor.

**Comment by leeoniya** [comment]
i will also note that the precompiled perf monitor [1] uses many ES6 features which makes it unusable in anything but evergreen browsers :/

[1] https://github.com/localvoid/perf-monitor/blob/master/public/0.1/perf-monitor.js

**Comment by leeoniya** [comment]
@trueadm

I have a local impl done.

Another thing i noticed is that it FPS is capped at 60 presumably due to internal rAF use. While this makes sense with respect to FPS, it also prevents easily asserting the framework's overhead at 0% mutations and since many libs can get well above 60 "fps" in such cases, the differences there are very significant but become masked.

**Comment by trueadm** [comment]
@leeoniya The problem is, the previous tool wasn't giving accurate values for that. You were seeing total rubbish values that actually had no real relation to how fast the implementation was. If you want to see the overhead, you can easily use the profiles – like Inferno's has done. That way you can see in `ms` what each render is really taking.

**Comment by leeoniya** [comment]
> If you want to see the overhead, you can easily use the profiles – like Inferno's has done

Can you clarify? I don't see any visualization of overhead at 1% in http://infernojs.org/benchmarks/dbmonster/

In the previous perf monitor, if I adjust the mutations to 1%, the fps counter goes to ~200fps for inferno vs ~100fps for domvm. It's easy to say, there's approx a 2x difference in framework overhead. And it's easy to use this method to check for regressions or improvement.

`ms` trends are difficult to assert in % when you're only going between tiny sub-ms increments per cycle.

**Comment by trueadm** [comment]
@leeoniya That number you saw was not FPS, that's the problem. The DOM is capped at 60 FPS, the number is fabricated by the fact we're using `setTimeout(0)`. If you move the mutations to 1% you can see the mean `ms` of Inferno is at 0.1ms opposed to 2.5ms for 50%. This is important as this is the time taken for the actual render to happen irrespective of the DOM reflow.

**Comment by leeoniya** [comment]
So it looks like the `view update` / `mean` is the metric to watch for "overhead", fine. Unfortunately, until there's an IE9+ `perf-monitor` that i can simply drop in, I cannot replace the current one. If you have all the tooling set up for an IE9+ build and want to push it somewhere, i will use it.

**Comment by trueadm** [comment]
It works on IE9 now. Boris updated it.

**Comment by leeoniya** [comment]
cool.

**Comment by leeoniya** [comment]
done [1].

also switched to using a new node-level `_diff` feature which is a bit slower than splitting off sub-views (since json-ml allocation is not avoided), but the implementation is much tighter and more readable [2].

[1] http://leeoniya.github.io/domvm/test/bench/dbmonster/
[2] https://github.com/leeoniya/domvm/blob/1.x-dev/test/bench/dbmonster/app.js
