### ISSUE TITLE
Decoupled model and view where model has properties which trigger redraws on the view

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#68]
I've been dancing around this issue since #60, but it's getting progressively more difficult. How would you recommend that a decoupled data-model which needs to trigger redraws on the `vm` that uses it be constructed?

The essential problem being that the properties of the model can't be created until the `vm` reference is available, but the model wants to be created before the view and injected into it.

````
var model=new DataModel();
var view =domvm.view(new DataView(model)); // or (new DataView(),model)
````

But DataModel needs the DataView view-model to do the moral equivalent of:

````
var w=domvm.watch(function() { vm.redraw(); });
...
exported.someProp=w.prop("default");
````

So the model can't be injected into the view, and the view can't be injected into the model. I can't see a clean way to do this.

**Comment by leeoniya** [comment]
So the problem is creating a circular reference with both the model and view needing each other during their both inits?

You may have to loosen the init requirements for one of them. Probably for the view. You can always inject the model into the view after the fact, as long as it's available before `render()` is called. It currently doesnt seem to work, but something like this?:

https://jsfiddle.net/dk5j1qdm/

**Comment by leeoniya** [comment]
it works here if you do mount => update: https://jsfiddle.net/dk5j1qdm/1/

i can look into getting it working in for the update => mount case.

**Comment by lawrence-dol** [comment]
That's the essential problem. Doesn't doing mount first mean that you have one view render with a null model? Probably works because it's been deferred to the next animation frame.

It's the hard dependency on the view for redrawing that closes the circle. It's normal for view to be dependent on a model, but it seems odd that the model is tightly coupled to a view. My instinct is to create a break the dependency of the model on the view... just not seeing a clean way to do it.

**Comment by leeoniya** [comment]
I guess i'm not understanding the problem then. The model does not have any dependency on the view, unless you plan for the model to be able to refresh the view by itself, then of course it needs some knowledge of the view it will be refreshing, either by some proxy `w.prop` observer or directly to the `vm`. Could you flesh out the exact situation and specifically what you'd like to achieve?

**Comment by leeoniya** [comment]
> That's the essential problem. Doesn't doing mount first mean that you have one view render with a null model? Probably works because it's been deferred to the next animation frame.

Yes currently, but the initial `render()` call may be able to be deferred. Your render just needs to handle a null model as the example does, and simply return some minimal template, `["div"]` works.

**Comment by lawrence-dol** [comment]
> unless you plan for the model to be able to refresh the view by itself

Yes. If a part of the model is changed, the affected view(s) which depend on it should be redrawn.

That sounds like it needs to be a named registry in each model, such that view can add themselves to models to be refreshed, though the model level may be too coarse.

E.g:


    function View(vm,mdl) {
        mdl.register("path/to/my/view/XyzView",vm);
        return function() {
            ...
        }
    }

The name being used to replace the view registration when it is recreated.

But that sounds like a memory leak waiting to happen.

**Comment by lawrence-dol** [comment]
Currently I have two sub views:

    function AppView(vm) {
        var sub1=new BodyView(new BodyModel(vm));
        var sub2=new StatusView(new StatusModel(vm));
        return function() {
            ["div",[
                sub1,
                sub2,
            ]]
        }
    }

Whenever the status model is change, it need only update the StatusView, but it's currently updating the AppView because there's no other reference to a vm available.

**Comment by leeoniya** [comment]
This problem is pretty fundamental and not domvm-specific, no? If your view can poke the model and model can poke the view, you always have to make this chicken-egg choice work by providing one to the other after its init. Either your model has a registry or your view does.

**Comment by leeoniya** [comment]
> Currently I have two sub views:

one sec, lemme see...

**Comment by lawrence-dol** [comment]
> This problem is pretty fundamental and not domvm-specific, no?

Well, yes and no. It seems like the kind of thing that will come up in every app if the view is truly model-driven, therefore completely slave to the model. I guess the argument could be made that there are other ways of architecting the app, but I thought model-driven was pretty fundamental to DOMVM (as it is to Mithril).

**Comment by leeoniya** [comment]
yeah, you need to inform the models about the views in which they happen to participate. there's no way to do this otherwise in a decoupled architecture (domvm or otherwise). a model having a view registry sounds fine.

If the vms happen to be removed, as an effect of the model being removed from some larger template, yes you'll have to manage the memory leaks there and maybe use `unmount` hooks to do the cleanup.

Can you show me a decoupled framework where this is not the case [or how you expect it to work]? Of course if you opt for a coupled and stricter convention, you can make this automatically handled for you. Like unified model+view, but then you give up flexibility of multiple views of one model, etc.

**Comment by lawrence-dol** [comment]
> Of course if you opt for a coupled and stricter convention, you can make this automatically handled for you

That was my first choice and by far my preference for this app. I'll work more toward this direction for now, but I wanted to know what my options were and if I was missing something.

**Comment by leeoniya** [comment]
it sounds like you might be better off with some variant of *Pattern C*, where the views are initialized within the models and just exposed for external composition.

**Comment by lawrence-dol** [comment]
> you might be better off with some variant of Pattern C

You could be right. I'll continue to ponder it. Otherwise, a central event bus looks like the only way to decouple them if I end up needing that.

**Comment by lawrence-dol** [comment]
Does a given vm have access to all the vm's of it's children in an efficient manner? Would it be possible to initiate a top-down walk of the vms and redraw any affected by querying each one and asking it if value "Xyz" means it should redraw?

**Comment by leeoniya** [comment]
you could manually walk the tree, sure. you can also use exposed refs `_ref: "^deepVm1"` on each vm's root node that will populate `vm.refs` of all ancestor vms (up to you to avoid collisions). you can set whatever flags on the vm objects you want, much like `extend`.

**Comment by leeoniya** [comment]
you can also use exposed refs as the _ key during view init: `domvm.view(View, model, "^myVm")`. same thing applies to declarative views `[View, model, "^myVm"]`.

**Comment by lawrence-dol** [comment]
So, if I am understanding this right, `domvm.view(View, model, "^myVm")` will cause a ref in the parent vm named `"^myVm"` which will reference the vm of the just created view?

Given

````
function AppView(appVm) {
    var bdymdl=new BodyModel();
    var stsmdl=new StatusModel();
    return function() {
        ["div",[
            [BodyView,bdymdl,"^BodyVm"],
            [StatusView,stsmdl,"^StatusVm"],
        ]]
    }
}
````

I'll have `appVm.refs["^BodyVm"]` == vm of Body and likewise for the Status? (Or `appVm.refs.BodyVm`?)

**Comment by leeoniya** [comment]
right, the caret is stripped though, so it can be used without brackets: `appVm.refs.BodyVm`, and this will reference the root view vnode...so the vm will be `appVm.refs.BodyVm.vm`

**Comment by lawrence-dol** [comment]
I think that's exactly what I need. I have the final (rather complex) bits of the prototype to do over the next few days, but then I'll refactor on these lines and report back with what I do. 

I imagine there'll be a reusable little function/extension that will enable any vm to cascade a named "remodel" request down. But I am also musing on whether in this case each model shouldn't just be exposing it's own view. It's a tough call, because though eschewing MVC for self-contained components, I *do* like the models entirely separate from everything else.

**Comment by leeoniya** [comment]
> I think that's exactly what I need. I have the final (rather complex) bits of the prototype

At this point, I'm fairly certain that we have very different definitions of "prototype" D:

> I imagine there'll be a reusable little function/extension that will enable any vm to cascade a named "remodel" request down.

The idea is that you can implement disjoint sub-view communication by using a combo of exposed/bubbled refs, `vm.emit` and emit handlers in some common ancestor's closure. This includes redrawing sub-views or emiting "down" into them from above. The facilities are there, it's really up to you where you want to establish the conventions/coupling.

**Comment by leeoniya** [comment]
BTW, this was the central subject of https://github.com/leeoniya/domvm/issues/17 if you're looking for some nostalgia.

**Comment by lawrence-dol** [comment]
`vm.emit` bubbles up, right, as opposed to cascading down? Unfortunately, I am already using keys for their primary use, to determine when the view needs to be replaced.

So I think I need to add a cascade function that walks the `_node.el.childNodes` accessing the `_node.el.vm` for each one, recursively. (That does seem like a service DOMVM should provide, walking up or down the tree from a given node.

**Comment by leeoniya** [comment]
the tree is so easy to walk, i dont want to add extra api surface to domvm to save a 4-liner. emit goes up, which is cheap; cascading down is expensive, since you may need to visit possibly thousands of nodes in that branch.

you should be able to use both _ref and _key. you could set up the ref inside the view on the root node and still have the view key be normal (should work). if you want to specify what the internal _ref should be from above, you can pass it through to the view via the 4th `opts` arg.

**Comment by lawrence-dol** [comment]
> the tree is so easy to walk

I'm actually talking about the vm tree, not the generated node tree. Confer #72.

**Comment by lawrence-dol** [comment]
> the tree is so easy to walk

Also, if it is, it's far from obvious when working from the root vm object. Can you share what that four lines of code would be?

**Comment by leeoniya** [comment]
this is getting off-topic, please transfer comments (if needed) and discuss in #72.

**Comment by lawrence-dol** [comment]
Yes it is, though that issue was opened due to this. Now that I know about `body` I understand why you said it's simple and obvious to walk the node tree.

**Comment by lawrence-dol** [comment]
> At this point, I'm fairly certain that we have very different definitions of "prototype" D:

Well the app I'm replacing is well over 50 KLOC so the prototype needed to prove it can be done in JavaScript is pretty big. And I'm just doing the essentials of the UI. :-)

**Comment by leeoniya** [comment]
how's it stacking up so far?

**Comment by lawrence-dol** [comment]
So far it's working well; better than expected. Though I have my work cut out for me with many of the more advanced features, a hard end-of-year deadline and multiple other projects that need to be advanced at the same time. This is actually the Java applet for which I had to write a fully functional GUI toolkit on top of AWT canvas, because we had to target Java 1.1 which didn't have Swing and AWT components were heavyweight, awful at rendering and could not be styled at all.

**Comment by yosbelms** [comment]
Hey, @lawrence-dol you can find `up` and `down` utilities in https://github.com/leeoniya/domvm/pull/19/commits/7357f342221861f5902f3c771b89d7cf18385e28 , a rejected PR.

**Comment by leeoniya** [comment]
thanks @yosbelms :)

**Comment by lawrence-dol** [comment]
@yosbelms : They look useful; thanks. @leeoniya : Perhaps they belong in the widgets repo?

**Comment by leeoniya** [comment]
The widgets repo is meant for official UI widgets rather than low-level utils. The internal structure should be documented but is always subject to change, I want to retain this freedom for future optimization, etc.

Tree traversal should not be necessary to the majority. Even in your case, you can use bubbled refs [i really should settle on a permanent name for these] in combination with key-based subview invalidation: https://jsfiddle.net/3bvc7zyu/1/

```js
function ViewA() {
	return function() {
		return ["#a",
			[ViewB, {text: "abc"}, "ID234", {ref: "^b"}]
		];
	};
}

function ViewB(vm, model, key) {
	return function() {
		return ["#b", {_ref: vm.opts.ref}, "foo"];
	};
}

var vm = domvm.view(ViewA).mount(document.body);

console.log(vm.refs);
```
