### ISSUE TITLE
Play nice with 3rd party libs

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#7]
There are plans to add a couple features that would allow easy use of third-party libs.

Guarded nodes are nodes that are created and then protected from re-use by domvm, allowing you to use them as containers for other libs without worrying about them being mutated.

```js
["div", {_guard: true}, someContent]
```

A way to sync a DOM node back into domvm's vtree. Not sure if this can be offered at node-level or only vm-level, but the latter is probably most likely. This allows domvm-managed nodes to be modified but then have their css or other properties re-synced back into the vtree.

```js
vm.absorb();
```

~~For another issue, since some features cover multiple purposes: Lifecycle hooks either at node level and/or vm level, pub/sub event listerners/hooks.~~ Implemented.

**Comment by leeoniya** [comment]
this is now looking a lot better for node-level since `vm.patch` has been implemented

**Comment by lawrence-dol** [comment]
This is nice. I've integrated a third-party date picker with Mithril, and it was a little clumsy.

**Comment by leeoniya** [comment]
Many libs will create their own root elements, so `_guard` may be insufficient as it requires you to dump the contents into an extra container layer. Maybe this isn't a huge issue. But...

`[existingElem, {...}]` could be added as a node signature to both import existing raw elems and apply props and even content/children to them. There's some overlap here with the not-yet-documented `vm.mount(container, true)` which reuses the container rather than appending into it, which is also similar to the isomorphic `vm.attach(container)`.

may need to think about DRYing them out internally though slight nuances still apply for each.

**Comment by leeoniya** [comment]
this is available as raw element insertion into templates. no special things needed here.
