### ISSUE TITLE
Defer resolution of property getters in View?

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#71]
If I create an input, thus:

```js
    let inpfnc=function(evt,nod,vm) {
        fld.value(evt.target.value);
        };

    ...

    return [ "input.field", { value: fld.value, oninput: inpfnc }];
```

where fld.value is a property function, it doesn't matter whether I use `fld.value` or `fld.value()`. The net effect is that the current value is baked into the view.

However if it would retain the reference to the function and invoke it when building the DOM, it could pull the value live and the recreation of the entire view could be avoided if the only volatile bits are inputs. In other words, I could build my view structure in view-init instead of render and just return the view structure each render until the key changes. Currently the only thing stopping me is that the input fields all reset their contents on every redraw if I do that.

Thoughts? Is this possible? Desirable?

**Comment by leeoniya** [comment]
> I could build my view structure in view-init instead of render and just return the view structure each render until the key changes

You cannot. The JSONML structure you return from render gets mutated into a new vnode tree, so you must recreate it on each redraw.

> The net effect is that the current value is baked into the view.

No, but it could appear this way if you try to reuse the same jsonml template (or prop objects) between redraws.

`render()` should recreate the template in full. you can [should] reuse functions (getters, event handlers). but the structure must be recreated, including prop objects. it's possibly you could reuse deeper objects like `style`, but just remake them to be safe.

**Comment by lawrence-dol** [comment]
> You cannot. The JSONML structure you return from render gets mutated into a new vnode tree, so you must recreate it on each redraw.

Ohhhhhhh! That just clicked and now a bunch of things just became clear.
