### ISSUE TITLE
Clean up the DOMVM vm tree

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#72]
Is there a logical way to follow the vm and node hierarchies? 

I find the nomenclature used in the tree to be confusing. There are `node` objects which are DOMVM nodes, containing `el` objects which are DOM elements and have a circular reference to the node named `_node`. And references that crisscross all over the place. 

Would it be possible and sensible to have the vm tree as parallel to any associated vDOM and DOM tree such that each vm has both `parent` and `children` references to other vm's where any vm whose `parent` is `x` is also in the children array of `x`?

I'd like to see a `vm` structure, orthogonal to vDOM/DOM of:

````text
appVm
  _el   (=vm root DOM element)
  _node (=vm root vDOM node)
  api
  attach
  children
    [0] subVm1
        _el   (=vm root DOM element)
        _node (=vm root vDOM node)
        api
        attach
        ...
        parent (=appVm)
    [1] subVm2
        _el   (=vm root DOM element)
        _node (=vm root vDOM node)
        api
        attach
        children
          [0] subsubVM
              _el   (=vm root DOM element)
              _node (=vm root vDOM node)
              api
              attach
              ...
              parent (=subVm2)
        ...
        parent (=appVm)
  emit
  events
  ...
  parent (=null)
````

With each vDOM node corresponding to a vm root having a `_vm` ref and each DOM element corresponding to a vm root having a `_node` and `_vm` ref.

For me, the primary tree is the DOMVM vm tree. The rest is all ancillary, but necessary.

**Comment by lawrence-dol** [comment]
(I think all that's missing is the vm's have children arrays.)

**Comment by leeoniya** [comment]
the primary tree is not the `vm` tree (there isn't one), it's the vnode tree. if the vnode is a root view node, then it has a non-null `vm` attached to it. if `body` is an array, then those are child vnodes, else it's textContent of a leaf node.

the vnode tree exactly mimics the DOM.

**Comment by lawrence-dol** [comment]
> the primary tree is not the vm tree (there isn't one), it's the vnode tree.

But, I would argue, it should be. It seems like that if every vm can have a reference to it's parent, then every vm can be populated with a reference to it's children. The primary thing, as developers we reason about is the hierarchy of components (vms); the rest is clutter (though necessary clutter).

Maybe just think about whether a children array could be populated as the parent nodes are being assigned. Please?

**Comment by leeoniya** [comment]
You're basically asking if it's possible for the vm's to additionally have a `body` [of child vms] like vnodes. vms already have a vm `parent` (which emit uses to bubble).

domvm is a half vdom-lib have viewstate. what is primary depends on who you ask and really makes no difference since the trees are parallel. the vnode tree is primary because in the end every vnode has an atomic DOM representation. the vms which are just "state" attachments to the dom tree are ancillary and just hang off the root vnodes.

you can currently walk the vms upwards via `vm.parent`. i can add `vm.children` (or `vm.body` to be uniform with the vnode tree).

**Comment by leeoniya** [comment]
this is the tree structure:

```
el			vnode			vm
	el			vnode
	el			vnode
	el			vnode			vm
		el			vnode
		el			vnode
	el			vnode			vm
```

there are some circular references so you can jump in/out. vms have a `.parent` (vm), vnodes have a `.parent` (vnode), vnodes also have a `body` (children or textContent). vms lack a children/body.

if you want to traverse down to deeper vms, just walk the vnode tree looking for any vnodes with a non-null `.vm`. it's not difficult.

**Comment by lawrence-dol** [comment]
> You're basically asking if it's possible for the vm's to additionally have a body [of child vms] like vnodes.

Yes please, though I missed the `body` property in the tangle of names expecting to see `children` (I told you the structure is not clear from the outside coming in).

> domvm is half vdom-lib, half viewstate. what is primary depends on who you ask

Granted; from DOMVM it's the vDOM nodes; from the developer I'd argue it's the vm tree.

> you can currently walk the vms upwards via vm.parent. i can add vm.children (or vm.body to be uniform with the vnode tree).

Again, yes, please. Personally, I'd use `children` for both to be uniform with the DOM tree. If the vDOM tree is dictated externally or there is other precedent then, yes, use `body` since from the developer perspective it's vm => vnode => dom, in decreasing level of interest.

> just walk the vnode tree looking for any vnodes with a non-null .vm. it's not difficult.

Right. But it could be a lot easier if the price is small.

**Comment by leeoniya** [comment]
added `vm.body` in 1.x-dev: https://github.com/leeoniya/domvm/commit/175a6715cd38568767ee44bc9d491a75553e7dca

**Comment by lawrence-dol** [comment]
Now that my understanding of the trees is improved, the only thing I want is the vm `body` array. `vm.node.el` is fine.

**Comment by lawrence-dol** [comment]
That was fast; thanks!

**Comment by lawrence-dol** [comment]
Add something to #36 about describing the tree structures and relationships? Boy, we are going to have some documenting to do.

**Comment by leeoniya** [comment]
Q: How do you eat an elephant?
A: One bite at a time.

**Comment by lawrence-dol** [comment]
Hmmm. Root body array is zero length. Will dig further shortly.

**Comment by lawrence-dol** [comment]
But not in a simple fiddle. Time to figure out where my app is going wrong.

**Comment by lawrence-dol** [comment]
The following fiddle always has the body array as zero length:

https://jsfiddle.net/LawrenceDol/d72nc3h7/

Code is:

````
<script src="https://cdn.rawgit.com/leeoniya/domvm/1.x-dev/dist/domvm.min.js"></script>

-----

var appVm;

appVm=domvm.view(RootView).mount(document.body,true);
appVm.redraw();

function RootView(vm) {
    return function() {
  	  	console.log("appVm:",appVm);
        return [ "#temjs", [
            [DummyView,"View1"],
            [DummyView,"View2"],
            ]];
        };
    }

function DummyView(vm,txt) {
    return function() { return ["div",txt]; }
    }
````

**Comment by leeoniya** [comment]
this is by design and is another chicken/egg problem.

the body and refs are cleared before render is called because you're about to re-built them from the template you're returning. this regenerated template may result in removed nodes or unmounted vms. offering you the stale body and refs is not an option and will lead to pain and suffering.

you cannot use refs or body from inside render(), only from handlers or functions within the view closure, but not mid-redraw.

**Comment by lawrence-dol** [comment]
Duh! I feel stupid. Though I have another fiddle that seems identical but dies have the body elements.
