### ISSUE TITLE
router.goto doesnt change location.href

### ISSUE THREAD

**Issue by iamjohnlong** [leeoniya/domvm#73]
calling 
```js 
router.goto("about", {}, {foo:'baz'})
```
doesn't change the location in the URL. Is this by design?

**Comment by leeoniya** [comment]
heyhey!

nope, probably an oversight. will look into it soon.

**Comment by leeoniya** [comment]
wasnt really an oversight (the code was there but commented out). had to resolve a cyclic goto->hashchange->goto... situation since they have to invoke each other depending on whether the nav action is native (hashchange->goto) or programmatic (goto->hashchange).

should work now.
