### ISSUE TITLE
False attributes set `attr=""`

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#78]
I was sure I'd raised this before, but could not find an issue. Apologies if this is a repeat.

I have code like so:

    nod=[ "label.selection",[
            [ "input."+typ, {
                name: grp,
                type: typ,
                checked: chc.selected,
                enabled: chc.available,
                }],
            NBS,
            chc.text
            ]];

which results in: "`... checked="" ...` when `chc.selected` is false.

Is that expected? Given that `checked=""` sets the attribute to the logical equivalent of `true`, I'd expected that boolean attribute `false` values should suppress the attribute altogether.

(I swear we've had this conversation before!)

**Comment by lawrence-dol** [comment]
`checked: null` works to suppress the attr, so:

            checked: (chc.selected ? "" : null),

but that quite verbose.

**Comment by leeoniya** [comment]
unable to reproduce: https://jsfiddle.net/ux0hgsfy/1/

**Comment by lawrence-dol** [comment]
It seems to be no longer happening since I updated to 1.2.5 (dev).
