### ISSUE TITLE
reduce cost of 0 mutations

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#80]
the fastest vdom libs still have up to 2x perf advantage at 1% mutation rate in the dbmonster bench (85fps vs 160fps on my laptop). need to see where the low hanging fruit are for optimizing costly funcs and further reducing GC/alloc. here's the current profile:

![dbmon-profile](https://cloud.githubusercontent.com/assets/43234/16049290/bbd7dc72-321c-11e6-8a90-787eae8a5956.png)

**Comment by leeoniya** [comment]
![domvm-profile](https://cloud.githubusercontent.com/assets/43234/16718523/6d9eac64-46e6-11e6-94b5-4bcdae5c4d5e.png)

**Comment by lawrence-dol** [comment]
Does this indicate you've increased overall performance at low mutation rates by a factor of 2.589?

**Comment by leeoniya** [comment]
no, i just let it run for some random amount of time and collect relative stats. so you can tell where the hotspots are that can use some attention. the fact that patch() the GC as a % of overall dropped is notable. but i think that the diff between the two is 1% vs 0% mutations. so don't take too much away from this. overall things have improved, but it's easiest to tell from frp counter in dbmonster.

**Comment by leeoniya** [comment]
@lawrence-dol 

On a related note, i just pushed https://github.com/leeoniya/domvm/commit/5dee7161629f265d64c6cf26d327aad83add1ba1 which provides a less ugly way to do cheap sCU diffing. i enabled this in dbmonster and the 0% mutation case went from 4ms overhead to 0.5ms overhead. You could have achieved this already by caching and returning `false` from render, but this construct was rather grotesque.

Compare:

https://github.com/leeoniya/domvm/blob/5dee7161629f265d64c6cf26d327aad83add1ba1/test/bench/dbmonster/app.js#L67-L81

vs 

https://github.com/leeoniya/domvm/blob/f0768ee41d0a17fcdec948636409c9152b777509/test/bench/dbmonster/app.js#L68-L86

**Comment by leeoniya** [comment]
all perf issues resolved in `2.x-dev`
