### ISSUE TITLE
How deep can you nest views?

### ISSUE THREAD

**Issue by Veid** [leeoniya/domvm#81]
```
function LiView(vm, item) {
  return function() { return ["li", item.text];};
}

function ItemView(vm, item) {
	return function() {
        return [LiView, item];
	};
}

function ListView(vm, items) {
	return function() {
		return ["ul", items.map(function(item) {
			return [ItemView, item];
		})];
	}
}

var vm = domvm.view(ListView, items).mount(document.body);
```

This doesn't seem to work. If I change ItemView like so:

```
function ItemView(vm, item) {
	return function() {
        return ["li", item.text];
	};
}
```

Then it is fine. Can you only nest 1 level deep?

EDIT:
I realized my mistake after posting. The first part in `ItemView` must be a `string` tagname...

**Comment by Veid** [comment]
Sorry for the post, I realized my mistake after posting. The first parameter in `ItemView` really must be a `string` tagname.

**Comment by leeoniya** [comment]
@Veid thanks for trying out domvm :)

let me know if you have any other questions about how to get things done. there are a lot of features that are not documented yet, see #36.

should i close this?

**Comment by Veid** [comment]
Thank you! So far so good, I'm loving domvm 👍 Closed.
