### ISSUE TITLE
Explain: Using subviews

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#82]
@leeoniya 

If this is in the docs already I can't find it. Could you please briefly explain the difference between using a subview with the following two forms:

```js
["#ui",                                                     // same as "div#ui"
    [SomeViewFn],                                           // sub-view w/closured data
    preInitVm,                                              // pre-initialized ViewModel
]
```

Also, I noticed now that the docs only have up to 3 arguments for a subview: `function,model,key`. Is this current? I thought there was a fourth, `options`.

Thanks.

**Comment by iamjohnlong** [comment]
@lawrence-dol checkout pattern C

**Comment by lawrence-dol** [comment]
So, if I follow correctly, with

    function PeopleView(vm, people) {
        return function() {
            return ["ul.people-list", people.list.map(function(person) {
                // imperative sub-view composition (model exposes its own view)
                return person.vm;
            })];
        };
    }

the `Person` view exists for the lifetime of the `Person` object, but with

    function PeopleView(vm, people) {
        return function() {
            return ["ul.people-list", people.list.map(function(person) {
                // imperative sub-view composition (model exposes its own view)
                return [Person];
            })];
        };
    }

the `Person` view exists for the lifetime of the underlying HTML node?

**Comment by leeoniya** [comment]
> Could you please briefly explain the difference between using a subview with the following two forms...

It's declarative `[SomeViewFn]` vs imperative `preInitVm` composition. In the first case you have no external access to the `vm` that gets created for this view, so you cannot issue an `redraw()` to it. In the second version, you have the `vm` that you just inject into another template and you have more control if you need it. There is especially important if your view exposes its own API/state via `vm.api`.

> Also, I noticed now that the docs only have up to 3 arguments for a subview: function,model,key. Is this current? I thought there was a fourth, options.

Yes, there is an `options` arg. You can use it to pass in `hooks` or a `watch` observer that will auto-fire on all bound dom events. I will note this in #36.

**Comment by leeoniya** [comment]
i think i actually understand where the confusion is now and should probably update the docs.

`[SomeViewFn]` doesnt make much sense, cause there is not any kind of view "identity" there, it would only make sense for a static view that would be better off as just a sub-template generating function.

`[SomeViewFn, data]` would make more sense here. in both cases, the views will exist as long as `data` exists.

**Comment by leeoniya** [comment]
i've removed `[SomeViewFn]` from the docs, it has no use case and should be replaced by a sub-template generator.

**Comment by lawrence-dol** [comment]
> i've removed `[SomeViewFn]` from the docs

Thanks. 

That then leads to related questions: Is there any significant cost difference in performance or memory between using a sub-template generator and a sub-view? Should granular sub-views be avoided unless there is a need to interact with it as a separate component/view-model?

**Comment by leeoniya** [comment]
>  Is there any significant cost difference in performance or memory between using a sub-template generator and a sub-view? Should granular sub-views be avoided unless there is a need to interact with it as a separate component/view-model?

There is a small cost to sub-views, which needs some investigation: https://github.com/leeoniya/domvm/issues/65. If you do not need isolated redraw, a view api or sub-view state, I would recommend using sub-templates. Remember also that you can maintain temporary state directly on the vnodes between `render()` firing and the event handler invocation via `_data` and `_ref`.

**Comment by leeoniya** [comment]
@lawrence-dol it looks like in recent versions, the sub-view overhead has been reduced. in addition, if you have immutable data that you can cheaply diff between redraws, you can use sub-views to greatly increase perf as well.

the situation is somewhat nuanced and depends a lot on your data. i just pushed f0768ee41d0a17fcdec948636409c9152b777509 which implements a sub-view based dbmonster with optional immutability optimizations. Notice that the keys in all the subviews are `false`, which speeds up the diff by avoiding any subview reordering lookups and treating them as slots (it works in this dbmonster case because we have knowledge of how the data mutates, same for the immutability optims).

Play around with it in all 3 variations across the full range of mutations 0%-100% and look at how the FPS behaves as well as the cost of the "view update" (ms).

**Comment by leeoniya** [comment]
gonna close this, but feel free to inquire further if still needed.
