### ISSUE TITLE
Error Handling in Views / Failing Gracefully / Coding Defensively

### ISSUE THREAD

**Issue by grumpi** [leeoniya/domvm#88]
JavaScript errors in views currently can break an app irrecoverably (see https://jsfiddle.net/4u6x45fe/3/).

Admittedly, the ideal solution is to only write error-free code. But the reality is that there will at some point be an error that makes its way to the user.

As a non-expert JavaScript developer I'm wondering: what is a good way to code defensively in order to avoid breaking the whole app with a failing view?

Is wrapping my views in `try`/`catch` blocks a good idea or a bad idea?

I'm not suggesting that domvm itself should `try`/`catch` the view functions - I think that wouldn't be a good idea, unless the error can be re-raised in a way that doesn't break the app (after redraw is complete?).

I'm just looking at how to set up a single-page-application around domvm that fails in a reasonably graceful way when I shoot myself in the foot.

Anyone willing to share how they deal with minimizing the effect of errors in their apps?

ETA: Ok, what is written at https://www.sitepoint.com/proper-error-handling-javascript/ tells me that plastering `try`/`catch` all over my own view code is probably not a good idea. If I reraise the error in the view's `catch` block, execution stops and the app breaks just as before. If I don't reraise the error, I'm introducing a bad code smell that makes debugging unnecessarily hard.

**Comment by leeoniya** [comment]
I'm not sure why this example screws up as it does while this seems to do ok:
https://jsfiddle.net/4u6x45fe/7/

In general, typed and compiled JS variants like TypeScript [1], Flow [2], Google Closure annotations [2] help prevent various errors like these. At runtime having most of these checks end up degrading performance (definitely in V8 where try/catch will not be JIT-optimized) and instrumenting every place with checks leads to code which is difficult to read.

[1] https://www.typescriptlang.org/
[2] https://flowtype.org/
[3] https://developers.google.com/closure/compiler/docs/js-for-compiler

**Comment by grumpi** [comment]
Fair enough. Static types do reduce the risk of accidentally doing stupid things like that. I'm personally leaning towards TypeScript since that seems least invasive/opinionated.

I can still accidentally mess things up, though. E.g. if I don't verify my API actually delivers data in the format expected by the SPA. Admittedly, for my own API, I could figure out how to automatically generate properly type-annotated code and then get great value out of type checking.

> I'm not sure why this example screws up as it does while this seems to do ok:

Here, this makes it fail in what I believe to be the same way mine failed: https://jsfiddle.net/4u6x45fe/10/

I seem to get additional DOM nodes every second iteration.

**Comment by leeoniya** [comment]
interesting, thanks. i'll need to look into this.

**Comment by leeoniya** [comment]
so there's a fairly elegant solution here which would require an extra layer, but would work.

`render()` can return `false` instead of a template to indicate no changes, so you can wrap the template generation in a `try/catch` that console.logs and returns `false`: https://jsfiddle.net/4u6x45fe/11/

this is the simplest user-space solution. i can technically do the same thing within the lib as per https://github.com/leeoniya/domvm/commit/1b96a14e3a1bf510f839169e386e69059f692953, and it seems from initial benchmarks that there's no penalty, though I'm very hesitant to bake this into the lib as default behavior and discover otherwise in the future.

**Comment by leeoniya** [comment]
gonna close this, but feel free to discuss further.

**Comment by lawrence-dol** [comment]
> though I'm very hesitant to bake this into the lib as default behavior and discover otherwise in the future

Given that's it's trivially easy to simply wrap every render-function in a generic try/catch/log function, I wouldn't.

    return function() {
        view...
        };

vs.

    return catchAll(function() {
        view...
        });

**Comment by grumpi** [comment]
I see. Yes, I've been playing around in `domvm/src/view.js` as well. Wrapping `render()` seemed to be the most elegant/simple thing to do in order to stop the DOM from exploding after an error occurs in a view function.

I agree that it's not a good idea to bake this naive solution into `domvm` itself since catching and logging errors like that is too specific/opinionated. There might be other patterns we haven't thought of that would work better, or be more appropriate in particular situations.

@lawrence-dol It looks like we've been thinking the same thing. Though, having an explicit wrapper means that I need to never forget to wrap things which might blow up.

Maybe there is some way that allows to provide a wrapper that is automatically applied to all `render()` functions? (I suppose an application could "monkey-patch" `domvm.view` to automatically apply the wrapper.)

Maybe it should be possible to register a `renderErrorHandler()` with domvm that will be called from the catch block?

Maybe it's just a topic for the documentation? Saying that `domvm` requires error-free view functions really isn't unreasonable. That leaves taking measures to ensure error-free views is up to the application.

I'm just a clueless person with a talent to break things. :) Since the goal of `domvm` is to stay flexible, please never feel rushed to change things because I found another way to wreak havoc out of ignorance.

**Comment by grumpi** [comment]
Attempt to do error-handling by monkey-patching `domvm.view` at https://jsfiddle.net/4u6x45fe/15/.

**Comment by lawrence-dol** [comment]
@grumpi : Putting something like this in your setup code should work:

    vm.view=function() {
        vm._viewFunction=vm.view;
        vm.view=function() {
            try { vm._viewFunction.apply(Array.prototype.slice.call(arguments)); } 
            catch(thr) { console.error("View exception:",thr); }
        }
    };

**Comment by leeoniya** [comment]
@grumpi that monkey patch passes most but not all the tests. if you'd like this functionality baked in, just do a custom domvm build (which won't break anything).

**Comment by grumpi** [comment]
I just realized that my monkey patch in the jsfiddle only seems to apply the wrapper function to the top-level views. 

Turns out I needed to patch `createView()` instead of `domvm.view()` in order to end up wrapping each and every single subview. That appears to work but isn't a monkey patch anymore since I need to change `domvm/src/view.js`.

Yes, looks like this is a case for a custom build at this point (either that, or I'm missing another obvious point where I can try monkey-patching). If I'm doing a custom domvm build, I suppose the most reasonable place to patch is right around the `render()` call. :)

When I change `domvm` to internally call `domvm.view()` instead of `createView()`, I can apply the monkey patch successfully. This feels quite reasonable to me, since it lets me keep the app-specific error-handling out of `domvm`.

**Comment by leeoniya** [comment]
>  I suppose the most reasonable place to patch is right around the `render()` call. :)

it's already in the code, just uncomment: https://github.com/leeoniya/domvm/commit/1b96a14e3a1bf510f839169e386e69059f692953

**Comment by lawrence-dol** [comment]
Would it not make more sense to leave this as the developer's choice, using something like:

    domvm.view.extend(function(vm) {
        let renderFnc=vm.render;
        vm.render=function(api,vm,model,key) {
            try { return renderFnc(api,vm,model,key); }
            catch(exc) {
                console.log(exc);
                return false;
                }
            }
        });

Which keeps the actual error handling in application space?
