### ISSUE TITLE
Maintaining view state

### ISSUE THREAD

**Issue by Veid** [leeoniya/domvm#90]
I have something like this:

```js
function RowView(vm, state) {
	var w = domvm.watch().on(function() {
		vm.redraw();
	});

	var c = w.prop('red');

	return function() {
		return ["tr", {
			onclick: flip,
			class: c()
		}, state.text];
	};

	function flip() {
		if (c() === 'red') {
			c('blue');
		} else {
			c('red');
		}
	}
}

function BodyView(vm, state) {
	return function() {
		return ["tbody", [
			state.displayItems.map(function(itemData) {
				return [RowView, {
					text : itemData.text,
					_key : itemData.key
				}];

			})
		]];
	}
}

function TableView(vm, state) {
	return function() {
		return ["table", [
			[BodyView, {
				displayItems : state.displayItems
			}]
		]];
	};
}

var items = [
	{
		text: 'one',
		key : 1
	},
	{
		text: 'two',
		key : 2
	},
];

var vm = domvm.view(TableView, {displayItems:items}).mount(document.body);
```

So if I click the items, they toggle between red and blue. If I had a function that sorted the items then called `vm.redraw()`, `c` will get reset to red regardless of `_key` in `BodyView`. Where would you put this kind of state?

Another example might be a `tr` with some information and a button. You click the button and it can be in one of three possible states: `ready`, `in progress`, `done`. If you have a list of `n` items, you might have a few items with a `ready` button, a few `in progress`, and a few `done`. If sort the list, they would all get reset to `ready` -- using the method above.

I would have thought, since I set the `_key` attribute that the node would be (reused??) and only the return function will execute?

How would you approach this?

**Comment by leeoniya** [comment]
`_key` is for keying elements: `["div", {_key: 123}]`, to key the views, you have to pass them as a third param: `[RowView, {text : itemData.text}, itemData.key]`

[1] https://jsfiddle.net/88otx64e/

**Comment by leeoniya** [comment]
you can do a bunch of simplification here as well [1]

- child arrays dont need to be explicit, so reduce braces
- if objects in `items` are persistent, they don't need to have keys, since views will use the objects - themselves as keys by default. (assumption of model persistence).
- each `w.prop` has a `.toString` and can be compared via `==` without invoking the getter.
- since all `w.prop` are functions/getters, they can be used directly as values and attributes in templates without invocation. (domvm will invoke them for you).
`domvm.watch` factory accepts a handler as a param without needing `.on`

[1] https://jsfiddle.net/88otx64e/5/

**Comment by leeoniya** [comment]
@Veid 

something else i'll advise it to not over-componentize unless/until you need to maintain state and do granular redraw. doing premature componentization makes the templates less readable for little benefit. i would recommend useing sub-template generating functions [1] or staying monolithic [2] until you have perf problems. making every node a component is far from necessary and will actually negatively affect perf.

[1] https://jsfiddle.net/88otx64e/8/
[2] https://jsfiddle.net/88otx64e/7/

**Comment by Veid** [comment]
@leeoniya 

This is all tremendously helpful, thank you!

About point two, "if objects in `items` are persistent, they don't need to have keys...". So if I wanted to implement sorting in the above example, e.g.

`items = _.sortBy(items, 'text');`

If I was using my original, over-componentized  example, would I have to key both the `BodyView` and each individual `RowView`?

**Comment by leeoniya** [comment]
> If I was using my original, over-componentized example, would I have to key both the BodyView and each individual RowView?

basically if you recreate the state/model on each redraw (which you do by making a new object `{displayItems: state.displayItems}`, you have to *either* key it by some fixed value or peristent object or explicitly unkey it via `false`. If domvm sees the old model has disappeared it will unmount the view, destroy the dom and recreate everything. so, any of these will work to maintain the view state and recycle the dom:

```js
// a persistent model
var model = {};

// this is just shorthand [View, model, model], where the
// model also serves as the key (assumed persistent)
[View, model]

// an ad-hoc re-generated wrapper (model as key)
[View, {myModel: model}, model]

// an ad-hoc re-generated wrapper (fixed key)
[View, {myModel: model}, 'fixed_key']
[View, {myModel: model}, model.id]

// explicitly unkeyed (essentially a slot that maintains
// view state that can have the model swapped)
[View, model, false]
[View, {myModel: model}, false]
```

the fixed-key and false-key versions can be used with immutable structures where models get replaced wholesale but you still need to recycle the dom. however false-key views will not follow/track the model if a list is sorted, they just stay in place.

hope some of that makes sense.

**Comment by leeoniya** [comment]
also, you can just make the wrapper itself persistent:

```js
function TableView(vm, state) {
    var wrap = {displayItems : state.displayItems};
    return function() {
        return ["table",
            [BodyView, wrap]
        ];
    };
}
```

**Comment by leeoniya** [comment]
closing, but feel free to discuss further.

**Comment by Veid** [comment]
This is great, thanks again! I felt I was doing something strange in my toy examples. For example:

```
function HeadView(vm, state) {
	return function() {
		return ["thead", [
			["tr", state.columnOrder.map(function(columnItem) {
				return ["th", [
					["span", {
						onclick: vm.emit.bind(this, 'sortByChange', columnItem)
					}, 'blah'
					]
				]];
			})]
		]];
	};
}
```

If instead I decomponentized it, as in your fiddles:


```
function HeadTpl(args) {
	return ["thead", [
		["tr", args.columnOrder.map(function(columnItem) {
			return ["th", [
				["span", {
					onclick: vm.emit.bind(this, 'sortByChange', columnItem)
				}, 'blah'
				]
			]];
		})]
	]];
}
```

But then I'm left with the issue of how I was using the `vm` that got passed to each view: `vm.emit.bind(this, 'sortByChange', columnItem)`

So then instead of using an ad-hoc regenerated wrapper, as I was doing. I could do something like this:

```
function TableView(vm, tableModel) {
	return function() {
		return ["table", [
			HeadTpl(tableModel),
			BodyTpl(tableModel)
		]];
	};
}
```

Where tableModel is something like:

```
function TableModel(args) {
	this.displayItems = args.items;
	// more stuff
}
TableModel.prototype = {
	sortBy: function(sortKey) {
		this.displayItems = _.sortBy(displayItems, sortKey);
		...
		// where do you call redraw() though? Pass the vm into here
		// then call args.vm.redraw()?
		// or maybe use domvm.watch?
	}
}
```

Then inside of `HeadTpl`:

```
function HeadTpl(tableModel) {
	return ["thead", [
		["tr", tableModel.columnOrder.map(function(columnItem) {
			return ["th", [
				["span", {
					onclick: tableModel.sortBy.bind(this, columnItem)
				}, 'blah'
				]
			]];
		})]
	]];
}
```

So then each sub-template inside of the table view gets the `tableModel`.

**Comment by leeoniya** [comment]
yep, that looks better 👍

**Comment by leeoniya** [comment]
> where do you call redraw() though? Pass the vm into here then call args.vm.redraw()? or maybe use domvm.watch?

Sorry, i missed this. This problem is kind of why i prefer to do view-wrapping models:

```js
// model
function Table() {
	// model-view binding
	this.vm = domvm.view(TableView, this);
}

Table.prototype = {
	sortBy: function(col) {
		// sort...
		vm.redraw();
	}
};

// view
function TableView(vm, table) {
	return function() {
		return ["table",
			HeadTpl
			BodyTpl
		];
	}
	
	function HeadTpl() {
		return ["thead", ...];
	}
	
	function BodyTpl() {
		return ["tbody", ...];
	}
}
```

this gives you bi-directional comm.
