### ISSUE TITLE
Rendering in Node.js throws when using attributes

### ISSUE THREAD

**Issue by yosbelms** [leeoniya/domvm#92]
The following snippet fails:
```js
function SomeView() {
    return function() {
        return ['div#foo', {foo: 'bar'}, 'some text']
    }
}

var vm = domvm.view(SomeView)
vm.mount()
console.log(domvm.html(vm.node))
```
The rendering routine calls `utils.isElem` during the process, which causes to throw `RefereceError: HTMLElement is not defined`. I looked at the code and I see that `val instanceof HTMLElement` is the root of this error. May be `typeof HTMLElement !== 'undefined'` or choosing a different strategy for Node.js could solve the problem.

**Comment by leeoniya** [comment]
thanks! good catch.

next release will have a breaking change for Node related to lazy rendering landing as of https://github.com/leeoniya/domvm/issues/89#issuecomment-231615332

you'll now need to call a target-less `.mount()` to get the vtree to build out after initializing the view. the SSR test/example has been updated to reflect this [1].

[1] https://github.com/leeoniya/domvm/blob/1.x-dev/test/node-ssr.js

**Comment by yosbelms** [comment]
I've thought could be good to allow `domvm.html` to accept `vm`, not just nodes, example:
```js
vm   = domvm.view(SomeView)
html = domvm.html(vm)

// domvm.html(vm.node)
// should work fine too
```

**Comment by leeoniya** [comment]
originally `.html()` was a vm method until it was spun off into its own module and i figured you can really pass it any vnode.

you're right that it should accept either a node *or* vm and it can handle the empty `mount()` implicitly if the vm's node is null.

**Comment by yosbelms** [comment]
I've been thinking about it last night, you can see my proposal, about 9 LOCs in two commits, I'm sure you may think a better solution anyway:

https://github.com/yosbelms/domvm/commits/1.x-dev

**Comment by leeoniya** [comment]
@yosbelms thanks!

i already use the presence of of `.render()` in other places to discern vms from other objects, so i'll stick with this for now. i also beat you to the [near identical] implementation by 15min :)

https://github.com/leeoniya/domvm/commit/00d5db4127e3fd0603eae9ec365cceccc18c8e2c

I'll skip throwing on invalid nodes; if you don't follow the docs, you're on your own!

**Comment by yosbelms** [comment]
Thats convergence... regarding I adopt the coding standard of the project I'm contributing to, and the simplicity of the solution, every implementation would looks near identical.

> i also beat you [...] :)

Well, I wrote the code yesterday but copied/pasted/pushed this morning to discuss about it, since I have no internet in home :(

**Comment by yosbelms** [comment]
@lawrence-dol I live in Cuba, remember.

**Comment by lawrence-dol** [comment]
@yosbelms : I wasn't smiling at the no internet part. I was smiling (in approval) at the idea of adopting the coding standards and philosophy of the project. I didn't actually notice the no internet at home part until just now. Though, now that I do, it's hard for us to relate to up here unless some is way out in the country and off-grid.

**Comment by leeoniya** [comment]
huh

https://blog.cloudflare.com/the-cuban-cdn/

**Comment by yosbelms** [comment]
yeah, aliased "USB Channel"
