### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#93]
## Roadmap

Arranged broadly in order of implementation difficulty, BC risk, usefulness.
### 1.3.0
- [watch]  fetch -> promisified xhr (via alite [1] or own impl). will reduce need for polyfills, allow progress listeners, aborting requests.
- [route] `prefix: "#"`. in place of `useHist` + `root` combo
- route parsing/gener tests
- lifecycle hook tests
- improve dom reordering algo to be bidi and avoid some unnecessary dom ops for sibling swapping, etc.
- ensure node hydration respects `wasSame` and leaf nodes with non-array body don't get hydrated since this is handled by recycling pass.
### 1.x
- immutability mode (assumes all models are immutable), may break inter-op if global pref
- decouple mount/unmount from elem insert/removal (for view dom reuse)
- unmounted view DOM reuse, via `canRecycle(newView)` hook or `viewFn` similarity
- ? fuller impl of root node swapping
- ? evaluate moving from QUnit to more lightweight ospec [2]
### 2.0.0
- streams instead of promises
- invert persistence assumption; default to unkeyed views, `true` -> key = model
- evaluate removing any rarely-used features that can improve perf / reduce code size
- ? explicit child arrays
- ? hyperscript
- ? rootless views

[1] https://github.com/chrisdavies/alite
[2] https://github.com/lhorie/mithril.js/tree/rewrite/ospec

**Comment by yosbelms** [comment]
Fetch is standard [1] something to take in consideration, anyways XHR will be always there.

> ? evaluate moving from QUnit to more lightweight ospec

+1 `opspec` looks clean and simple, I've been using `jasmine` in several projects and I have no regrets.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by leeoniya** [comment]
there are some good arguments for using XMLHttpRequest over fetch made here [1]

[1] https://github.com/lhorie/mithril.js/blob/rewrite/docs/request.md#why-xmlhttprequest-instead-of-fetch

**Comment by yosbelms** [comment]
These arguments are enough to me. +1 XHR.

Promises cancellation has been long discussed around the Web (example, https://esdiscuss.org/topic/cancelable-promises) but sadly none of them has arrived to definitive clonclusions.

**Comment by yosbelms** [comment]
Hey @leeoniya have you thought of _isomorphic_ router? If you cheer up you may want to check [this](http://github.com/flatiron/director) out

**Comment by grumpi** [comment]
@yosbelms the current router implementation from domvm actually **is** isomorphic. At 284 lines of code it's doing just what I need and nothing more.

**Comment by leeoniya** [comment]
the main issue with routing isomorphism is that the only commonality between client and server are GET routes. anything beyond that you have to figure out what a client-side POST route should do, whether your client side router now has to proxy all your ajax requests and hold your server's api endpoints. at this point you're getting into more opinionated territory. is a router now required to invoke an app's `addUser()` or should addUser contain the necessary endpoint itself, including response handling/redraw? client-side requests have only url while server-side has http headers, file uploads, server env variables, database/file io, etc, etc. "isomorphism" is fully dismanteled at this point and we're literally writing different routers perhaps with some cosmetic similarity in basic setup/config.

a lot of questions emerge that require opinionated answers and a lot more routing code.

that being said, feel free to simply use another router with domvm if it has sufficient isomorphism for you. nothing in domvm's router is special aside from maybe the href generator from defined routes, but this can be added to any other router that exposes its route config.

**Comment by yosbelms** [comment]
@leeoniya  I'm aware I can use any other router thanks to the domvm decoupling. My point is a simple server routing to allow render in the server as in the client-side, make the routing code shareable just like views.

The flow is grab the route and dispatch. For advanced request/response flow should be used another router, `express` may be.

**Comment by leeoniya** [comment]
@yosbelms can you open another issue to discuss the router and explain how you envision it working? currently the routes do not return views, they simply have their handlers invoked once they are matched, so i'm not sure i understand how you expect it to function differently than it already does now (including on the server).

**Comment by yosbelms** [comment]
I'll make some isomorphic experiments before to open an issue to give solid arguments.

**Comment by leeoniya** [comment]
thanks @yosbelms,

btw, @grumpi's been hard at work on an isomorphic implementation, check out: https://github.com/leeoniya/domvm/issues/67 as well as https://github.com/grumpi/domvm-isomorphic-example
