### ISSUE TITLE
Focusing a textarea

### ISSUE THREAD

**Issue by Veid** [leeoniya/domvm#95]
Hello,

I have something like this:

```js
if (state == 'editable') {
	return ["div", {
		onclick : function() {
			state = 'editing';
			vm.redraw();
		}
	},[
		['div', [
			["span", text]
		]]
	]];
} else if (state == 'editing') {
	return ["div", [
		['textarea', {
			onblur: function() {
				state = 'editable';
				vm.redraw();
			},
		}, text]
	]];
} else {
	console.log("PENDING");
}
```

How would I go about focusing the `textarea` when `state == 'editing'`? Would it involve `_hooks`?

**Comment by leeoniya** [comment]
HTML5 has an `autofocus` attribute but it seems to only work on initial page load, otherwise i'd say use that since the textarea gets recreated. Yeah you can use _hooks/didInsert or vm.hook()/didRedraw with a a state check.

It may be a useful thing to add to domvm and make any defined `autofocus` work on insert/reInsert. or maybe a custom `focused` prop to avoid surprises.

**Comment by yosbelms** [comment]
@Veid, a solution could be the following:

```js
// use hook/didRedraw
vm.hook({
    didRedraw: function() {
        // if editing and a reference named `editor` exists execute `focus()`
        // see the renderer where the `ref` is settled
        state === 'editing' && vm.refs.editor && vm.refs.editor.el.focus()
    }
})

return function() {
    if (state == 'editable') {
        return ["div", {
                onclick : function() {
                    state = 'editing';
                    vm.redraw();
                }
            },
            ['div',
                ["span", text]
            ]
        ];
    } else if (state == 'editing') {
        return ["div",
            ['textarea', {
                // here we store this node (the textarea, not the DOM node but the domvm node)
                // as `editor`, it can be accessed by `vm.ref.editor`, `el` references the DOM node, hence,
                // vm.ref.editor.el.focus() will focus the element
                _ref: 'editor',
                onblur: function() {
                    state = 'editable';
                    vm.redraw();
                },
            }, text]
        ];
    } else {
        console.log("PENDING");
    }
}
```

**Comment by Veid** [comment]
@leeoniya Yes I tried autofocus, but it did not work correctly... I like the `focused` prop idea -- I actually tried doing that, before I posted here, just to see if it worked :) Thanks for your response!

@yosbelms Thanks for the example! I ended up doing just about what you have

**Comment by lawrence-dol** [comment]
I can testify that `autofocus` will **not** work. As @leeoniya said, it seemed only to work at page load, and then unreliably. I ended up having to trigger code to request the focus when I changed the view.

**Comment by leeoniya** [comment]
since implementing `focused` would necessitate the user to also track where the focus should be at all times (when multiple inputs are involved), i'm gonna leave things simple and as-is.
