### ISSUE TITLE
is +1k (min) worth an improved keyed algo?

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#99]
There are currently some specific situations when domvm does sub-optimal DOM ops when it comes to reordering sibling keyed nodes or model-bound subviews. For example, swapping siblings or moving a sibling upwards.

If we take a keyed list: `a,b,c,d` and move `a` to the end in the model, domvm will:

1. move `b` ahead of `a`
1. move `c` ahead of `a`
1. then `d` ahead of `a`

In the same list, if we swap `a` and `d`, domvm will:

1. move `d` ahead of `a`
1. move `b` ahead of `a`
1. then `c` ahead of `a`

Logically, the first op should perform a single move and the second should perform two. For small sibling counts the difference is negligible, but in certain benchmarks with huge tables, 1 move vs 1000 makes a big difference.

I have written an alternate implementation of the internal `hydrateNode` method which better handles this type of reordering (essentially it's a tweaked [1] with a fall-through to a selection sort [2] which minimizes the number of needed move ops, but pays for it in [typically much cheaper] lookups). It would only have any effect on lists of keyed siblings/views and only in [what i'd consider unusual] cases similar to above. The perf with the patch is about 1-2% slower on dbmonster than the current dumb [but effective] algo. With a bit of work I could probably get it to break even.

However, the smarter algo adds ~1k (min) to the lib size which cannot be squeezed much further. The $1M question being, is it worth it?

[1] https://github.com/localvoid/kivi/blob/master/lib/vnode.ts#L1224-L1259
[2] https://en.wikipedia.org/wiki/Selection_sort

--
cc @lawrence-dol @yosbelms @grumpi @devmondo @tamasnet

**Comment by lawrence-dol** [comment]
For a large list where it matters, what, if any, options does the app programmer have to mitigate the naive reordering? Would one simply have to change the key on all entries?

And what is the "big difference" for 1000 moves on typical hardware (meaning average hardware in the current market)?

**Comment by leeoniya** [comment]
> For a large list where it matters, what, if any, options does the app programmer have to mitigate the naive reordering? Would one simply have to change the key on all entries?

If your nodes are keyed (or subviews are *not* `false`-keyed . . . aka you view state is bound to the physical dom element), then there's nothing you can do in app-space to solve this. You could use slotted views with false keys so the dom can be reused and you will get 1000x updates instead of 1000x moves, which is often faster. If your nodes are not keyed, then you will have the same 1000x updates.

> And what is the "big difference" for 1000 moves on typical hardware (meaning average hardware in the current market)?

It's hard to say because it really depends on the complexity of each node and how long a browser will need to repaint everything. For simple tables it could be 4ms vs 40ms on a desktop machine. But it could be 50ms vs 500ms even on modern mobile.

**Comment by leeoniya** [comment]
On my work machine, (my ThinkPad T440s would be maybe half this):

(Chromium v54)
```
 1k:  35ms vs  59ms
10k: 399ms vs 819ms
```

```js
function List(vm, list) {
	return function() {
		return ["div",
			list.map(function(item) {
				return ["div", {_key: item}, item];
			})
		];
	};
}

var list = [];

for (var i = 0; i < 1000; i++)
	list[i] = i;

var vm = domvm.view(List, list).mount(document.body);

setTimeout(function() {
	list.push(list.shift());
	vm.redraw();
}, 1000);
```

**Comment by lawrence-dol** [comment]
If it's 1K before gzip compression *and* DOMVM is feature complete or nearly so, I say go for it. Indeed, as long as the download size for DOMVM remains under 10K I think we're in a good place. Once it starts growing beyond that, it seems like we're losing site of the lean, mean, DOM-producing machine goal. It's a tough call in this space, but if I had to choose now, I'd say the speed gain is worth it -- cutting code size after the fact is likely easier than cutting code execution time.

**Comment by leeoniya** [comment]
this is implemented in `2.x-dev`
